/* Quiz question bank for the Corrupted Miku deck (Shalai, Voice of Plenty).
   Each question: { id, topic, q, options, answer (index or array of indices), explain, cards }.
   Topics: combos, tutors, cards, rules, plan, mana. Card mentions use <i-c>Exact Card Name</i-c>. */
window.CORRUPTED_QUIZ = [
  /* ---------- combos ---------- */
  { id: "thune-feeder-partner", topic: "combos",
    q: "Which card makes an infinite combo with <i-c>Archangel of Thune</i-c> on its own?",
    options: ["<i-c>Vizier of Remedies</i-c>", "<i-c>Destiny Spinner</i-c>", "<i-c>Spike Feeder</i-c>", "<i-c>Devoted Druid</i-c>"],
    answer: 2,
    explain: "Feeder removes a counter to gain 2 life, Archangel puts a counter back on each creature. Repeat forever.",
    cards: ["Archangel of Thune","Spike Feeder"] },
  { id: "thune-feeder-mana", topic: "combos",
    q: "How much mana does each loop of <i-c>Archangel of Thune</i-c> plus <i-c>Spike Feeder</i-c> cost?",
    options: ["None", "{2}", "{G}", "{1}"],
    answer: 0,
    explain: "Feeder's life-gain ability only costs removing a +1/+1 counter. Its {2} ability is the other one, which moves a counter to a creature." },
  { id: "thune-feeder-speed", topic: "combos",
    q: "When can you run the <i-c>Archangel of Thune</i-c> plus <i-c>Spike Feeder</i-c> loop?",
    options: ["Only during combat", "Only in your main phase", "Any time you have priority, even on an opponent's turn", "Only during your turn"],
    answer: 2,
    explain: "Feeder's ability is an activated ability with no timing restriction, so it works at instant speed. That's why it's a great answer to a wipe on the stack." },
  { id: "thune-feeder-sick", topic: "combos",
    q: "You cast <i-c>Spike Feeder</i-c> this turn. <i-c>Archangel of Thune</i-c> is out. Can you start the loop right away?",
    options: ["Only if Archangel has been out since your turn began", "No, Feeder is summoning sick", "Only with <i-c>Lightning Greaves</i-c> on Feeder", "Yes, Feeder's ability doesn't use {T}"],
    answer: 3,
    explain: "Summoning sickness only stops attacking and abilities with {T} or {Q} in the cost. Removing a counter isn't tapping." },
  { id: "thune-feeder-per-loop", topic: "combos",
    q: "After one full loop of <i-c>Spike Feeder</i-c> with <i-c>Archangel of Thune</i-c>, what changed?",
    options: ["+2 life, and Feeder has one more counter than before", "+1 life, and Feeder has one more counter", "+2 life, and every creature except Feeder has one more counter", "+2 life, and only Archangel got a counter"],
    answer: 2,
    explain: "Feeder lost a counter and got one back, so it's even. You gained 2, and every other creature you control is one counter bigger." },
  { id: "thune-feeder-last-counter", topic: "combos",
    q: "<i-c>Spike Feeder</i-c> has one +1/+1 counter left. <i-c>Archangel of Thune</i-c> is out. What happens if you remove that counter to gain 2?",
    options: ["Feeder survives because it's a Spike", "Feeder survives because Archangel's counter arrives in time", "Feeder dies as a 0/0 before the ability resolves, and the loop stops", "Nothing, you can't remove the last counter"],
    answer: 2,
    explain: "State-based actions kill a 0/0 before the life gain resolves. You still gain 2 and Archangel triggers, but Feeder is gone. Keep Feeder at 2 counters." },
  { id: "thune-feeder-outlet", topic: "combos",
    q: "You have infinite life and huge creatures from <i-c>Archangel of Thune</i-c> and <i-c>Spike Feeder</i-c>. Which card on the battlefield turns it into a win without attacking?",
    options: ["<i-c>Heliod, Sun-Crowned</i-c>", "<i-c>Kutzil, Malamet Exemplar</i-c>", "<i-c>Gavony Township</i-c>", "<i-c>Walking Ballista</i-c>"],
    answer: 3,
    explain: "Ballista gets a counter each loop. Remove them to deal 1 damage each to any target, enough to ping out every opponent.",
    cards: ["Walking Ballista"] },
  { id: "heliod-ballista-counters", topic: "combos",
    q: "How many +1/+1 counters does <i-c>Walking Ballista</i-c> need for the <i-c>Heliod, Sun-Crowned</i-c> loop?",
    options: ["1", "It doesn't need any", "2 or more", "3 or more"],
    answer: 2,
    explain: "With one counter, removing it makes Ballista a 0/0 that dies before Heliod's trigger can put a counter on it. With two, it drops to one and gets the counter back.",
    cards: ["Heliod, Sun-Crowned","Walking Ballista"] },
  { id: "heliod-ballista-mana", topic: "combos",
    q: "What do you pay to start the <i-c>Heliod, Sun-Crowned</i-c> plus <i-c>Walking Ballista</i-c> loop, once Ballista has enough counters?",
    options: ["{4} per ping", "{W} per ping", "{1}{W} once, for lifelink", "{1}{W} per ping"],
    answer: 2,
    explain: "Heliod's {1}{W} gives Ballista lifelink until end of turn. After that, each ping gains 1 life and Heliod puts the counter back for free." },
  { id: "heliod-ballista-steps", topic: "combos",
    q: "Put the Heliod plus Ballista loop in order. Which list is right?",
    options: ["Give lifelink, Heliod puts a counter on Ballista, then ping", "Give lifelink, remove a counter to ping, gain 1 life, Heliod puts a counter on Ballista", "Ping, give lifelink, gain life, Heliod puts a counter on Ballista", "Gain life, give lifelink, ping, Heliod puts a counter on Heliod"],
    answer: 1,
    explain: "Lifelink first. Each ping is lifelink damage, the life gain triggers Heliod, and Heliod's trigger targets Ballista." },
  { id: "heliod-not-creature", topic: "combos",
    q: "Your devotion to white is 2. Does the <i-c>Heliod, Sun-Crowned</i-c> plus <i-c>Walking Ballista</i-c> loop work?",
    options: ["No, Heliod must be a creature", "Yes, Heliod's abilities work while it's only an enchantment", "Only with <i-c>Archangel of Thune</i-c> out", "Only if Ballista has three counters"],
    answer: 1,
    explain: "Heliod's devotion clause only decides whether it's a creature. Its trigger and lifelink ability work either way." },
  { id: "heliod-feeder-result", topic: "combos",
    q: "What do <i-c>Heliod, Sun-Crowned</i-c> and <i-c>Spike Feeder</i-c> make together?",
    options: ["Infinite life", "Infinite green mana", "Infinite damage", "Infinitely large creatures"],
    answer: 0,
    explain: "Feeder gains 2, Heliod puts the counter back on Feeder. Heliod only gives one counter, so only the life grows.",
    cards: ["Heliod, Sun-Crowned","Spike Feeder"] },
  { id: "druid-vizier-result", topic: "combos",
    q: "What do <i-c>Devoted Druid</i-c> and <i-c>Vizier of Remedies</i-c> make together?",
    options: ["Infinite mana of any color", "Infinite life", "Infinite +1/+1 counters", "Infinite green mana"],
    answer: 3,
    explain: "The Druid taps for {G}. Its untap cost is a -1/-1 counter, and Vizier reduces that to zero. Only green.",
    cards: ["Devoted Druid","Vizier of Remedies"] },
  { id: "druid-sick", topic: "combos",
    q: "You cast <i-c>Devoted Druid</i-c> and <i-c>Vizier of Remedies</i-c> this turn. Can you go infinite now?",
    options: ["Yes, the untap ability has no {T}", "No, the Druid needs {T} to make mana and it's summoning sick", "Yes, if you have <i-c>Gaea's Cradle</i-c>", "No, Vizier is summoning sick"],
    answer: 1,
    explain: "The loop needs the Druid's {T}: Add {G}. Cast it a turn early, or give it haste with <i-c>Lightning Greaves</i-c>. Vizier's ability is static, so Vizier can be new." },
  { id: "druid-alone", topic: "combos",
    q: "No Vizier. How many times can a fresh <i-c>Devoted Druid</i-c> untap itself and survive?",
    options: ["Twice", "Never", "As long as it has toughness", "Once"],
    answer: 3,
    explain: "It's a 0/2. One -1/-1 counter leaves it 0/1. A second makes it 0/0 and it dies. The counter stays on it in later turns too." },
  { id: "druid-outlets", topic: "combos",
    q: "You have infinite green mana from Druid and Vizier. Which cards turn it into a win? (choose all that apply)",
    options: ["<i-c>Finale of Devastation</i-c> with X of 10 or more", "<i-c>Walking Ballista</i-c>", "<i-c>Heliod, Sun-Crowned</i-c>'s {1}{W}", "<i-c>Shalai, Voice of Plenty</i-c>'s {4}{G}{G}, then attack"],
    answer: [0,1,3],
    explain: "Ballista's costs are generic. Finale and Shalai's ability take green. Heliod's ability needs {W}, which the Druid can't make, and it isn't a win on its own." },
  { id: "finale-ballista-trap", topic: "combos",
    q: "You have infinite green mana. Why not cast <i-c>Finale of Devastation</i-c> with a huge X to get <i-c>Walking Ballista</i-c>?",
    options: ["Finale can't have X over 10", "Ballista enters with zero counters and dies", "Ballista would be exiled", "Finale can't find artifacts"],
    answer: 1,
    explain: "Ballista's counters depend on the X you paid to cast it. Put onto the battlefield by Finale, X is 0. Cast Ballista from hand instead, or get Craterhoof." },
  { id: "finale-ten", topic: "combos",
    q: "What extra does <i-c>Finale of Devastation</i-c> do when X is 10 or more?",
    options: ["Opponents can't block", "It finds two creatures", "You draw ten cards", "Creatures you control get +X/+X and gain haste until end of turn"],
    answer: 3,
    explain: "With Craterhoof as the target, every creature gets +X/+X and haste from Finale, then Hoof's trigger adds more and trample.",
    cards: ["Finale of Devastation","Craterhoof Behemoth"] },
  { id: "second-ballista-counter", topic: "combos",
    q: "<i-c>Walking Ballista</i-c> has one counter and <i-c>Heliod, Sun-Crowned</i-c> is out. Which ways give it the second counter it needs? (choose all that apply)",
    options: ["Ballista's own {4}", "<i-c>Gavony Township</i-c>", "<i-c>Lightning Greaves</i-c>", "<i-c>Shalai, Voice of Plenty</i-c>'s {4}{G}{G}"],
    answer: [0,1,3],
    explain: "All three add a +1/+1 counter. Greaves adds no counter, and its shroud would stop Heliod from targeting Ballista." },
  { id: "thune-wipe-deluge", topic: "combos",
    q: "An opponent casts Toxic Deluge paying 6 life. You have <i-c>Archangel of Thune</i-c> and <i-c>Spike Feeder</i-c> but no Ballista. Best play?",
    options: ["Loop in response until your creatures have toughness over 6", "Let it resolve, then rebuild", "Activate <i-c>Shalai, Voice of Plenty</i-c> once", "Cast <i-c>Flawless Maneuver</i-c>"],
    answer: 0,
    explain: "X is locked when Deluge is cast. Loop at instant speed and your creatures are too big for -6/-6. Indestructible doesn't help against -X/-X." },
  { id: "thune-wipe-ballista", topic: "combos",
    q: "Someone casts a wipe. You have <i-c>Archangel of Thune</i-c>, <i-c>Spike Feeder</i-c> and <i-c>Walking Ballista</i-c>. What do you do?",
    options: ["Cast <i-c>Teferi's Protection</i-c>", "Sacrifice <i-c>Ranger-Captain of Eos</i-c>", "Nothing, hexproof saves you", "Loop in response and ping every opponent out before the wipe resolves"],
    answer: 3,
    explain: "The whole combo is instant speed. Win with the wipe still on the stack." },
  { id: "tp-blocks-lifegain", topic: "combos",
    q: "You cast <i-c>Teferi's Protection</i-c> earlier this round. Can you win with Feeder and Archangel before your next turn?",
    options: ["No, your life total can't change, so no life is gained and nothing triggers", "Yes, they're instant speed", "Yes, but only with Ballista", "Only if Archangel attacks"],
    answer: 0,
    explain: "Teferi's Protection stops your life total changing until your next turn. Your permanents are phased out too.",
    cards: ["Teferi's Protection"] },
  { id: "thune-no-ballista", topic: "combos",
    q: "You loop <i-c>Archangel of Thune</i-c> and <i-c>Spike Feeder</i-c> without any Ballista. How do you win?",
    options: ["You win immediately with infinite life", "Opponents lose when you reach 1000 life", "You can't win, so don't loop", "Attack with your huge creatures, flying Shalai and Archangel first"],
    answer: 3,
    explain: "Infinite life alone doesn't win. Your creatures are huge, so attack. Chump blocks and fogs can still save them, so find Ballista if you can." },
  { id: "combo-pieces-white", topic: "combos",
    q: "Which combo pieces are white? (choose all that apply)",
    options: ["<i-c>Vizier of Remedies</i-c>", "<i-c>Heliod, Sun-Crowned</i-c>", "<i-c>Devoted Druid</i-c>", "<i-c>Spike Feeder</i-c>", "<i-c>Archangel of Thune</i-c>"],
    answer: [0,1,4],
    explain: "Archangel, Heliod and Vizier are white. Feeder and the Druid are green. Ballista is colorless." },
  { id: "chord-feeder-win", topic: "combos",
    q: "<i-c>Archangel of Thune</i-c> is on the battlefield. It's an opponent's end step. Which play wins right now?",
    options: ["<i-c>Chord of Calling</i-c> for <i-c>Spike Feeder</i-c> (X=3)", "<i-c>Green Sun's Zenith</i-c> for <i-c>Spike Feeder</i-c>", "<i-c>Natural Order</i-c> for <i-c>Spike Feeder</i-c>", "<i-c>Worldly Tutor</i-c> for <i-c>Spike Feeder</i-c>"],
    answer: 0,
    explain: "Chord is an instant that puts Feeder onto the battlefield with its two counters. GSZ and Natural Order are sorceries, and Worldly only puts it on top." },
  { id: "feeder-enters-counters", topic: "combos",
    q: "<i-c>Spike Feeder</i-c> is put onto the battlefield by <i-c>Natural Order</i-c>. How many counters does it have?",
    options: ["1", "2", "0, it dies", "It depends on X"],
    answer: 1,
    explain: "It \"enters with two +1/+1 counters\" however it enters. Ballista is different: its counters come from the X paid when casting." },

  /* ---------- tutors ---------- */
  { id: "tut-ballista-not", topic: "tutors",
    q: "Which tutor can't usefully get <i-c>Walking Ballista</i-c>?",
    options: ["<i-c>Recruiter of the Guard</i-c>", "<i-c>Ranger-Captain of Eos</i-c>", "<i-c>Chord of Calling</i-c>", "<i-c>Enlightened Tutor</i-c>"],
    answer: 2,
    explain: "Chord puts Ballista onto the battlefield without casting it, so it enters with zero counters and dies. The others put it in hand or on top." },
  { id: "tut-ranger-targets", topic: "tutors",
    q: "What can <i-c>Ranger-Captain of Eos</i-c> find?",
    options: ["A green creature card", "A creature card with mana value 1 or less", "Any creature card", "A creature card with toughness 2 or less"],
    answer: 1,
    explain: "Mana value 1 or less: Ballista, the one-mana dorks, Giver, Esper Sentinel, Dryad Arbor.",
    cards: ["Ranger-Captain of Eos"] },
  { id: "tut-recruiter-targets", topic: "tutors",
    q: "What can <i-c>Recruiter of the Guard</i-c> find?",
    options: ["A creature card with mana value 2 or less", "A creature card with power 2 or less", "A white creature card", "A creature card with toughness 2 or less"],
    answer: 3,
    explain: "Toughness 2 or less. That includes Ballista and Feeder (0/0 printed), Druid (0/2) and Vizier (2/1).",
    cards: ["Recruiter of the Guard"] },
  { id: "tut-recruiter-not", topic: "tutors",
    q: "Which card can <i-c>Recruiter of the Guard</i-c> NOT find?",
    options: ["<i-c>Kutzil, Malamet Exemplar</i-c>", "<i-c>Solitude</i-c>", "<i-c>Spike Feeder</i-c>", "<i-c>Grand Abolisher</i-c>"],
    answer: 0,
    explain: "Kutzil is a 3/3. Abolisher is 2/2, Feeder 0/0 and Solitude 3/2." },
  { id: "tut-recruiter-not-2", topic: "tutors",
    q: "Which of these can <i-c>Recruiter of the Guard</i-c> find? (choose all that apply)",
    options: ["<i-c>Aven Mindcensor</i-c>", "<i-c>Voice of Victory</i-c>", "<i-c>Thalia, Heretic Cathar</i-c>", "<i-c>Drannith Magistrate</i-c>"],
    answer: [0,2],
    explain: "Thalia is 3/2 and Mindcensor 2/1. Drannith and Voice of Victory are 1/3." },
  { id: "tut-heliod-enlightened", topic: "tutors",
    q: "Can <i-c>Enlightened Tutor</i-c> find <i-c>Heliod, Sun-Crowned</i-c>?",
    options: ["Only from the graveyard", "No, it's a creature card", "Yes, it's an enchantment card", "Only when your devotion is under five"],
    answer: 2,
    explain: "Heliod is a Legendary Enchantment Creature. Enlightened finds any artifact or enchantment card.",
    cards: ["Enlightened Tutor","Heliod, Sun-Crowned"] },
  { id: "tut-heliod-not", topic: "tutors",
    q: "Which tutors can NOT find <i-c>Heliod, Sun-Crowned</i-c>? (choose all that apply)",
    options: ["<i-c>Ranger-Captain of Eos</i-c>", "<i-c>Eladamri's Call</i-c>", "<i-c>Summoner's Pact</i-c>", "<i-c>Green Sun's Zenith</i-c>"],
    answer: [0,2,3],
    explain: "GSZ and Pact need green, and Heliod is white. Ranger-Captain needs mana value 1 or less, and Heliod is 3. Eladamri's finds any creature." },
  { id: "tut-chord-heliod-x", topic: "tutors",
    q: "What X do you need on <i-c>Chord of Calling</i-c> to get <i-c>Heliod, Sun-Crowned</i-c>?",
    options: ["2", "5", "1", "3"],
    answer: 3,
    explain: "Heliod's mana value is 3. Chord with X=3 costs {3}{G}{G}{G}, and convoke helps pay." },
  { id: "tut-chord-thune-x", topic: "tutors",
    q: "What X do you need on <i-c>Chord of Calling</i-c> or <i-c>Finale of Devastation</i-c> to get <i-c>Archangel of Thune</i-c>?",
    options: ["5", "6", "3", "4"],
    answer: 0,
    explain: "Archangel costs {3}{W}{W}, mana value 5." },
  { id: "tut-thune-not", topic: "tutors",
    q: "Which tutor can find <i-c>Archangel of Thune</i-c>?",
    options: ["<i-c>Summoner's Pact</i-c>", "<i-c>Natural Order</i-c>", "<i-c>Archdruid's Charm</i-c>", "<i-c>Green Sun's Zenith</i-c>"],
    answer: 2,
    explain: "Archdruid's Charm finds any creature card to hand. The other three need a green creature." },
  { id: "tut-green-only", topic: "tutors",
    q: "Which tutors only find green creatures? (choose all that apply)",
    options: ["<i-c>Green Sun's Zenith</i-c>", "<i-c>Chord of Calling</i-c>", "<i-c>Summoner's Pact</i-c>", "<i-c>Finale of Devastation</i-c>", "<i-c>Natural Order</i-c>"],
    answer: [0,2,4],
    explain: "Chord and Finale find any creature with low enough mana value." },
  { id: "tut-gsz-feeder", topic: "tutors",
    q: "How much do you pay for <i-c>Green Sun's Zenith</i-c> to get <i-c>Spike Feeder</i-c>?",
    options: ["{3}{G}{G}", "{2}{G}", "{3}{G}", "{1}{G}{G}"],
    answer: 2,
    explain: "Feeder's mana value is 3, so X=3: {3}{G}." },
  { id: "tut-gsz-hoof", topic: "tutors",
    q: "How much mana does <i-c>Green Sun's Zenith</i-c> need for <i-c>Craterhoof Behemoth</i-c>?",
    options: ["4", "10", "9", "8"],
    answer: 2,
    explain: "Hoof's mana value is 8. X=8 plus {G} is nine mana." },
  { id: "tut-worldly-dest", topic: "tutors",
    q: "Where does <i-c>Worldly Tutor</i-c> put the creature card?",
    options: ["Into your graveyard", "Onto the battlefield", "On top of your library", "Into your hand"],
    answer: 2,
    explain: "On top. Cast it at the end of the opponent's turn before yours and draw the card in your draw step." },
  { id: "tut-enlightened-finds", topic: "tutors",
    q: "Which of these can <i-c>Enlightened Tutor</i-c> find? (choose all that apply)",
    options: ["<i-c>Urza's Saga</i-c>", "<i-c>Walking Ballista</i-c>", "<i-c>Spike Feeder</i-c>", "<i-c>Destiny Spinner</i-c>"],
    answer: [0,1,3],
    explain: "Ballista is an artifact, Spinner an enchantment creature, Saga an enchantment land. Feeder is just a creature." },
  { id: "tut-gearhulk", topic: "tutors",
    q: "What does <i-c>Brightglass Gearhulk</i-c> find when it enters?",
    options: ["Up to two land cards", "One artifact card with mana value 2 or less", "Up to two artifact, creature and/or enchantment cards with mana value 1 or less", "One creature card with toughness 2 or less"],
    answer: 2,
    explain: "Two cards: Ballista plus <i-c>Sol Ring</i-c>, or Ballista plus <i-c>Deafening Silence</i-c>, for example.",
    cards: ["Brightglass Gearhulk"] },
  { id: "tut-gearhulk-pair", topic: "tutors",
    q: "Which pair can <i-c>Brightglass Gearhulk</i-c> find together?",
    options: ["<i-c>Walking Ballista</i-c> and <i-c>Mana Vault</i-c>", "<i-c>Survival of the Fittest</i-c> and <i-c>Sol Ring</i-c>", "<i-c>Walking Ballista</i-c> and <i-c>Lightning Greaves</i-c>", "<i-c>Devoted Druid</i-c> and <i-c>Vizier of Remedies</i-c>"],
    answer: 0,
    explain: "Both have mana value 1 or less. Greaves, Druid, Vizier and Survival all have mana value 2." },
  { id: "tut-survival", topic: "tutors",
    q: "What does one activation of <i-c>Survival of the Fittest</i-c> cost?",
    options: ["{1}{G} and discard any card", "{G} and sacrifice a creature", "{2} and discard a creature card", "{G} and discard a creature card"],
    answer: 3,
    explain: "{G}, discard a creature card: search for a creature card. It works at instant speed.",
    cards: ["Survival of the Fittest"] },
  { id: "tut-charm-modes", topic: "tutors",
    q: "Which is NOT a mode of <i-c>Archdruid's Charm</i-c>?",
    options: ["Return a creature card from your graveyard to hand", "Put a +1/+1 counter on your creature, then it deals damage to a creature you don't control", "Exile target artifact or enchantment", "Search for a creature or land card"],
    answer: 0,
    explain: "The three modes are tutor, the counter-and-damage mode, and exile an artifact or enchantment. A land it finds enters tapped; a creature goes to hand." },
  { id: "tut-pact-cost", topic: "tutors",
    q: "What happens at your next upkeep after you cast <i-c>Summoner's Pact</i-c>?",
    options: ["Pay 4 life or lose the game", "Pay {2}{G}{G} or lose the game", "Pay {2}{G} or lose the game", "Sacrifice a creature"],
    answer: 1,
    explain: "{2}{G}{G}, or you lose. Only cast it when you can pay, or when you win this turn.",
    cards: ["Summoner's Pact"] },
  { id: "tut-finale-graveyard", topic: "tutors",
    q: "Your <i-c>Archangel of Thune</i-c> died. Which tutor can put it back onto the battlefield from your graveyard?",
    options: ["<i-c>Green Sun's Zenith</i-c>", "<i-c>Chord of Calling</i-c>", "<i-c>Eladamri's Call</i-c>", "<i-c>Finale of Devastation</i-c>"],
    answer: 3,
    explain: "Finale searches your library and/or graveyard. With X=5 it puts Archangel straight back. <i-c>Eternal Witness</i-c> can also return it to hand." },
  { id: "tut-druid-vizier-both", topic: "tutors",
    q: "Which tutor on a body can find both <i-c>Devoted Druid</i-c> and <i-c>Vizier of Remedies</i-c>, one each time?",
    options: ["<i-c>Recruiter of the Guard</i-c>", "<i-c>Eternal Witness</i-c>", "<i-c>Brightglass Gearhulk</i-c>", "<i-c>Ranger-Captain of Eos</i-c>"],
    answer: 0,
    explain: "Both have toughness 2 or less. They have mana value 2, which is too high for Ranger-Captain and Gearhulk." },
  { id: "tut-vizier-green", topic: "tutors",
    q: "Can <i-c>Summoner's Pact</i-c> find <i-c>Vizier of Remedies</i-c>?",
    options: ["No, Vizier is white", "Only during your upkeep", "Yes", "Only if Druid is on the battlefield"],
    answer: 0,
    explain: "Pact finds green creatures only. It can get the Druid, not the Vizier." },
  { id: "tut-instant-list", topic: "tutors",
    q: "Which tutors are instants? (choose all that apply)",
    options: ["<i-c>Chord of Calling</i-c>", "<i-c>Eladamri's Call</i-c>", "<i-c>Finale of Devastation</i-c>", "<i-c>Natural Order</i-c>", "<i-c>Worldly Tutor</i-c>"],
    answer: [0,1,4],
    explain: "Finale and Natural Order are sorceries, and so is Green Sun's Zenith." },
  { id: "tut-natural-order-not", topic: "tutors",
    q: "Which card can <i-c>Natural Order</i-c> put onto the battlefield?",
    options: ["<i-c>Heliod, Sun-Crowned</i-c>", "<i-c>Archangel of Thune</i-c>", "<i-c>Spike Feeder</i-c>", "<i-c>Walking Ballista</i-c>"],
    answer: 2,
    explain: "It needs a green creature card. Feeder is green; with Archangel or Heliod out, it wins." },
  { id: "tut-ranger-dryad", topic: "tutors",
    q: "Which of these can <i-c>Ranger-Captain of Eos</i-c> find? (choose all that apply)",
    options: ["<i-c>Esper Sentinel</i-c>", "<i-c>Giver of Runes</i-c>", "<i-c>Dryad Arbor</i-c>", "<i-c>Devoted Druid</i-c>"],
    answer: [0,1,2],
    explain: "Giver and Sentinel have mana value 1, Dryad Arbor 0. The Druid costs {1}{G}, mana value 2." },
  { id: "tut-saga-sentinel", topic: "tutors",
    q: "Can <i-c>Urza's Saga</i-c> find <i-c>Esper Sentinel</i-c>?",
    options: ["No, its mana cost is {W}, not {0} or {1}", "Yes, its mana value is 1", "Only on chapter II", "Yes, it's an artifact"],
    answer: 0,
    explain: "The Saga checks the mana cost itself. {W} isn't {1}." },
  { id: "tut-top-vs-hand", topic: "tutors",
    q: "You want <i-c>Spike Feeder</i-c> and will cast it next turn. It's the end of the opponent's turn before yours. Cheapest good tutor?",
    options: ["<i-c>Natural Order</i-c>", "<i-c>Finale of Devastation</i-c>", "<i-c>Green Sun's Zenith</i-c>", "<i-c>Worldly Tutor</i-c>"],
    answer: 3,
    explain: "{G} at instant speed, and you draw it in your draw step. The others are sorceries anyway." },

  /* ---------- cards ---------- */
  { id: "card-shalai-cost", topic: "cards",
    q: "What does <i-c>Shalai, Voice of Plenty</i-c> cost?",
    options: ["{2}{G}{W}", "{3}{W}", "{2}{W}", "{3}{W}{W}"],
    answer: 1,
    explain: "{3}{W}, mana value 4, a 3/4 flier.",
    cards: ["Shalai, Voice of Plenty"] },
  { id: "card-shalai-ability-cost", topic: "cards",
    q: "What does <i-c>Shalai, Voice of Plenty</i-c>'s activated ability cost?",
    options: ["{4}{G}{G}", "{4}{W}{W}", "{2}{G}{W}", "{2}{G}{G}"],
    answer: 0,
    explain: "{4}{G}{G}: a +1/+1 counter on each creature you control, Shalai included. <i-c>Gavony Township</i-c> is the one with {2}{G}{W}." },
  { id: "card-shalai-self", topic: "cards",
    q: "Who does <i-c>Shalai, Voice of Plenty</i-c> give hexproof to? (choose all that apply)",
    options: ["Other creatures you control", "Shalai herself", "Planeswalkers you control", "You", "Your noncreature artifacts"],
    answer: [0,2,3],
    explain: "Not Shalai herself, and not your noncreature artifacts, enchantments or lands." },
  { id: "card-thune-cost", topic: "cards",
    q: "What is the mana value of <i-c>Archangel of Thune</i-c>?",
    options: ["3", "4", "6", "5"],
    answer: 3,
    explain: "{3}{W}{W}. Chord or Finale need X=5 for it.",
    cards: ["Archangel of Thune"] },
  { id: "card-heliod-cost", topic: "cards",
    q: "What does <i-c>Heliod, Sun-Crowned</i-c> cost?",
    options: ["{2}{W}", "{3}{W}", "{2}{W}{W}", "{1}{W}"],
    answer: 0,
    explain: "{2}{W}, mana value 3. Its lifelink ability costs {1}{W}." },
  { id: "card-ballista-mv", topic: "cards",
    q: "What is <i-c>Walking Ballista</i-c>'s mana value in your library?",
    options: ["2", "0", "4", "1"],
    answer: 1,
    explain: "X counts as 0 outside the stack. That's why <i-c>Ranger-Captain of Eos</i-c> and <i-c>Brightglass Gearhulk</i-c> can find it." },
  { id: "card-druid-stats", topic: "cards",
    q: "What are <i-c>Devoted Druid</i-c>'s cost and stats?",
    options: ["{1}{G}, 1/2", "{1}{G}, 0/2", "{2}{G}, 0/3", "{G}, 0/1"],
    answer: 1,
    explain: "{1}{G} for a 0/2. It can survive one -1/-1 counter on its own." },
  { id: "card-vizier-text", topic: "cards",
    q: "What does <i-c>Vizier of Remedies</i-c> do?",
    options: ["Removes a -1/-1 counter at each upkeep", "Prevents all -1/-1 counters on your creatures", "Gives your creatures +1/+1", "One fewer -1/-1 counter is put on each of your creatures"],
    answer: 3,
    explain: "\"That many minus one.\" One counter becomes zero, which is exactly what the Druid's untap cost needs." },
  { id: "card-abolisher", topic: "cards",
    q: "What does <i-c>Grand Abolisher</i-c> stop during your turn?",
    options: ["Opponents casting noncreature spells", "All activated abilities, including yours", "Opponents casting spells and activating abilities of artifacts, creatures or enchantments", "Opponents casting spells only"],
    answer: 2,
    explain: "Spells and those abilities. Land abilities and triggered abilities still happen.",
    cards: ["Grand Abolisher"] },
  { id: "card-kutzil", topic: "cards",
    q: "What does <i-c>Kutzil, Malamet Exemplar</i-c> stop?",
    options: ["Opponents can't cast spells during your turn", "Opponents can't search libraries", "Opponents can't cast noncreature spells", "Opponents can't activate abilities during your turn"],
    answer: 0,
    explain: "Spells only. Abilities still work. It also draws when boosted creatures connect.",
    cards: ["Kutzil, Malamet Exemplar"] },
  { id: "card-on-your-turn", topic: "cards",
    q: "Which cards stop opponents from casting spells during your turn, every turn? (choose all that apply)",
    options: ["<i-c>Kutzil, Malamet Exemplar</i-c>", "<i-c>Thalia, Heretic Cathar</i-c>", "<i-c>Voice of Victory</i-c>", "<i-c>Grand Abolisher</i-c>", "<i-c>Drannith Magistrate</i-c>"],
    answer: [0,2,3],
    explain: "Drannith only stops casting from places other than hand. Thalia makes things enter tapped." },
  { id: "card-ranger-sac", topic: "cards",
    q: "What does sacrificing <i-c>Ranger-Captain of Eos</i-c> do?",
    options: ["Opponents can't cast spells this turn", "Your creatures gain hexproof", "Opponents can't activate abilities this turn", "Opponents can't cast noncreature spells this turn"],
    answer: 3,
    explain: "Noncreature spells only. An opponent could still flash in a creature." },
  { id: "card-orims", topic: "cards",
    q: "What does kicked <i-c>Orim's Chant</i-c> add?",
    options: ["Creatures can't attack this turn", "It also stops abilities", "You draw a card", "It hits every opponent"],
    answer: 0,
    explain: "Kicker {W}: creatures can't attack this turn. That includes yours, so don't kick it on your attack turn.",
    cards: ["Orim's Chant"] },
  { id: "card-silence-vs-orims", topic: "cards",
    q: "What's the difference between <i-c>Silence</i-c> and <i-c>Orim's Chant</i-c>?",
    options: ["Silence costs {1}{W}", "Silence hits all opponents, Orim's Chant one target player", "Orim's Chant also stops abilities", "Silence is a sorcery"],
    answer: 1,
    explain: "Both cost {W} and are instants. Silence stops all your opponents; Orim's Chant targets one player, with a kicker to stop attacks." },
  { id: "card-spinner", topic: "cards",
    q: "Which spells does <i-c>Destiny Spinner</i-c> make uncounterable?",
    options: ["Your legendary spells", "All your spells", "Your creature and enchantment spells", "Your green spells"],
    answer: 2,
    explain: "Creatures and enchantments. That covers every combo piece, Heliod included, but not your tutors.",
    cards: ["Destiny Spinner"] },
  { id: "card-halfling", topic: "cards",
    q: "Which spells can use <i-c>Delighted Halfling</i-c>'s colored mana? (choose all that apply)",
    options: ["<i-c>Shalai, Voice of Plenty</i-c>", "<i-c>The One Ring</i-c>", "<i-c>Archangel of Thune</i-c>", "<i-c>Spike Feeder</i-c>", "<i-c>Heliod, Sun-Crowned</i-c>"],
    answer: [0,1,4],
    explain: "Only legendary spells, and they can't be countered. Archangel and Feeder aren't legendary." },
  { id: "card-drannith", topic: "cards",
    q: "What does <i-c>Drannith Magistrate</i-c> stop?",
    options: ["Opponents casting more than one spell", "Opponents' creatures entering untapped", "Opponents casting spells from anywhere but their hand", "Opponents searching libraries"],
    answer: 2,
    explain: "No commanders from the command zone, no flashback, no casting from the top of the library.",
    cards: ["Drannith Magistrate"] },
  { id: "card-mindcensor", topic: "cards",
    q: "What does <i-c>Aven Mindcensor</i-c> do to your own tutors?",
    options: ["Your tutors cost {1} more", "Nothing, it only affects opponents", "You can't search at all", "You search only the top four"],
    answer: 1,
    explain: "\"If an opponent would search a library.\" Your searches are untouched." },
  { id: "card-deafening", topic: "cards",
    q: "Who does <i-c>Deafening Silence</i-c> affect?",
    options: ["Only opponents", "Each player, you included", "Only during your turn", "Only creature spells"],
    answer: 1,
    explain: "Each player can cast only one noncreature spell each turn. Your creatures are fine, but Chrome Mox then Sol Ring is two noncreature spells.",
    cards: ["Deafening Silence"] },
  { id: "card-giver", topic: "cards",
    q: "What can <i-c>Giver of Runes</i-c> target?",
    options: ["Another creature you control", "Any permanent you control", "Itself only", "Any creature"],
    answer: 0,
    explain: "Another creature you control gets protection from colorless or a color until end of turn. Shalai is the usual target." },
  { id: "card-greaves", topic: "cards",
    q: "What does <i-c>Lightning Greaves</i-c> give, and what does equip cost?",
    options: ["Haste and indestructible, equip {2}", "Haste and hexproof, equip {1}", "Shroud only, equip {0}", "Haste and shroud, equip {0}"],
    answer: 3,
    explain: "Haste and shroud for {0}. Shroud also stops your own spells and abilities targeting the creature." },
  { id: "card-flawless", topic: "cards",
    q: "When can you cast <i-c>Flawless Maneuver</i-c> for free?",
    options: ["When your commander is in the command zone", "On an opponent's turn", "When you control three creatures", "When you control a commander"],
    answer: 3,
    explain: "With Shalai on the battlefield it costs nothing. It gives your creatures indestructible until end of turn.",
    cards: ["Flawless Maneuver"] },
  { id: "card-tp", topic: "cards",
    q: "What does <i-c>Teferi's Protection</i-c> do? (choose all that apply)",
    options: ["Your life total can't change until your next turn", "All permanents you control phase out", "Your creatures gain indestructible", "You gain protection from everything"],
    answer: [0,1,3],
    explain: "Indestructible is <i-c>Flawless Maneuver</i-c>. Teferi's Protection is exiled after it resolves." },
  { id: "card-hoof", topic: "cards",
    q: "What does <i-c>Craterhoof Behemoth</i-c>'s enters trigger give your creatures?",
    options: ["+X/+X and trample", "+2/+2 and trample", "+X/+X and haste", "Trample and haste"],
    answer: 0,
    explain: "+X/+X and trample until end of turn, where X is your creature count. Only Hoof itself has haste.",
    cards: ["Craterhoof Behemoth"] },
  { id: "card-vorinclex", topic: "cards",
    q: "What does <i-c>Vorinclex, Voice of Hunger</i-c> do to opponents' lands?",
    options: ["A land they tap for mana doesn't untap during their next untap step", "Their lands make one less mana", "They can't play lands", "They enter tapped"],
    answer: 0,
    explain: "And your lands make double mana. It's close to land denial, so mention it pregame.",
    cards: ["Vorinclex, Voice of Hunger"] },
  { id: "card-solitude-evoke", topic: "cards",
    q: "How do you cast <i-c>Solitude</i-c> for free?",
    options: ["Return a Plains to your hand", "Evoke: exile a white card from your hand", "Evoke: exile a green card from your hand", "Pay 4 life"],
    answer: 1,
    explain: "Evoke it, the exile trigger still happens, then it's sacrificed. <i-c>Endurance</i-c> and <i-c>Force of Vigor</i-c> exile green cards." },

  /* ---------- rules ---------- */
  { id: "rule-own-hexproof", topic: "rules",
    q: "Can <i-c>Heliod, Sun-Crowned</i-c> give lifelink to your <i-c>Walking Ballista</i-c> while Shalai gives it hexproof?",
    options: ["Only if Heliod is a creature", "Only if you remove Shalai first", "No, hexproof stops all targeting", "Yes, hexproof only stops opponents"],
    answer: 3,
    explain: "Hexproof means it can't be the target of spells or abilities your opponents control." },
  { id: "rule-greaves-ballista", topic: "rules",
    q: "<i-c>Lightning Greaves</i-c> is on <i-c>Walking Ballista</i-c>. What happens to the Heliod loop?",
    options: ["It fails: shroud stops Heliod's lifelink and its trigger from targeting Ballista", "It works, but costs more", "It works normally", "It works twice as fast"],
    answer: 0,
    explain: "Shroud stops everyone, you included. Move Greaves first: equip it to another creature for {0} in your main phase." },
  { id: "rule-shalai-wipe", topic: "rules",
    q: "Does Shalai's hexproof save your creatures from a Wrath of God style wipe?",
    options: ["Yes", "Only if Shalai survives", "Only your combo pieces", "No, wipes don't target"],
    answer: 3,
    explain: "Hexproof only stops targeting. Use <i-c>Flawless Maneuver</i-c> or <i-c>Teferi's Protection</i-c>." },
  { id: "rule-shalai-edict", topic: "rules",
    q: "An opponent casts \"each opponent sacrifices a creature\". What does Shalai do about it?",
    options: ["Only Shalai can be sacrificed", "Nothing, edicts don't target your creatures", "You choose to sacrifice nothing", "It's countered"],
    answer: 1,
    explain: "You choose which creature to sacrifice, so keep a spare dork around." },
  { id: "rule-shalai-counter", topic: "rules",
    q: "Does Shalai's {4}{G}{G} put a counter on Shalai?",
    options: ["Yes, on each creature you control", "Only on attacking creatures", "Only on creatures with hexproof", "No, only on other creatures"],
    answer: 0,
    explain: "\"Each creature you control\", Shalai included." },
  { id: "rule-heliod-tutor", topic: "rules",
    q: "Heliod isn't a creature on the battlefield. Is it a creature card in your library?",
    options: ["Yes", "Only with devotion 5", "No", "Only in the graveyard"],
    answer: 0,
    explain: "The \"isn't a creature\" rule only works on the battlefield. Creature tutors find it." },
  { id: "rule-hoof-x-locked", topic: "rules",
    q: "Craterhoof's trigger resolved with 6 creatures. You then cast a seventh. What does the new creature get?",
    options: ["Nothing from Hoof", "+6/+6 and trample", "+7/+7 and trample", "Only trample"],
    answer: 0,
    explain: "The bonus applies only to creatures on the battlefield when the trigger resolves, and X is fixed then." },
  { id: "rule-hoof-sick", topic: "rules",
    q: "You cast three dorks, then <i-c>Craterhoof Behemoth</i-c>, all this turn. Who can attack?",
    options: ["All of them", "None of them", "Only Hoof and creatures you've controlled since your turn began", "Only Hoof"],
    answer: 2,
    explain: "Hoof has haste. Its trigger gives trample, not haste. The new dorks still count for X." },
  { id: "rule-convoke-sick", topic: "rules",
    q: "Can a creature you cast this turn help convoke <i-c>Chord of Calling</i-c>?",
    options: ["Yes, convoke doesn't use {T}", "Only green creatures", "Only if it has haste", "No, it's summoning sick"],
    answer: 0,
    explain: "Convoke taps creatures as part of paying the cost, which isn't a {T} ability." },
  { id: "rule-gemstone", topic: "rules",
    q: "You're the starting player with <i-c>Gemstone Caverns</i-c> in your opening hand. What can you do with it?",
    options: ["Nothing special: play it as a normal land that taps for {C}", "Exile it for {G}", "Put it on the bottom and draw", "Put it onto the battlefield before the game with a luck counter"],
    answer: 0,
    explain: "The free start only works when you're NOT the starting player.",
    cards: ["Gemstone Caverns"] },
  { id: "rule-pact-silence", topic: "rules",
    q: "An opponent casts <i-c>Silence</i-c> during your upkeep with a <i-c>Summoner's Pact</i-c> trigger. Can you still pay {2}{G}{G}?",
    options: ["Only if you have <i-c>Grand Abolisher</i-c>", "Only with <i-c>Elvish Spirit Guide</i-c>", "No, you lose", "Yes, paying the Pact isn't casting a spell"],
    answer: 3,
    explain: "Silence stops casting spells. Paying for a trigger is fine." },
  { id: "rule-natural-order-sac", topic: "rules",
    q: "Which creatures can you sacrifice to <i-c>Natural Order</i-c>? (choose all that apply)",
    options: ["<i-c>Dryad Arbor</i-c>", "<i-c>Shalai, Voice of Plenty</i-c>", "<i-c>Vizier of Remedies</i-c>", "<i-c>Llanowar Elves</i-c>"],
    answer: [0,3],
    explain: "It must be a green creature. Dryad Arbor is a green land creature. Shalai and Vizier are white." },
  { id: "rule-tap-then-sac", topic: "rules",
    q: "Can you tap <i-c>Elvish Mystic</i-c> for mana and then sacrifice it to <i-c>Natural Order</i-c> in the same casting?",
    options: ["Only if it's summoning sick", "No, a tapped creature can't be sacrificed", "Only with <i-c>Badgermole Cub</i-c>", "Yes, you activate mana abilities before paying costs"],
    answer: 3,
    explain: "Tapped creatures can still be sacrificed. Get the mana first, then pay the extra cost." },
  { id: "rule-abolisher-lands", topic: "rules",
    q: "With <i-c>Grand Abolisher</i-c> out, what can an opponent still do on your turn?",
    options: ["Activate a land's ability, like a channel land in hand", "Cast an instant", "Activate an artifact's ability", "Activate a creature's ability"],
    answer: 0,
    explain: "Abolisher covers spells and abilities of artifacts, creatures and enchantments. Lands aren't on the list." },
  { id: "rule-silence-abilities", topic: "rules",
    q: "You cast <i-c>Silence</i-c>. Which of these can an opponent still do this turn?",
    options: ["Activate a creature's sacrifice ability", "Cast an instant", "Cast a spell from their command zone", "Cast a creature with flash"],
    answer: 0,
    explain: "Silence stops spells, not activated abilities." },
  { id: "rule-giver-wipe", topic: "rules",
    q: "Does <i-c>Giver of Runes</i-c> giving Shalai protection from black save her from Toxic Deluge?",
    options: ["Only if X is under 4", "Only on your turn", "No, -X/-X doesn't target, deal damage or destroy", "Yes"],
    answer: 2,
    explain: "Protection stops damage, enchanting, blocking and targeting. Deluge's -X/-X does none of those." },
  { id: "rule-flawless-deluge", topic: "rules",
    q: "Does <i-c>Flawless Maneuver</i-c> save your creatures from Toxic Deluge?",
    options: ["Only Shalai", "Only creatures with counters", "No, 0 toughness kills them anyway", "Yes, indestructible saves them"],
    answer: 2,
    explain: "A creature with 0 or less toughness is put into the graveyard. That's not destruction, so indestructible doesn't help." },
  { id: "rule-veil-shalai", topic: "rules",
    q: "Does <i-c>Veil of Summer</i-c> protect Shalai herself?",
    options: ["Only from red", "Yes, from blue and black spells and abilities", "No, Shalai never gets hexproof", "Only from counterspells"],
    answer: 1,
    explain: "Veil gives you and permanents you control hexproof from blue and from black this turn. Shalai is a permanent you control." },
  { id: "rule-cradle-earthbend", topic: "rules",
    q: "You earthbend <i-c>Gaea's Cradle</i-c> with <i-c>Badgermole Cub</i-c>. What's true? (choose all that apply)",
    options: ["Tapping Cradle triggers Cub for an extra {G}", "Cradle is a creature with haste, so it can tap right away", "If it dies, it's gone for good", "Cradle gets Shalai's hexproof"],
    answer: [0,1,3],
    explain: "It returns to the battlefield tapped when it dies or is exiled. It also counts itself for Cradle's mana." },
  { id: "rule-orims-yours", topic: "rules",
    q: "You kick <i-c>Orim's Chant</i-c> in your own main phase. Can you attack this turn?",
    options: ["Yes, it only stops the target player", "No, creatures can't attack this turn, yours included", "Only with fliers", "Only with haste creatures"],
    answer: 1,
    explain: "The kicker says creatures can't attack. Don't kick it on a turn you need to attack." },

  /* ---------- plan ---------- */
  { id: "plan-removal-table", topic: "plan",
    q: "The table is full of Swords to Plowshares and Chaos Warp. What do you play first?",
    options: ["<i-c>The One Ring</i-c>", "<i-c>Deafening Silence</i-c>", "Shalai, then combo pieces", "Combo pieces, then Shalai"],
    answer: 2,
    explain: "Shalai's hexproof blanks targeted removal on everything else. Land her before your pieces." },
  { id: "plan-fast-table", topic: "plan",
    q: "An opponent's deck can win on turn 3 with spells from its command zone. What do you deploy first?",
    options: ["<i-c>Smothering Tithe</i-c>", "<i-c>Drannith Magistrate</i-c>", "Shalai", "<i-c>Craterhoof Behemoth</i-c>"],
    answer: 1,
    explain: "Against fast combo, put stax down first: Drannith, Abolisher or Deafening Silence. Shalai can wait a turn." },
  { id: "plan-silence-best", topic: "plan",
    q: "When is <i-c>Silence</i-c> at its best?",
    options: ["In response to a counterspell", "In your end step", "On turn 1", "In an opponent's upkeep on the turn they're about to win"],
    answer: 3,
    explain: "They lose a whole turn of spells. On your own turn, use it only if no Abolisher-type card is out." },
  { id: "plan-silence-own", topic: "plan",
    q: "No Abolisher, Kutzil or Voice of Victory is out. You'll combo this turn with <i-c>Silence</i-c> in hand. When do you cast it?",
    options: ["After the combo resolves", "At the end of your turn", "Before your first combo piece", "In response to their removal spell"],
    answer: 2,
    explain: "Once they've cast an answer, Silence can't stop it. Cast it first." },
  { id: "plan-pact-when", topic: "plan",
    q: "When is the best time to cast <i-c>Summoner's Pact</i-c> if you aren't winning this turn?",
    options: ["During your combat", "At the end of the opponent's turn before yours", "Your first main phase", "In response to a wipe"],
    answer: 1,
    explain: "Your lands and dorks untap right after, so you can pay {2}{G}{G} in your upkeep." },
  { id: "plan-wipe-table", topic: "plan",
    q: "A player at the table runs many wipes. You have a big board and two combo pieces in hand. What do you hold?",
    options: ["Nothing, play everything", "<i-c>Teferi's Protection</i-c> or <i-c>Flawless Maneuver</i-c>", "<i-c>Silence</i-c>", "<i-c>Sylvan Library</i-c>"],
    answer: 1,
    explain: "Hold one protection spell before you overextend." },
  { id: "plan-mull-dorks", topic: "plan",
    q: "Your opener: <i-c>Forest</i-c>, <i-c>Savannah</i-c>, <i-c>Brushland</i-c>, <i-c>Llanowar Elves</i-c>, <i-c>Fyndhorn Elves</i-c>, <i-c>Birds of Paradise</i-c>, <i-c>Elvish Mystic</i-c>. Keep or mulligan?",
    options: ["Keep if Shalai is in the command zone", "Keep, it's lots of mana", "Keep if you're on the draw", "Mulligan, it has nothing to do with the mana"],
    answer: 3,
    explain: "Shalai alone isn't a plan. A hand needs a tutor or a combo piece too." },
  { id: "plan-mull-noland", topic: "plan",
    q: "Your opener: <i-c>Chrome Mox</i-c>, <i-c>Lotus Petal</i-c>, <i-c>Birds of Paradise</i-c>, <i-c>Walking Ballista</i-c>, <i-c>Heliod, Sun-Crowned</i-c>, <i-c>Enlightened Tutor</i-c>, <i-c>Silence</i-c>. Keep or mulligan?",
    options: ["Keep, Petal and Mox are enough", "Keep if you're on the play", "Keep, it has two combo pieces", "Mulligan, it has no land"],
    answer: 3,
    explain: "One of your two mana sources should be a land. Petal is one-shot and the hand runs out of mana after turn 1." },
  { id: "plan-mull-keep", topic: "plan",
    q: "Your opener: <i-c>Savannah</i-c>, <i-c>Plains</i-c>, <i-c>Llanowar Elves</i-c>, <i-c>Sol Ring</i-c>, <i-c>Worldly Tutor</i-c>, <i-c>Archangel of Thune</i-c>, <i-c>Swords to Plowshares</i-c>. Keep or mulligan?",
    options: ["Mulligan, no Spike Feeder", "Mulligan, too few lands", "Keep", "Mulligan, no silence card"],
    answer: 2,
    explain: "Two lands, a dork, a rock, Shalai on turn 2, a combo piece and a tutor to find Feeder." },
  { id: "plan-keep-rule", topic: "plan",
    q: "What's the deck's basic keep rule?",
    options: ["Any hand with a combo piece", "Two mana sources (one a land), plus Shalai by turn 3, a tutor, or a combo piece", "Three lands minimum", "Any hand with Gaea's Cradle"],
    answer: 1,
    explain: "Mana plus something to do with it." },
  { id: "plan-t1", topic: "plan",
    q: "What's the usual turn 1 priority order?",
    options: ["Sylvan Library, then a dork", "Dork, then Sol Ring or a Mox, then Sylvan Library or Esper Sentinel", "Silence, then a dork", "Hold everything for turn 2"],
    answer: 1,
    explain: "Mana first, so turn 2 is big. Then card advantage." },
  { id: "plan-druid-early", topic: "plan",
    q: "You have <i-c>Devoted Druid</i-c> and <i-c>Vizier of Remedies</i-c> in hand, no Greaves. How do you play them?",
    options: ["Only with Natural Order", "Vizier first, Druid two turns later", "Druid a turn early as a mana dork, Vizier on the combo turn", "Both on the same turn"],
    answer: 2,
    explain: "The Druid needs to lose summoning sickness. It's also a fine dork in the meantime." },
  { id: "plan-hoof-or-vorinclex", topic: "plan",
    q: "You cast <i-c>Natural Order</i-c> with four creatures. Everyone's at 40. Which target is usually better?",
    options: ["<i-c>Elvish Mystic</i-c>", "<i-c>Vorinclex, Voice of Hunger</i-c>", "<i-c>Craterhoof Behemoth</i-c>", "<i-c>Destiny Spinner</i-c>"],
    answer: 1,
    explain: "Hoof with about four creatures does roughly 16 plus base power: it kills nobody. Vorinclex doubles your mana and locks their lands." },
  { id: "plan-hoof-one", topic: "plan",
    q: "Roughly how many attackers does Craterhoof need to kill one opponent at 40?",
    options: ["10 to 11", "3 to 4", "6 to 7", "15"],
    answer: 2,
    explain: "N attackers deal about N times N plus base power. Six or seven kill one player. The whole table takes ten or eleven." },
  { id: "plan-hoof-table", topic: "plan",
    q: "Roughly how many attackers does Craterhoof need to kill three opponents at 40 each?",
    options: ["5", "20", "7", "10 to 11"],
    answer: 3,
    explain: "120 total damage. Ten attackers is about 100 plus base power, eleven about 121 plus." },
  { id: "plan-ranger-timing", topic: "plan",
    q: "When should you sacrifice <i-c>Ranger-Captain of Eos</i-c> on your combo turn?",
    options: ["At the end of your turn", "After your combo resolves", "Before you cast your first tutor or combo piece", "In response to a counterspell"],
    answer: 2,
    explain: "Once the ability resolves, opponents can't cast noncreature spells this turn. In response, it's too late: the counterspell is already cast." },
  { id: "plan-blue-table", topic: "plan",
    q: "A blue player holds up counterspells. Which cards help your creature combo resolve? (choose all that apply)",
    options: ["<i-c>Cavern of Souls</i-c>", "<i-c>Deafening Silence</i-c>", "<i-c>Destiny Spinner</i-c>", "<i-c>Veil of Summer</i-c>"],
    answer: [0,2,3],
    explain: "Spinner and Cavern make creatures uncounterable. Veil makes all your spells uncounterable this turn. Deafening Silence still lets them cast one counterspell." },
  { id: "plan-deafening-turn", topic: "plan",
    q: "You want to cast <i-c>Chrome Mox</i-c>, <i-c>Sol Ring</i-c> and <i-c>Deafening Silence</i-c> this turn. In what order?",
    options: ["Deafening Silence first", "Sol Ring, Deafening Silence, Chrome Mox", "You can cast all three in any order", "The two rocks first, Deafening Silence last"],
    answer: 3,
    explain: "Once Deafening Silence is out, you can only cast one noncreature spell per turn too. Play it last, or hold it." },
  { id: "plan-cradle-crop", topic: "plan",
    q: "You control four creatures, one of them an untapped <i-c>Llanowar Elves</i-c>, and a Plains. You need a burst of green mana right now. Which instant helps most?",
    options: ["<i-c>Worldly Tutor</i-c>", "<i-c>Reprieve</i-c>", "<i-c>Crop Rotation</i-c> for <i-c>Gaea's Cradle</i-c>", "<i-c>Nature's Lore</i-c>"],
    answer: 2,
    explain: "Tap the Elves to pay {G}, sacrifice the Plains, and Cradle enters untapped. It makes {G}{G}{G}{G}: tapped creatures still count." },
  { id: "plan-reprieve", topic: "plan",
    q: "An opponent casts the spell that wins them the game. You have {1}{W} open. Which card stops it?",
    options: ["<i-c>Silence</i-c>", "<i-c>Orim's Chant</i-c>", "<i-c>Reprieve</i-c>", "<i-c>Flawless Maneuver</i-c>"],
    answer: 2,
    explain: "Reprieve returns the spell to its owner's hand and draws you a card. Silence and Orim's Chant stop future spells, not one already on the stack." },

  /* ---------- mana ---------- */
  { id: "mana-wooded", topic: "mana",
    q: "Which lands can <i-c>Wooded Foothills</i-c> find in this deck?",
    options: ["Any land", "Only basic Forest", "Forest-typed lands: Savannah, Temple Garden, Canopy Vista, Dryad Arbor, Forest", "Plains-typed lands"],
    answer: 2,
    explain: "It finds a Mountain or Forest card. You have no Mountains, so only Forest-typed lands.",
    cards: ["Wooded Foothills"] },
  { id: "mana-flooded", topic: "mana",
    q: "Can <i-c>Flooded Strand</i-c> find <i-c>Dryad Arbor</i-c>?",
    options: ["Only on turn 1", "No, Dryad Arbor is a Forest, and Strand finds Plains or Island", "Yes, it's a land creature", "Yes"],
    answer: 1,
    explain: "Flooded Strand and Marsh Flats find Plains: Savannah, Temple Garden, Canopy Vista or a basic Plains." },
  { id: "mana-heath", topic: "mana",
    q: "Which fetch can find both a basic <i-c>Forest</i-c> and a basic <i-c>Plains</i-c>?",
    options: ["<i-c>Wooded Foothills</i-c>", "<i-c>Misty Rainforest</i-c>", "<i-c>Marsh Flats</i-c>", "<i-c>Windswept Heath</i-c>"],
    answer: 3,
    explain: "Heath says Forest or Plains. It's the most flexible fetch here." },
  { id: "mana-marsh", topic: "mana",
    q: "Which of these can <i-c>Marsh Flats</i-c> find? (choose all that apply)",
    options: ["<i-c>Temple Garden</i-c>", "<i-c>Savannah</i-c>", "<i-c>Canopy Vista</i-c>", "<i-c>Sunpetal Grove</i-c>", "<i-c>Dryad Arbor</i-c>"],
    answer: [0,1,2],
    explain: "The three duals are Forest Plains. Dryad Arbor is only a Forest. Sunpetal Grove has no land type." },
  { id: "mana-best-fetch", topic: "mana",
    q: "You crack a fetch on turn 1 and want both colors at no extra cost. What do you get?",
    options: ["<i-c>Savannah</i-c>", "<i-c>Temple Garden</i-c>", "<i-c>Dryad Arbor</i-c>", "<i-c>Canopy Vista</i-c>"],
    answer: 0,
    explain: "Savannah is untapped and costs no life. Garden costs 2 life to enter untapped, and Vista enters tapped without two basics." },
  { id: "mana-saga-chapter3", topic: "mana",
    q: "Which artifacts can <i-c>Urza's Saga</i-c> find? (choose all that apply)",
    options: ["<i-c>Grim Monolith</i-c>", "<i-c>Walking Ballista</i-c>", "<i-c>Sol Ring</i-c>", "<i-c>Skullclamp</i-c>", "<i-c>Chrome Mox</i-c>"],
    answer: [2,3,4],
    explain: "Mana cost {0} or {1} only. Grim costs {2} and Ballista {X}{X}." },
  { id: "mana-gemstone-when", topic: "mana",
    q: "When does <i-c>Gemstone Caverns</i-c> start on the battlefield?",
    options: ["When you're the starting player", "When it's in your opening hand and you're not the starting player", "Whenever it's in your opening hand", "When you mulligan"],
    answer: 1,
    explain: "Then it has a luck counter and taps for any color. You exile a card from your hand to do it." },
  { id: "mana-halfling", topic: "mana",
    q: "Which spell can NOT use <i-c>Delighted Halfling</i-c>'s colored mana?",
    options: ["<i-c>Kutzil, Malamet Exemplar</i-c>", "<i-c>Archangel of Thune</i-c>", "<i-c>Linvala, Keeper of Silence</i-c>", "<i-c>Vorinclex, Voice of Hunger</i-c>"],
    answer: 1,
    explain: "Archangel isn't legendary. The Halfling's {C} still works for any spell." },
  { id: "mana-pilgrim", topic: "mana",
    q: "What color does <i-c>Avacyn's Pilgrim</i-c> make?",
    options: ["{G}", "Any color", "{C}", "{W}"],
    answer: 3,
    explain: "A green creature that makes {W}. Great for casting white cards off Forests." },
  { id: "mana-vault", topic: "mana",
    q: "What does <i-c>Mana Vault</i-c> do?",
    options: ["{0}: sacrifice for one mana of any color", "{1}: taps for {C}{C} every turn", "{2}: taps for {C}{C}{C}, {4} to untap", "{1}: taps for {C}{C}{C}, doesn't untap normally, deals 1 damage in your draw step while tapped"],
    answer: 3,
    explain: "Pay {4} in your upkeep to untap it. The {2} card with {4} to untap is <i-c>Grim Monolith</i-c>.",
    cards: ["Mana Vault"] },
  { id: "mana-chrome", topic: "mana",
    q: "What can you imprint on <i-c>Chrome Mox</i-c>?",
    options: ["A land card", "Any card", "An artifact card", "A nonartifact, nonland card from your hand"],
    answer: 3,
    explain: "It taps for one mana of the exiled card's colors. A green-white card like <i-c>Kutzil, Malamet Exemplar</i-c> gives a choice." },
  { id: "mana-diamond", topic: "mana",
    q: "What does <i-c>Mox Diamond</i-c> ask for?",
    options: ["Sacrifice a land", "Pay 2 life", "Exile a card from hand", "Discard a land card as it enters"],
    answer: 3,
    explain: "Discard a land or it goes to the graveyard. It taps for any color." },
  { id: "mana-cradle", topic: "mana",
    q: "How much mana does <i-c>Gaea's Cradle</i-c> make?",
    options: ["{G} for each creature you control", "One mana of any color", "{G} for each land you control", "{G}{G}"],
    answer: 0,
    explain: "With no creatures it makes nothing. With a full board it's huge.",
    cards: ["Gaea's Cradle"] },
  { id: "mana-esg", topic: "mana",
    q: "Why is <i-c>Elvish Spirit Guide</i-c> special?",
    options: ["It taps for {G}{G}", "Exile it from your hand for {G}, at instant speed", "It can't be countered", "It makes your spells uncounterable"],
    answer: 1,
    explain: "A free {G} with no land or creature needed. It also counts as a green card." },
  { id: "mana-cavern-type", topic: "mana",
    q: "You name Human with <i-c>Cavern of Souls</i-c>. Which spell can't use the colored mana?",
    options: ["<i-c>Recruiter of the Guard</i-c>", "<i-c>Grand Abolisher</i-c>", "<i-c>Archangel of Thune</i-c>", "<i-c>Vizier of Remedies</i-c>"],
    answer: 2,
    explain: "Archangel is an Angel. Vizier, Abolisher and Recruiter are all Humans." },
  { id: "mana-canopy-vista", topic: "mana",
    q: "When does <i-c>Canopy Vista</i-c> enter untapped?",
    options: ["When you control two or more basic lands", "When you control a Forest or Plains", "When you have two or more opponents", "When you pay 2 life"],
    answer: 0,
    explain: "Two basics. Sunpetal Grove needs a Forest or Plains; Temple Garden 2 life; Bountiful Promenade two opponents." },
  { id: "mana-green-for-no", topic: "mana",
    q: "Which of these are green creatures that Natural Order, GSZ or Summoner's Pact can find? (choose all that apply)",
    options: ["<i-c>Kutzil, Malamet Exemplar</i-c>", "<i-c>Avacyn's Pilgrim</i-c>", "<i-c>Grand Abolisher</i-c>", "<i-c>Brightglass Gearhulk</i-c>", "<i-c>Walking Ballista</i-c>"],
    answer: [0,1,3],
    explain: "Kutzil and Gearhulk are green and white, Pilgrim is green. Ballista is colorless and Abolisher white." },
  { id: "mana-nature-lore", topic: "mana",
    q: "What can <i-c>Nature's Lore</i-c> put onto the battlefield?",
    options: ["Any Forest card, untapped", "A basic land, tapped", "A Plains card, untapped", "Any land, tapped"],
    answer: 0,
    explain: "A Forest card: Savannah, Temple Garden, Canopy Vista, Dryad Arbor or a basic Forest. It enters untapped." },
  { id: "mana-boseiju", topic: "mana",
    q: "What makes <i-c>Boseiju, Who Endures</i-c>'s channel ability cheaper?",
    options: ["Each legendary creature you control", "Each Forest you control", "Each opponent", "Each creature you control"],
    answer: 0,
    explain: "{1} less per legendary creature: Shalai, Kutzil, Thalia, Linvala, Vorinclex. Same for <i-c>Eiganjo, Seat of the Empire</i-c>." }
];
