/* Prices for Corrupted Etrata (Etrata's Shadow Market v3): the cheapest legal regular printing of each card,
   in US dollars (TCGplayer via Archidekt, or MTGGoldfish). Generated from the research table (prices.csv).
   base: the card is also in the Etrata deck (../etrata/), so you may own it already. */
window.CETRATA_PRICES = {"date":"2026-10-05","currency":"USD","cards":[{"name":"Etrata, Deadly Fugitive","qty":1,"usd":0.49,"printing":"Ravnica: Murders at Karlov Manor #200","url":"https://www.mtggoldfish.com/price/ravnica-murders-at-karlov-manor/200/etrata-deadly-fugitive","gc":false,"base":true},
{"name":"Ramses, Assassin Lord","qty":1,"usd":2.45,"printing":"Dominaria United Commander #39 (as labeled by MTGGoldfish)","url":"https://www.mtggoldfish.com/price/dominaria-united-commander/39/ramses-assassin-lord","gc":false,"base":true},
{"name":"Duskmantle Guildmage","qty":1,"usd":0.74,"printing":"Gatecrash #158","url":"https://www.mtggoldfish.com/price/gatecrash/158/duskmantle-guildmage","gc":false,"base":true},
{"name":"Mindcrank","qty":1,"usd":11,"printing":"New Phyrexia #144 (Iconic Masters #220 also $11)","url":"https://www.mtggoldfish.com/price/New+Phyrexia/Mindcrank","gc":false,"base":true},
{"name":"Culling the Weak","qty":1,"usd":7.02,"printing":"Mystery Booster 2 (mb2) #40","url":"https://archidekt.com/api/cards/v2/?name=Culling+the+Weak","gc":false},
{"name":"Scroll of Fate","qty":1,"usd":0.28,"printing":"Murders at Karlov Manor Commander #235","url":"https://archidekt.com/api/cards/v2/?name=Scroll%20of%20Fate","gc":false,"base":true},
{"name":"Wormfang Manta","qty":1,"usd":0.5,"printing":"Judgment #58 (only printing)","url":"https://archidekt.com/api/cards/v2/?name=Wormfang%20Manta","gc":false},
{"name":"Crystal Shard","qty":1,"usd":1.62,"printing":"The List MRD-159 (Time Spiral Remastered #393 $1.78, Mirrodin #159 $1.94)","url":"https://archidekt.com/api/cards/v2/?name=Crystal%20Shard","gc":false},
{"name":"Training Grounds","qty":1,"usd":7.81,"printing":"Avatar: The Last Airbender Eternal #20 (MTGGoldfish: MOM Aftermath #9 $9.83)","url":"https://archidekt.com/api/cards/v2/?name=Training%20Grounds","gc":false,"base":true},
{"name":"Bloodthirsty Conqueror","qty":1,"usd":34.31,"printing":"Foundations Promos (PFDN 58p); FDN #58 $34.80; MTGGoldfish FDN #58 $36.26","url":"https://archidekt.com/api/cards/v2/?name=Bloodthirsty+Conqueror","gc":false},
{"name":"Necropotence","qty":1,"usd":37,"printing":"Eternal Masters #98","url":"https://www.mtggoldfish.com/price/masters-edition-ii/107/necropotence","gc":true},
{"name":"Bloodletter of Aclazotz","qty":1,"usd":34.41,"printing":"LCI Promos (plci) #92p; regular LCI #92 = 36.12","url":"https://archidekt.com/api/cards/v2/?name=Bloodletter+of+Aclazotz","gc":false},
{"name":"Roshan, Hidden Magister","qty":1,"usd":0.29,"printing":"Assassin's Creed #32 (from verify.csv)","url":"https://www.mtggoldfish.com/price/assassins-creed/32/roshan-hidden-magister","gc":false,"base":true},
{"name":"Leyline of Transformation","qty":1,"usd":0.75,"printing":"Duskmourn: House of Horror #63 (from verify.csv)","url":"https://www.mtggoldfish.com/price/duskmourn-house-of-horror/63/leyline-of-transformation","gc":false,"base":true},
{"name":"Vito, Thorn of the Dusk Rose","qty":1,"usd":10.26,"printing":"Foundations Jumpstart (J25)","url":"https://archidekt.com/api/cards/v2/?name=Vito%2C+Thorn+of+the+Dusk+Rose","gc":false},
{"name":"Imperial Seal","qty":1,"usd":180,"printing":"Double Masters 2022 #79","url":"https://www.mtggoldfish.com/price/Portal+Three+Kingdoms/Imperial+Seal","gc":true},
{"name":"Changeling Outcast","qty":1,"usd":1.5,"printing":"Modern Horizons #82","url":"https://www.mtggoldfish.com/price/Modern+Horizons/Changeling+Outcast","gc":false,"base":true},
{"name":"Marauding Blight-Priest","qty":1,"usd":0.19,"printing":"Jumpstart 2022 (J22)","url":"https://archidekt.com/api/cards/v2/?name=Marauding+Blight-Priest","gc":false},
{"name":"Dimir House Guard","qty":1,"usd":0.14,"printing":"The List RAV-83 (Ravnica Remastered #73 $0.16)","url":"https://archidekt.com/api/cards/v2/?name=Dimir%20House%20Guard","gc":false},
{"name":"Shred Memory","qty":1,"usd":0.85,"printing":"Ravnica: City of Guilds #105 (only printing)","url":"https://archidekt.com/api/cards/v2/?name=Shred%20Memory","gc":false},
{"name":"Beseech the Mirror","qty":1,"usd":21.21,"printing":"Wilds of Eldraine #82","url":"https://archidekt.com/api/cards/v2/?name=Beseech%20the%20Mirror","gc":false},
{"name":"Wishclaw Talisman","qty":1,"usd":1.92,"printing":"Mystery Booster 2 (MB2)","url":"https://archidekt.com/api/cards/v2/?name=Wishclaw+Talisman","gc":false},
{"name":"Gonti, Night Minister","qty":1,"usd":0.79,"printing":"Aetherdrift #87 (MTGGoldfish search $0.99)","url":"https://archidekt.com/api/cards/v2/?name=Gonti,%20Night%20Minister","gc":false},
{"name":"Exquisite Blood","qty":1,"usd":37.67,"printing":"The Lost Caverns of Ixalan Commander; MTGGoldfish AVR #102 $38.09","url":"https://archidekt.com/api/cards/v2/?name=Exquisite+Blood","gc":false},
{"name":"Thief of Sanity","qty":1,"usd":0.6,"printing":"Ravnica: Clue Edition #212 (Guilds of Ravnica #205 $0.75)","url":"https://www.mtggoldfish.com/price/Guilds+of+Ravnica/Thief+of+Sanity","gc":false},
{"name":"Black Market Connections","qty":1,"usd":9.02,"printing":"Marvel Super Heroes Commander #155","url":"https://archidekt.com/api/cards/v2/?name=Black%20Market%20Connections","gc":false},
{"name":"Fallen Shinobi","qty":1,"usd":6.15,"printing":"Streets of New Capenna Commander #338","url":"https://www.mtggoldfish.com/price/modern-horizons/199/fallen-shinobi","gc":false},
{"name":"Tetsuko Umezawa, Fugitive","qty":1,"usd":0.15,"printing":"Commander Masters (cmm) #126","url":"https://archidekt.com/api/cards/v2/?name=Tetsuko+Umezawa%2C+Fugitive","gc":false},
{"name":"Tribute Mage","qty":1,"usd":0.91,"printing":"Modern Horizons (MH1)","url":"https://archidekt.com/api/cards/v2/?name=Tribute+Mage","gc":false},
{"name":"Opposition Agent","qty":1,"usd":22,"printing":"Commander Legends #141","url":"https://www.mtggoldfish.com/price/Commander+Legends/Opposition+Agent","gc":true},
{"name":"Notion Thief","qty":1,"usd":1.85,"printing":"Zendikar Rising Commander #96","url":"https://www.mtggoldfish.com/price/dragons-maze/88/notion-thief","gc":true},
{"name":"Mystic Remora","qty":1,"usd":9.46,"printing":"Ice Age","url":"https://www.mtggoldfish.com/price/Ice+Age/Mystic+Remora","gc":false},
{"name":"Windfall","qty":1,"usd":5.26,"printing":"Commander (2011) #70","url":"https://www.mtggoldfish.com/price/urzas-saga/111/windfall","gc":false},
{"name":"Praetor's Grasp","qty":1,"usd":11,"printing":"New Phyrexia #71","url":"https://www.mtggoldfish.com/price/new-phyrexia/71/praetors-grasp","gc":false},
{"name":"Virtus the Veiled","qty":1,"usd":8.31,"printing":"Battlebond (bbd) #7","url":"https://archidekt.com/api/cards/v2/?name=Virtus+the+Veiled","gc":false},
{"name":"Dark Ritual","qty":1,"usd":4.46,"printing":"Urza's Saga (usg) #127","url":"https://archidekt.com/api/cards/v2/?name=Dark+Ritual","gc":false,"base":true},
{"name":"Muddle the Mixture","qty":1,"usd":2.1,"printing":"Ravnica: City of Guilds #60 (The List #60 also $2.10)","url":"https://www.mtggoldfish.com/price/ravnica-city-of-guilds/60/muddle-the-mixture","gc":false},
{"name":"Grim Tutor","qty":1,"usd":26,"printing":"Core Set 2021 #103","url":"https://www.mtggoldfish.com/price/Core+Set+2021/Grim+Tutor","gc":false},
{"name":"Drift of Phantasms","qty":1,"usd":0.24,"printing":"Ravnica Remastered #42","url":"https://archidekt.com/api/cards/v2/?name=Drift%20of%20Phantasms","gc":false},
{"name":"Rhystic Study","qty":1,"usd":64,"printing":"Prophecy #45","url":"https://www.mtggoldfish.com/price/Prophecy/Rhystic+Study","gc":true},
{"name":"Demonic Tutor","qty":1,"usd":63,"printing":"Mystery Booster #620 (Ultimate Masters #93 $66)","url":"https://www.mtggoldfish.com/price/masters-edition-iv/77/demonic-tutor","gc":true},
{"name":"Vampiric Tutor","qty":1,"usd":57,"printing":"Dominaria Remastered #108 (Commander Legends #156 also $57)","url":"https://www.mtggoldfish.com/price/Visions/Vampiric+Tutor","gc":true},
{"name":"Diabolic Intent","qty":1,"usd":18,"printing":"The Brothers' War #89","url":"https://www.mtggoldfish.com/price/planeshift/42/diabolic-intent","gc":false},
{"name":"Lim-Dûl's Vault","qty":1,"usd":4.49,"printing":"Alliances","url":"https://www.mtggoldfish.com/price/commander-2013-edition/197/lim-duls-vault","gc":false},
{"name":"Brainstorm","qty":1,"usd":0.79,"printing":"Reality Fracture Commander #39","url":"https://www.mtggoldfish.com/price/Ice+Age/Brainstorm","gc":false},
{"name":"Sanguine Bond","qty":1,"usd":5.19,"printing":"Commander 2013 (C13)","url":"https://archidekt.com/api/cards/v2/?name=Sanguine+Bond","gc":false},
{"name":"Ponder","qty":1,"usd":2.38,"printing":"Magic 2012 #73","url":"https://www.mtggoldfish.com/price/Lorwyn/Ponder","gc":false},
{"name":"Counterspell","qty":1,"usd":2.37,"printing":"Classic Sixth Edition #61","url":"https://www.mtggoldfish.com/price/mercadian-masques/69/counterspell","gc":false,"base":true},
{"name":"Swan Song","qty":1,"usd":11,"printing":"Edge of Eternities Commander #46","url":"https://www.mtggoldfish.com/price/Theros/Swan+Song","gc":false},
{"name":"An Offer You Can't Refuse","qty":1,"usd":3.27,"printing":"Final Fantasy Commander #267","url":"https://www.mtggoldfish.com/price/Streets+of+New+Capenna/An+Offer+You+Cant+Refuse","gc":false,"base":true},
{"name":"Fierce Guardianship","qty":1,"usd":66,"printing":"Commander 2020 #35","url":"https://www.mtggoldfish.com/price/commander-2020/35/fierce-guardianship","gc":true},
{"name":"Deadly Rollick","qty":1,"usd":28,"printing":"Commander Masters #147","url":"https://www.mtggoldfish.com/price/commander-2020/42/deadly-rollick","gc":false},
{"name":"Infernal Grasp","qty":1,"usd":0.33,"printing":"Edge of Eternities Commander #84","url":"https://www.mtggoldfish.com/price/Innistrad+Midnight+Hunt/Infernal+Grasp","gc":false,"base":true},
{"name":"Cyclonic Rift","qty":1,"usd":36,"printing":"Commander Masters","url":"https://www.mtggoldfish.com/price/Return+to+Ravnica/Cyclonic+Rift","gc":true},
{"name":"Toxic Deluge","qty":1,"usd":5.26,"printing":"Secrets of Strixhaven Commander #120","url":"https://www.mtggoldfish.com/price/Commander+2013+Edition/Toxic+Deluge","gc":false,"base":true},
{"name":"Mox Amber","qty":1,"usd":87.12,"printing":"Brothers' War Retro Artifacts (brr) #35; Dominaria #224 = 87.71","url":"https://archidekt.com/api/cards/v2/?name=Mox+Amber","gc":false},
{"name":"Sol Ring","qty":1,"usd":1.09,"printing":"Reality Fracture Commander #21","url":"https://www.mtggoldfish.com/price/Commander+Masters/Sol+Ring","gc":false,"base":true},
{"name":"Arcane Signet","qty":1,"usd":0.44,"printing":"Reality Fracture Commander #20","url":"https://www.mtggoldfish.com/price/Commander+Masters/Arcane+Signet","gc":false,"base":true},
{"name":"Talisman of Dominance","qty":1,"usd":0.5,"printing":"Reality Fracture Commander #62","url":"https://www.mtggoldfish.com/price/Mirrodin/Talisman+of+Dominance","gc":false,"base":true},
{"name":"Dimir Signet","qty":1,"usd":0.33,"printing":"Reality Fracture Commander #56","url":"https://archidekt.com/api/cards/v2/?name=Dimir%20Signet","gc":false,"base":true},
{"name":"Fellwar Stone","qty":1,"usd":0.57,"printing":"Reality Fracture Commander #57","url":"https://www.mtggoldfish.com/price/The+Dark/Fellwar+Stone","gc":false,"base":true},
{"name":"Mind Stone","qty":1,"usd":0.35,"printing":"Secrets of Strixhaven Commander #352","url":"https://www.mtggoldfish.com/price/Weatherlight/Mind+Stone","gc":false,"base":true},
{"name":"Command Tower","qty":1,"usd":0.31,"printing":"Aetherdrift Commander #59","url":"https://www.mtggoldfish.com/price/Commander+Legends/Command+Tower","gc":false,"base":true},
{"name":"Watery Grave","qty":1,"usd":10,"printing":"Guilds of Ravnica #259 (Edge of Eternities #261 also $10)","url":"https://www.mtggoldfish.com/price/Ravnica+City+of+Guilds/Watery+Grave","gc":false},
{"name":"Drowned Catacomb","qty":1,"usd":0.58,"printing":"Reality Fracture Commander #69","url":"https://www.mtggoldfish.com/price/magic-2012/226/drowned-catacomb","gc":false,"base":true},
{"name":"Darkslick Shores","qty":1,"usd":2.25,"printing":"Phyrexia: All Will Be One #250","url":"https://www.mtggoldfish.com/price/Scars+of+Mirrodin/Darkslick+Shores","gc":false,"base":true},
{"name":"Underground River","qty":1,"usd":0.78,"printing":"Reality Fracture Commander #87","url":"https://www.mtggoldfish.com/price/Ice+Age/Underground+River","gc":false,"base":true},
{"name":"Sunken Hollow","qty":1,"usd":0.38,"printing":"Final Fantasy Commander #429","url":"https://www.mtggoldfish.com/price/Battle+for+Zendikar/Sunken+Hollow","gc":false,"base":true},
{"name":"Morphic Pool","qty":1,"usd":29,"printing":"Commander Legends: Battle for Baldur's Gate #357","url":"https://www.mtggoldfish.com/price/battlebond/83/morphic-pool","gc":false},
{"name":"Gloomlake Verge","qty":1,"usd":11,"printing":"Duskmourn: House of Horror #260","url":"https://www.mtggoldfish.com/price/duskmourn-house-of-horror/260/gloomlake-verge","gc":false},
{"name":"Undercity Sewers","qty":1,"usd":17,"printing":"Ravnica: Murders at Karlov Manor #270","url":"https://www.mtggoldfish.com/price/Ravnica+Murders+at+Karlov+Manor/Undercity+Sewers","gc":false},
{"name":"Polluted Delta","qty":1,"usd":21,"printing":"Modern Horizons 3 #224","url":"https://www.mtggoldfish.com/price/Onslaught/Polluted+Delta","gc":false},
{"name":"Otawara, Soaring City","qty":1,"usd":28,"printing":"Kamigawa: Neon Dynasty #271","url":"https://www.mtggoldfish.com/price/Kamigawa+Neon+Dynasty/Otawara+Soaring+City","gc":false},
{"name":"Takenuma, Abandoned Mire","qty":1,"usd":11,"printing":"Kamigawa: Neon Dynasty #278","url":"https://www.mtggoldfish.com/price/Kamigawa+Neon+Dynasty/Takenuma+Abandoned+Mire","gc":false},
{"name":"Rogue's Passage","qty":1,"usd":0.44,"printing":"Magic Origins #250","url":"https://www.mtggoldfish.com/price/return-to-ravnica/245/rogues-passage","gc":false,"base":true},
{"name":"Path of Ancestry","qty":1,"usd":0.24,"printing":"Reality Fracture Commander #77 (Starter Commander Decks / Aetherdrift Commander also $0.24)","url":"https://archidekt.com/api/cards/v2/?name=Path%20of%20Ancestry","gc":false,"base":true},
{"name":"Secluded Courtyard","qty":1,"usd":0.32,"printing":"Marvel Super Heroes Commander #265","url":"https://archidekt.com/api/cards/v2/?name=Secluded%20Courtyard","gc":false},
{"name":"Scheming Symmetry","qty":1,"usd":8.47,"printing":"Secret Lair Drop (Pancoast & Okumura art); cheapest M20 $8.63","url":"https://archidekt.com/api/cards/v2/?name=Scheming+Symmetry","gc":false},
{"name":"Night's Whisper","qty":1,"usd":0.35,"printing":"Marvel Super Heroes Commander #158","url":"https://www.mtggoldfish.com/price/fifth-dawn/55/nights-whisper","gc":false,"base":true},
{"name":"Enduring Tenacity","qty":1,"usd":15.99,"printing":"Duskmourn: House of Horror (Card Kingdom NM)","url":"https://www.cardkingdom.com/catalog/search?search=header&filter%5Bname%5D=Enduring+Tenacity","gc":false},
{"name":"Starscape Cleric","qty":1,"usd":2.29,"printing":"Bloomburrow (Card Kingdom NM)","url":"https://www.cardkingdom.com/catalog/search?search=header&filter%5Bname%5D=Starscape+Cleric","gc":false},
{"name":"Vampire of the Dire Moon","qty":1,"usd":1.26,"printing":"Core Set 2020 #120","url":"https://www.mtggoldfish.com/price/core-set-2020/120/vampire-of-the-dire-moon","gc":false},
{"name":"Hooded Blightfang","qty":1,"usd":1.3,"printing":"Core Set 2021 #104","url":"https://www.mtggoldfish.com/price/core-set-2021/104/hooded-blightfang","gc":false},
{"name":"Silumgar Assassin","qty":1,"usd":0.36,"printing":"Dragons of Tarkir","url":"https://www.mtggoldfish.com/price/Dragons+of+Tarkir/Silumgar+Assassin","gc":false},
{"name":"Island","qty":8,"usd":null,"printing":"basic","url":"","gc":false,"base":true},
{"name":"Swamp","qty":8,"usd":null,"printing":"basic","url":"","gc":false,"base":true}]};
