/* Prices for Corrupted Etrata (the Etrata heist closer): Scryfall's prices.usd (the TCGplayer market price) for each
   card's cheapest nonfoil paper printing, from Scryfall's bulk data of 2026-10-05. Generated from
   research/etrata-theft-aggro/local/prices-heist-closer.csv. url: the TCGplayer product page; scryfall: the printing.
   base: the card is also in the Etrata deck (../etrata/), so you may own it already. */
window.CETRATA_PRICES = {"date":"2026-10-05","currency":"USD","cards":[
{"name":"Imperial Seal","qty":1,"usd":170.58,"printing":"2X2 #79","url":"https://www.tcgplayer.com/product/276288","scryfall":"https://scryfall.com/card/2x2/79/imperial-seal","gc":true},
{"name":"Mox Amber","qty":1,"usd":87.79,"printing":"DOM #224","url":"https://www.tcgplayer.com/product/162125","scryfall":"https://scryfall.com/card/dom/224/mox-amber","gc":false},
{"name":"Demonic Tutor","qty":1,"usd":63.1,"printing":"PLST #DDC-49","url":"https://www.tcgplayer.com/product/203644","scryfall":"https://scryfall.com/card/plst/DDC-49/demonic-tutor","gc":true},
{"name":"Rhystic Study","qty":1,"usd":61.95,"printing":"PCY #45","url":"https://www.tcgplayer.com/product/7357","scryfall":"https://scryfall.com/card/pcy/45/rhystic-study","gc":true},
{"name":"Fierce Guardianship","qty":1,"usd":59.66,"printing":"C20 #35","url":"https://www.tcgplayer.com/product/212218","scryfall":"https://scryfall.com/card/c20/35/fierce-guardianship","gc":true},
{"name":"Ancient Tomb","qty":1,"usd":56.94,"printing":"WC99 #kb315","url":"https://www.tcgplayer.com/product/164409","scryfall":"https://scryfall.com/card/wc99/kb315/ancient-tomb","gc":true},
{"name":"Vampiric Tutor","qty":1,"usd":51,"printing":"WC99 #js161","url":"https://www.tcgplayer.com/product/164949","scryfall":"https://scryfall.com/card/wc99/js161/vampiric-tutor","gc":true},
{"name":"Roaming Throne","qty":1,"usd":49.25,"printing":"LCI #344","url":"https://www.tcgplayer.com/product/525241","scryfall":"https://scryfall.com/card/lci/344/roaming-throne","gc":false},
{"name":"Cavern of Souls","qty":1,"usd":48.08,"printing":"AVR #226","url":"https://www.tcgplayer.com/product/58842","scryfall":"https://scryfall.com/card/avr/226/cavern-of-souls","gc":false},
{"name":"Chrome Mox","qty":1,"usd":47.56,"printing":"WC04 #mb152","url":"https://www.tcgplayer.com/product/174378","scryfall":"https://scryfall.com/card/wc04/mb152/chrome-mox","gc":true},
{"name":"Force of Negation","qty":1,"usd":45.86,"printing":"TLE #13","url":"https://www.tcgplayer.com/product/660518","scryfall":"https://scryfall.com/card/tle/13/force-of-negation","gc":false},
{"name":"Exquisite Blood","qty":1,"usd":38.86,"printing":"AVR #102","url":"https://www.tcgplayer.com/product/58373","scryfall":"https://scryfall.com/card/avr/102/exquisite-blood","gc":false},
{"name":"Scalding Tarn","qty":1,"usd":38.37,"printing":"MH2 #254","url":"https://www.tcgplayer.com/product/238610","scryfall":"https://scryfall.com/card/mh2/254/scalding-tarn","gc":false},
{"name":"Lotus Petal","qty":1,"usd":34.73,"printing":"MB2 #226","url":"https://www.tcgplayer.com/product/563253","scryfall":"https://scryfall.com/card/mb2/226/lotus-petal","gc":false},
{"name":"Bloodletter of Aclazotz","qty":1,"usd":34.32,"printing":"PLCI #92p","url":"https://www.tcgplayer.com/product/526862","scryfall":"https://scryfall.com/card/plci/92p/bloodletter-of-aclazotz","gc":false},
{"name":"Bloodthirsty Conqueror","qty":1,"usd":34.19,"printing":"PFDN #58p","url":"https://www.tcgplayer.com/product/648590","scryfall":"https://scryfall.com/card/pfdn/58p/bloodthirsty-conqueror","gc":false},
{"name":"Marsh Flats","qty":1,"usd":32.13,"printing":"MM3 #239","url":"https://www.tcgplayer.com/product/128221","scryfall":"https://scryfall.com/card/mm3/239/marsh-flats","gc":false},
{"name":"Cyclonic Rift","qty":1,"usd":30.04,"printing":"2XM #47","url":"https://www.tcgplayer.com/product/218370","scryfall":"https://scryfall.com/card/2xm/47/cyclonic-rift","gc":true},
{"name":"Morphic Pool","qty":1,"usd":26.99,"printing":"CLB #357","url":"https://www.tcgplayer.com/product/267057","scryfall":"https://scryfall.com/card/clb/357/morphic-pool","gc":false},
{"name":"Deadly Rollick","qty":1,"usd":26.69,"printing":"SLD #1754","url":"https://www.tcgplayer.com/product/625928","scryfall":"https://scryfall.com/card/sld/1754/deadly-rollick","gc":false},
{"name":"Force of Will","qty":1,"usd":26.56,"printing":"WC97 #jk28","url":"https://www.tcgplayer.com/product/162316","scryfall":"https://scryfall.com/card/wc97/jk28/force-of-will","gc":true},
{"name":"Grim Tutor","qty":1,"usd":24.46,"printing":"M21 #103","url":"https://www.tcgplayer.com/product/215341","scryfall":"https://scryfall.com/card/m21/103/grim-tutor","gc":false},
{"name":"Polluted Delta","qty":1,"usd":20.5,"printing":"KTK #239","url":"https://www.tcgplayer.com/product/92829","scryfall":"https://scryfall.com/card/ktk/239/polluted-delta","gc":false},
{"name":"Diabolic Intent","qty":1,"usd":15.37,"printing":"FCA #34","url":"https://www.tcgplayer.com/product/632688","scryfall":"https://scryfall.com/card/fca/34/diabolic-intent","gc":false},
{"name":"Sakashima the Impostor","qty":1,"usd":13.82,"printing":"PLST #SOK-53","url":"https://www.tcgplayer.com/product/204143","scryfall":"https://scryfall.com/card/plst/SOK-53/sakashima-the-impostor","gc":false},
{"name":"Coat of Arms","qty":1,"usd":12.24,"printing":"SLD #2682","url":"https://www.tcgplayer.com/product/704936","scryfall":"https://scryfall.com/card/sld/2682/coat-of-arms","gc":false},
{"name":"Mystic Remora","qty":1,"usd":10.55,"printing":"ICE #87","url":"https://www.tcgplayer.com/product/4815","scryfall":"https://scryfall.com/card/ice/87/mystic-remora","gc":false},
{"name":"Swan Song","qty":1,"usd":9.99,"printing":"EOC #46","url":"https://www.tcgplayer.com/product/642791","scryfall":"https://scryfall.com/card/eoc/46/swan-song","gc":false},
{"name":"Watery Grave","qty":1,"usd":9.67,"printing":"GRN #259","url":"https://www.tcgplayer.com/product/175205","scryfall":"https://scryfall.com/card/grn/259/watery-grave","gc":false},
{"name":"Eldrazi Monument","qty":1,"usd":9.14,"printing":"PLST #CMA-216","url":"https://www.tcgplayer.com/product/202949","scryfall":"https://scryfall.com/card/plst/CMA-216/eldrazi-monument","gc":false},
{"name":"Vito, Thorn of the Dusk Rose","qty":1,"usd":9.11,"printing":"J25 #71","url":"https://www.tcgplayer.com/product/590683","scryfall":"https://scryfall.com/card/j25/71/vito-thorn-of-the-dusk-rose","gc":false},
{"name":"Undercity Sewers","qty":1,"usd":8.32,"printing":"PZA #20","url":"https://www.tcgplayer.com/product/679230","scryfall":"https://scryfall.com/card/pza/20/undercity-sewers","gc":false},
{"name":"Virtus the Veiled","qty":1,"usd":8.31,"printing":"BBD #7","url":"https://www.tcgplayer.com/product/167533","scryfall":"https://scryfall.com/card/bbd/7/virtus-the-veiled","gc":false},
{"name":"Ashnod's Altar","qty":1,"usd":8.15,"printing":"WC00 #nl274","url":"https://www.tcgplayer.com/product/164493","scryfall":"https://scryfall.com/card/wc00/nl274/ashnods-altar","gc":false},
{"name":"Demonic Consultation","qty":1,"usd":7.36,"printing":"MB2 #181","url":"https://www.tcgplayer.com/product/563085","scryfall":"https://scryfall.com/card/mb2/181/demonic-consultation","gc":false},
{"name":"Achilles Davenport","qty":1,"usd":6.76,"printing":"ACR #294","url":"https://www.tcgplayer.com/product/555925","scryfall":"https://scryfall.com/card/acr/294/achilles-davenport","gc":false},
{"name":"Reanimate","qty":1,"usd":6.61,"printing":"FIC #282","url":"https://www.tcgplayer.com/product/631573","scryfall":"https://scryfall.com/card/fic/282/reanimate","gc":false},
{"name":"Vein Ripper","qty":1,"usd":6.29,"printing":"MKM #346","url":"https://www.tcgplayer.com/product/533410","scryfall":"https://scryfall.com/card/mkm/346/vein-ripper","gc":false},
{"name":"Snuff Out","qty":1,"usd":5.79,"printing":"FIC #285","url":"https://www.tcgplayer.com/product/631256","scryfall":"https://scryfall.com/card/fic/285/snuff-out","gc":false},
{"name":"Sanguine Bond","qty":1,"usd":5.35,"printing":"WOT #35","url":"https://www.tcgplayer.com/product/512422","scryfall":"https://scryfall.com/card/wot/35/sanguine-bond","gc":false},
{"name":"Mari, the Killing Quill","qty":1,"usd":5.19,"printing":"NCC #89","url":"https://www.tcgplayer.com/product/269114","scryfall":"https://scryfall.com/card/ncc/89/mari-the-killing-quill","gc":false},
{"name":"Kindred Dominance","qty":1,"usd":5.15,"printing":"MSC #156","url":"https://www.tcgplayer.com/product/698010","scryfall":"https://scryfall.com/card/msc/156/kindred-dominance","gc":false},
{"name":"Spark Double","qty":1,"usd":5.03,"printing":"MSC #279","url":"https://www.tcgplayer.com/product/698034","scryfall":"https://scryfall.com/card/msc/279/spark-double","gc":false,"base":true},
{"name":"Unstoppable Slasher","qty":1,"usd":4.48,"printing":"DSK #294","url":"https://www.tcgplayer.com/product/576893","scryfall":"https://scryfall.com/card/dsk/294/unstoppable-slasher","gc":false,"base":true},
{"name":"Mutavault","qty":1,"usd":4.19,"printing":"PLST #CLB-903","url":"https://www.tcgplayer.com/product/631655","scryfall":"https://scryfall.com/card/plst/CLB-903/mutavault","gc":false},
{"name":"Lightning Greaves","qty":1,"usd":3.68,"printing":"FIC #349","url":"https://www.tcgplayer.com/product/631235","scryfall":"https://scryfall.com/card/fic/349/lightning-greaves","gc":false},
{"name":"Arcane Adaptation","qty":1,"usd":3.66,"printing":"PLST #XLN-46","url":"https://www.tcgplayer.com/product/631629","scryfall":"https://scryfall.com/card/plst/XLN-46/arcane-adaptation","gc":false,"base":true},
{"name":"Dark Confidant","qty":1,"usd":3.39,"printing":"FIN #94","url":"https://www.tcgplayer.com/product/630935","scryfall":"https://scryfall.com/card/fin/94/dark-confidant","gc":false},
{"name":"Ramses, Assassin Lord","qty":1,"usd":2.65,"printing":"DMC #39","url":"https://www.tcgplayer.com/product/282769","scryfall":"https://scryfall.com/card/dmc/39/ramses-assassin-lord","gc":false,"base":true},
{"name":"Basim Ibn Ishaq","qty":1,"usd":2.44,"printing":"ACR #49","url":"https://www.tcgplayer.com/product/555942","scryfall":"https://scryfall.com/card/acr/49/basim-ibn-ishaq","gc":false,"base":true},
{"name":"Pyre of Heroes","qty":1,"usd":1.79,"printing":"KHM #241","url":"https://www.tcgplayer.com/product/229212","scryfall":"https://scryfall.com/card/khm/241/pyre-of-heroes","gc":false},
{"name":"Darkslick Shores","qty":1,"usd":1.68,"printing":"ONE #250","url":"https://www.tcgplayer.com/product/478311","scryfall":"https://scryfall.com/card/one/250/darkslick-shores","gc":false,"base":true},
{"name":"Tainted Isle","qty":1,"usd":1.63,"printing":"MIC #183","url":"https://www.tcgplayer.com/product/248796","scryfall":"https://scryfall.com/card/mic/183/tainted-isle","gc":false,"base":true},
{"name":"Quietus Spike","qty":1,"usd":1.45,"printing":"PC2 #112","url":"https://www.tcgplayer.com/product/59630","scryfall":"https://scryfall.com/card/pc2/112/quietus-spike","gc":false},
{"name":"Changeling Outcast","qty":1,"usd":1.2,"printing":"MH1 #82","url":"https://www.tcgplayer.com/product/190942","scryfall":"https://scryfall.com/card/mh1/82/changeling-outcast","gc":false,"base":true},
{"name":"Teferi's Veil","qty":1,"usd":1.06,"printing":"WTH #53","url":"https://www.tcgplayer.com/product/6110","scryfall":"https://scryfall.com/card/wth/53/teferis-veil","gc":false},
{"name":"Sol Ring","qty":1,"usd":1,"printing":"FDC #286","url":"https://www.tcgplayer.com/product/719218","scryfall":"https://scryfall.com/card/fdc/286/sol-ring","gc":false,"base":true},
{"name":"Satoru, the Infiltrator","qty":1,"usd":0.77,"printing":"POTJ #230p","url":"https://www.tcgplayer.com/product/546034","scryfall":"https://scryfall.com/card/potj/230p/satoru-the-infiltrator","gc":false},
{"name":"Preordain","qty":1,"usd":0.65,"printing":"C15 #101","url":"https://www.tcgplayer.com/product/108015","scryfall":"https://scryfall.com/card/c15/101/preordain","gc":false,"base":true},
{"name":"Brainstorm","qty":1,"usd":0.57,"printing":"FRC #39","url":"https://www.tcgplayer.com/product/717702","scryfall":"https://scryfall.com/card/frc/39/brainstorm","gc":false},
{"name":"Leyline of Transformation","qty":1,"usd":0.51,"printing":"PDSK #63p","url":"https://www.tcgplayer.com/product/583662","scryfall":"https://scryfall.com/card/pdsk/63p/leyline-of-transformation","gc":false,"base":true},
{"name":"Reverse the Polarity","qty":1,"usd":0.49,"printing":"WHO #54","url":"https://www.tcgplayer.com/product/518883","scryfall":"https://scryfall.com/card/who/54/reverse-the-polarity","gc":false},
{"name":"Underground River","qty":1,"usd":0.49,"printing":"FRC #87","url":"https://www.tcgplayer.com/product/717757","scryfall":"https://scryfall.com/card/frc/87/underground-river","gc":false,"base":true},
{"name":"Mothdust Changeling","qty":1,"usd":0.45,"printing":"PLST #MOR-42","url":"https://www.tcgplayer.com/product/581626","scryfall":"https://scryfall.com/card/plst/MOR-42/mothdust-changeling","gc":false,"base":true},
{"name":"Dark Ritual","qty":1,"usd":0.44,"printing":"SUM #99","url":"https://www.tcgplayer.com/product/211791","scryfall":"https://scryfall.com/card/sum/99/dark-ritual","gc":false,"base":true},
{"name":"Talisman of Dominance","qty":1,"usd":0.4,"printing":"FRC #62","url":"https://www.tcgplayer.com/product/717784","scryfall":"https://scryfall.com/card/frc/62/talisman-of-dominance","gc":false,"base":true},
{"name":"Arcane Signet","qty":1,"usd":0.37,"printing":"FDC #245","url":"https://www.tcgplayer.com/product/719175","scryfall":"https://scryfall.com/card/fdc/245/arcane-signet","gc":false,"base":true},
{"name":"Drowned Catacomb","qty":1,"usd":0.37,"printing":"FRC #69","url":"https://www.tcgplayer.com/product/717739","scryfall":"https://scryfall.com/card/frc/69/drowned-catacomb","gc":false,"base":true},
{"name":"Slither Blade","qty":1,"usd":0.35,"printing":"AKH #71","url":"https://www.tcgplayer.com/product/130277","scryfall":"https://scryfall.com/card/akh/71/slither-blade","gc":false},
{"name":"Etrata, Deadly Fugitive","qty":1,"usd":0.34,"printing":"MKM #200","url":"https://www.tcgplayer.com/product/532917","scryfall":"https://scryfall.com/card/mkm/200/etrata-deadly-fugitive","gc":false,"base":true},
{"name":"They Came from the Pipes","qty":1,"usd":0.33,"printing":"DSC #14","url":"https://www.tcgplayer.com/product/577804","scryfall":"https://scryfall.com/card/dsc/14/they-came-from-the-pipes","gc":false,"base":true},
{"name":"Brotherhood Headquarters","qty":1,"usd":0.33,"printing":"ACR #80","url":"https://www.tcgplayer.com/product/555908","scryfall":"https://scryfall.com/card/acr/80/brotherhood-headquarters","gc":false},
{"name":"River of Tears","qty":1,"usd":0.32,"printing":"MKC #283","url":"https://www.tcgplayer.com/product/535797","scryfall":"https://scryfall.com/card/mkc/283/river-of-tears","gc":false,"base":true},
{"name":"Sunken Hollow","qty":1,"usd":0.31,"printing":"BFZ #249","url":"https://www.tcgplayer.com/product/104305","scryfall":"https://scryfall.com/card/bfz/249/sunken-hollow","gc":false,"base":true},
{"name":"Darkwater Catacombs","qty":1,"usd":0.3,"printing":"PLST #OTC-282","url":"https://www.tcgplayer.com/product/631647","scryfall":"https://scryfall.com/card/plst/OTC-282/darkwater-catacombs","gc":false,"base":true},
{"name":"Choked Estuary","qty":1,"usd":0.29,"printing":"FIC #379","url":"https://www.tcgplayer.com/product/631309","scryfall":"https://scryfall.com/card/fic/379/choked-estuary","gc":false,"base":true},
{"name":"Secluded Courtyard","qty":1,"usd":0.29,"printing":"ECC #62","url":"https://www.tcgplayer.com/product/671189","scryfall":"https://scryfall.com/card/ecc/62/secluded-courtyard","gc":false},
{"name":"Rogue's Passage","qty":1,"usd":0.27,"printing":"FDC #310","url":"https://www.tcgplayer.com/product/719262","scryfall":"https://scryfall.com/card/fdc/310/rogues-passage","gc":false,"base":true},
{"name":"Roshan, Hidden Magister","qty":1,"usd":0.26,"printing":"ACR #133","url":"https://www.tcgplayer.com/product/556354","scryfall":"https://scryfall.com/card/acr/133/roshan-hidden-magister","gc":false,"base":true},
{"name":"Path of Ancestry","qty":1,"usd":0.21,"printing":"SCD #312","url":"https://www.tcgplayer.com/product/456942","scryfall":"https://scryfall.com/card/scd/312/path-of-ancestry","gc":false,"base":true},
{"name":"Command Tower","qty":1,"usd":0.2,"printing":"TDC #107","url":"https://www.tcgplayer.com/product/623982","scryfall":"https://scryfall.com/card/tdc/107/command-tower","gc":false,"base":true},
{"name":"Hired Poisoner","qty":1,"usd":0.18,"printing":"GRN #72","url":"https://www.tcgplayer.com/product/176928","scryfall":"https://scryfall.com/card/grn/72/hired-poisoner","gc":false},
{"name":"Brotherhood Spy","qty":1,"usd":0.18,"printing":"ACR #282","url":"https://www.tcgplayer.com/product/556386","scryfall":"https://scryfall.com/card/acr/282/brotherhood-spy","gc":false,"base":true},
{"name":"Reno and Rude","qty":1,"usd":0.18,"printing":"FIN #113","url":"https://www.tcgplayer.com/product/632634","scryfall":"https://scryfall.com/card/fin/113/reno-and-rude","gc":false},
{"name":"Tetsuko Umezawa, Fugitive","qty":1,"usd":0.15,"printing":"CMM #126","url":"https://www.tcgplayer.com/product/507460","scryfall":"https://scryfall.com/card/cmm/126/tetsuko-umezawa-fugitive","gc":false},
{"name":"Island","qty":8,"usd":0.07,"printing":"SOI #287","url":"https://www.tcgplayer.com/product/115929","scryfall":"https://scryfall.com/card/soi/287/island","gc":false,"base":true},
{"name":"Swamp","qty":7,"usd":0.05,"printing":"HOP #151","url":"https://www.tcgplayer.com/product/80266","scryfall":"https://scryfall.com/card/hop/151/swamp","gc":false,"base":true}
]};
