/* Quiz question bank for the Corrupted Etrata deck: the heist closer list ("Etrata Heist", Etrata, Deadly Fugitive).
   Each question: { id, topic, q, options, answer (index or array of indices for choose-all), explain, cards }.
   Topics: kills, snowball, tutors, cards, rules, plan, mana, rulings.
   kills: Ramses and the drain loop. snowball: the cloak engine (type-changers, copies, anthems, payoffs).
   plan: the nine piloting rules and the game plan, with their measured gains. Every number comes from
   research/etrata-theft-aggro/local/REPORT.md and is a bot-game number (5,040 games per field unless noted).
   Card mentions use <i-c>Exact Card Name</i-c>, only for cards in the heist list or the v3 drain list. */
window.CETRATA_QUIZ = [
  /* ---------- kills: Ramses and the drain loop ---------- */
  { id: "k-ramses-text", topic: "kills",
    q: "<i-c>Ramses, Assassin Lord</i-c> is on the battlefield. An opponent loses the game. When do you win?",
    options: ["Only if they died to combat damage", "Only if they died on your turn", "Always: any opponent losing wins you the game", "If an Assassin you controlled attacked them this turn, however they lost"],
    answer: 3,
    explain: "“Whenever a player loses the game, if they were attacked this turn by an Assassin you controlled, you win the game.” Combat, a halver, the drain loop, <i-c>Bloodletter of Aclazotz</i-c>: any way they lose counts, as long as an Assassin of yours attacked them this turn.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "k-ramses-one-death", topic: "kills",
    q: "With <i-c>Ramses, Assassin Lord</i-c> out, how many opponents do you have to kill to win?",
    options: ["One, if an Assassin of yours attacked them this turn", "Two", "All three", "None: he wins on his own when he attacks"],
    answer: 0,
    explain: "One death is the game. That's why the deck picks one player and kills them once Ramses is out.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "k-ramses-walker", topic: "kills",
    q: "Your Assassins attack an opponent's planeswalker, not the opponent. Later this turn that opponent loses the game. Does <i-c>Ramses, Assassin Lord</i-c> win you the game?",
    options: ["Yes, attacking their permanent counts", "Only if the planeswalker died", "Only if Ramses attacked", "No: the player has to be attacked, not their planeswalker"],
    answer: 3,
    explain: "Ramses ruling: attacking a planeswalker the player controls won't count. Send at least one Assassin at the player.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "k-ramses-dead-attacker", topic: "kills",
    q: "<i-c>Hired Poisoner</i-c> attacked a player and died in combat. After combat the drain loop kills that player. Does <i-c>Ramses, Assassin Lord</i-c> trigger?",
    options: ["No, the Assassin has to still be on the battlefield", "Yes: it only matters that an Assassin you controlled attacked them this turn", "Only if the Poisoner dealt damage", "Only on an opponent's turn"],
    answer: 1,
    explain: "Ramses ruling: it works even if the Assassin is no longer on the battlefield, no longer under your control or no longer an Assassin when the player loses.",
    cards: ["Ramses, Assassin Lord", "Hired Poisoner"] },
  { id: "k-loop-pairs", topic: "kills",
    q: "The drain loop needs one card from each side. How many two-card loops does the heist closer have?",
    options: ["Two", "Six", "Three", "Four"],
    answer: 3,
    explain: "Two cards gain you life when an opponent loses (<i-c>Exquisite Blood</i-c>, <i-c>Bloodthirsty Conqueror</i-c>) and two make an opponent lose when you gain (<i-c>Sanguine Bond</i-c>, <i-c>Vito, Thorn of the Dusk Rose</i-c>). Two times two is four.",
    cards: ["Exquisite Blood", "Bloodthirsty Conqueror", "Sanguine Bond", "Vito, Thorn of the Dusk Rose"] },
  { id: "k-loop-not-pair", topic: "kills",
    q: "Which pair does NOT make the drain loop?",
    options: ["<i-c>Exquisite Blood</i-c> and <i-c>Vito, Thorn of the Dusk Rose</i-c>", "<i-c>Bloodthirsty Conqueror</i-c> and <i-c>Sanguine Bond</i-c>", "<i-c>Exquisite Blood</i-c> and <i-c>Sanguine Bond</i-c>", "<i-c>Sanguine Bond</i-c> and <i-c>Vito, Thorn of the Dusk Rose</i-c>"],
    answer: 3,
    explain: "Bond and Vito both turn your life gain into an opponent's loss. Nothing turns that loss back into a gain, so it stops after one step. You need one of each side.",
    cards: ["Sanguine Bond", "Vito, Thorn of the Dusk Rose"] },
  { id: "k-loop-start", topic: "kills",
    q: "<i-c>Exquisite Blood</i-c> and <i-c>Sanguine Bond</i-c> are out. <i-c>Changeling Outcast</i-c> deals 1 combat damage to an opponent. What happens?",
    options: ["The loop starts and runs until every opponent is dead", "That opponent loses 1 and it stops", "You gain 1 and it stops", "Nothing: combat damage isn't life loss"],
    answer: 0,
    explain: "Damage makes them lose life. Exquisite Blood gains you 1, Bond makes a target opponent lose 1, which triggers Exquisite Blood again, and so on. Each new Bond trigger targets an opponent still alive.",
    cards: ["Exquisite Blood", "Sanguine Bond", "Changeling Outcast"] },
  { id: "k-loop-their-turn", topic: "kills",
    q: "<i-c>Bloodthirsty Conqueror</i-c> and <i-c>Vito, Thorn of the Dusk Rose</i-c> are out. On their own turn, an opponent pays 1 life to crack a fetchland. What happens?",
    options: ["Nothing until your turn", "The loop starts: every opponent dies", "Only that opponent loses 1", "You gain 1, then it stops"],
    answer: 1,
    explain: "Paying life is losing life. The Conqueror works on any turn, so the loop runs on theirs. <i-c>Ramses, Assassin Lord</i-c> doesn't matter here: the loop kills all three by itself.",
    cards: ["Bloodthirsty Conqueror", "Vito, Thorn of the Dusk Rose"] },
  { id: "k-ramses-loop", topic: "kills",
    q: "Ramses is out. <i-c>Hired Poisoner</i-c> attacked one opponent this turn; nobody else was attacked. After combat the drain loop starts and the first player to die is a different opponent. What happens?",
    options: ["You win as soon as anyone dies", "You lose: the loop counts as an attack on you", "Ramses stops the loop", "No win yet: that player wasn't attacked by an Assassin. The loop keeps going, and when the Poisoner's player dies, Ramses wins you the game"],
    answer: 3,
    explain: "Ramses checks the player who just lost. Here it makes no real difference: the loop kills all three anyway. It matters when only one player can die this turn: make sure that's the one an Assassin attacked.",
    cards: ["Ramses, Assassin Lord", "Hired Poisoner"] },
  { id: "k-virtus-40", topic: "kills",
    q: "No Ramses, no Bloodletter. <i-c>Virtus the Veiled</i-c> (1/1) deals 1 combat damage to a player at 40. Where do they end up?",
    options: ["19", "20", "0", "39"],
    answer: 0,
    explain: "40 minus 1 is 39. Then the trigger: half of 39 rounded up is 20. 39 minus 20 is 19.",
    cards: ["Virtus the Veiled"] },
  { id: "k-bloodletter-halve", topic: "kills",
    q: "Your turn. <i-c>Ramses, Assassin Lord</i-c> and <i-c>Bloodletter of Aclazotz</i-c> are out. <i-c>Virtus the Veiled</i-c>, now a 2/2, hits a player at 30. Where do they end up?",
    options: ["13", "26", "15", "0"],
    answer: 3,
    explain: "The 2 damage becomes 4 life lost: 26. Half of 26 is 13, doubled to 26. They're at 0, and Ramses wins you the game. On your turn, halve plus double is always all of it.",
    cards: ["Bloodletter of Aclazotz", "Virtus the Veiled", "Ramses, Assassin Lord"] },
  { id: "k-two-halvers", topic: "kills",
    q: "No Ramses, no Bloodletter. <i-c>Virtus the Veiled</i-c> (1 damage) and <i-c>Unstoppable Slasher</i-c> (2 damage) both hit a player at 40. Where do they end up?",
    options: ["0", "9", "19", "18"],
    answer: 1,
    explain: "Combat damage first: 40 to 37. The first trigger takes half of 37 rounded up, 19: 18 left. The second takes half of 18, 9: 9 left. Each halving looks at the life total as it resolves.",
    cards: ["Virtus the Veiled", "Unstoppable Slasher"] },
  { id: "k-bloodletter-turn", topic: "kills",
    q: "When does <i-c>Bloodletter of Aclazotz</i-c> double an opponent's life loss?",
    options: ["On every turn", "Only from combat damage", "Only while you control Ramses", "Only during your turn"],
    answer: 3,
    explain: "“If an opponent would lose life during your turn, they lose twice that much life instead.” Swing with the halvers on your turn.",
    cards: ["Bloodletter of Aclazotz"] },
  { id: "k-ripper-altar", topic: "kills",
    q: "<i-c>Vein Ripper</i-c> and <i-c>Ashnod's Altar</i-c> are out, no loop piece. You sacrifice three stolen face-down 2/2s. What do you get?",
    options: ["Nothing: stolen cards don't die, they go home", "{C}{C} only", "Opponents lose 6 in total, you gain 6, and you get six colorless mana", "Each opponent loses 6"],
    answer: 2,
    explain: "Each sacrifice is a creature dying (it goes to its owner's graveyard): the Ripper makes a target opponent lose 2 and you gain 2, and the Altar adds {C}{C}. With <i-c>Sanguine Bond</i-c> or <i-c>Vito, Thorn of the Dusk Rose</i-c> plus a drain piece, any of those triggers starts the loop.",
    cards: ["Vein Ripper", "Ashnod's Altar"] },
  { id: "k-spike-outcast", topic: "kills",
    q: "Your turn, Ramses and Bloodletter out. Which attacker with <i-c>Quietus Spike</i-c> is sure to kill the player it hits?",
    options: ["<i-c>Changeling Outcast</i-c>: it can't be blocked, and on your turn the halving is doubled to all of their life", "None: the Spike only works with deathtouch blockers", "Only <i-c>Etrata, Deadly Fugitive</i-c>", "Only a 1/1, because of Tetsuko"],
    answer: 0,
    explain: "The Outcast can't be blocked by its own text. Its hit is doubled, then the Spike's half rounded up is doubled to the whole total. It's every creature type, so it's an Assassin and Ramses wins you the game.",
    cards: ["Quietus Spike", "Changeling Outcast", "Bloodletter of Aclazotz"] },
  { id: "k-share", topic: "kills",
    q: "In the bot games against three precons, what share of the heist closer's eliminations came from combat damage?",
    options: ["9%", "36%", "93%", "55%"],
    answer: 3,
    explain: "In the 5,040-game confirmation run (bot games): combat damage 55% (63% against Bracket 4), the loop and the other drains 36% / 28%, the halvers' and Bloodletter's on-hit triggers 9% / 9%." },
  { id: "k-why-loop", topic: "kills",
    q: "Why does the heist closer play the drain loop, according to the bot games?",
    options: ["It's the only other effect in the deck that kills three players at once", "It protects Ramses", "It finds Ramses", "It's cheaper than the halvers"],
    answer: 0,
    explain: "The halvers and Bloodletter kill one player, which only wins with Ramses. The loop wins 38% of the games in which Ramses never lands against the precons, against 17% for the snowball list without it (bot games).",
    cards: ["Exquisite Blood", "Sanguine Bond"] },

  /* ---------- snowball: the cloak engine ---------- */
  { id: "s-cloak-trigger", topic: "snowball",
    q: "What triggers Etrata's cloak?",
    options: ["Any creature dealing combat damage to an opponent", "An Assassin you control dealing combat damage to an opponent", "Etrata attacking", "A face-down creature entering"],
    answer: 1,
    explain: "Only Assassins count, one cloak per Assassin that connects, from the damaged player's library.",
    cards: ["Etrata, Deadly Fugitive"] },
  { id: "s-facedown-types", topic: "snowball",
    q: "With no type-changer out, a face-down 2/2 you cloaked deals combat damage to an opponent. Does Etrata cloak again?",
    options: ["Yes, face-down creatures are every type", "Only if the card under it is an Assassin", "Only with Ramses out", "No: a face-down creature has no creature types, so it isn't an Assassin"],
    answer: 3,
    explain: "Face down it's a 2/2 with no name and no creature types. That's what the type-changers are for.",
    cards: ["Etrata, Deadly Fugitive"] },
  { id: "s-type-changers", topic: "snowball",
    q: "Choose all that apply: which cards make your face-down 2/2s Assassins?",
    options: ["<i-c>Leyline of Transformation</i-c>", "<i-c>Tetsuko Umezawa, Fugitive</i-c>", "<i-c>Arcane Adaptation</i-c>", "<i-c>Roshan, Hidden Magister</i-c>"],
    answer: [0, 2, 3],
    explain: "Leyline and Arcane Adaptation make creatures you control the chosen type (choose Assassin), face-down ones included. Roshan makes other creatures you control Assassins. Tetsuko only makes small creatures unblockable.",
    cards: ["Leyline of Transformation", "Arcane Adaptation", "Roshan, Hidden Magister"] },
  { id: "s-roshan", topic: "snowball",
    q: "What else does <i-c>Roshan, Hidden Magister</i-c> give your face-down creatures?",
    options: ["Flying", "Deathtouch", "Ward {4}", "Menace"],
    answer: 3,
    explain: "Face-down creatures you control have menace. And whenever a permanent you control is turned face up, you draw a card and lose 1 life.",
    cards: ["Roshan, Hidden Magister"] },
  { id: "s-spark-etrata", topic: "snowball",
    q: "<i-c>Spark Double</i-c> copies Etrata. An Assassin hits an opponent. How many cards do you cloak?",
    options: ["One", "Three", "None, the copy is legendary and dies", "Two"],
    answer: 3,
    explain: "Both Etratas trigger. The copy isn't legendary, so the legend rule doesn't apply. It enters with an extra +1/+1 counter: a 2/5.",
    cards: ["Spark Double", "Etrata, Deadly Fugitive"] },
  { id: "s-sakashima", topic: "snowball",
    q: "You cast <i-c>Sakashima the Impostor</i-c> as a copy of Etrata. Why don't you lose one to the legend rule?",
    options: ["Sakashima isn't legendary", "Its name is Sakashima the Impostor, not Etrata's", "The legend rule doesn't apply to commanders", "You do lose one"],
    answer: 1,
    explain: "The legend rule only checks legendary permanents with the same name. Sakashima copies Etrata but keeps its own name. It works the same way on Ramses: a second lord and a second “you win”.",
    cards: ["Sakashima the Impostor"] },
  { id: "s-throne", topic: "snowball",
    q: "<i-c>Roaming Throne</i-c> named Assassin. An Assassin hits an opponent. How many cloaks does Etrata make?",
    options: ["Two", "One", "Four", "None, the Throne only doubles its own triggers"],
    answer: 0,
    explain: "Etrata is a Vampire Assassin, another creature of the chosen type, so her trigger triggers an additional time.",
    cards: ["Roaming Throne", "Etrata, Deadly Fugitive"] },
  { id: "s-throne-virtus", topic: "snowball",
    q: "<i-c>Roaming Throne</i-c> named Assassin, no Ramses, no Bloodletter. <i-c>Virtus the Veiled</i-c> deals 1 damage to a player at 40. Where do they end up?",
    options: ["19", "0", "10", "9"],
    answer: 3,
    explain: "40 to 39. Virtus is an Assassin, so its trigger happens twice: half of 39 rounded up (20) leaves 19, then half of 19 rounded up (10) leaves 9.",
    cards: ["Roaming Throne", "Virtus the Veiled"] },
  { id: "s-pipes", topic: "snowball",
    q: "<i-c>They Came from the Pipes</i-c> is out. Two Assassins connect and Etrata cloaks two cards. What do you draw?",
    options: ["Nothing", "Two cards", "One card", "Only a card if the cloaks are creatures"],
    answer: 1,
    explain: "“Whenever a face-down creature you control enters, draw a card.” Each cloak is a face-down creature entering.",
    cards: ["They Came from the Pipes"] },
  { id: "s-satoru", topic: "snowball",
    q: "Does a cloak entering trigger <i-c>Satoru, the Infiltrator</i-c>?",
    options: ["Yes: it entered without being cast", "No: only cast creatures count", "Only if it's a creature card", "Only during combat"],
    answer: 0,
    explain: "Satoru draws when nontoken creatures enter and none of them were cast (or no mana was spent on them). A cloak is put onto the battlefield, not cast. So is a creature from <i-c>Pyre of Heroes</i-c> or <i-c>Reanimate</i-c>.",
    cards: ["Satoru, the Infiltrator"] },
  { id: "s-lords", topic: "snowball",
    q: "<i-c>Ramses, Assassin Lord</i-c> and <i-c>Achilles Davenport</i-c> are out. How big is <i-c>Hired Poisoner</i-c>?",
    options: ["2/2", "1/1", "4/4", "3/3"],
    answer: 3,
    explain: "Each gives other Assassins +1/+1, so the 1/1 gets +2/+2. Ramses and Achilles each get +1/+1 from the other.",
    cards: ["Ramses, Assassin Lord", "Achilles Davenport", "Hired Poisoner"] },
  { id: "s-coat", topic: "snowball",
    q: "<i-c>Leyline of Transformation</i-c> named Assassin. You control five creatures and nobody else has any. <i-c>Coat of Arms</i-c> comes down. How much does each of yours get?",
    options: ["+5/+5", "+1/+1", "Nothing, face-down creatures don't count", "+4/+4"],
    answer: 3,
    explain: "Each creature gets +1/+1 for each OTHER creature on the battlefield that shares a type with it. All five are Assassins, so each counts four others. Watch the opponents' creatures: any that share a type count too.",
    cards: ["Coat of Arms", "Leyline of Transformation"] },
  { id: "s-ward", topic: "snowball",
    q: "What protects a cloaked 2/2?",
    options: ["Hexproof", "Indestructible", "Ward {2}", "Nothing"],
    answer: 2,
    explain: "A cloak is a face-down 2/2 with ward {2}: a spell or ability that targets it is countered unless its controller pays {2}." },
  { id: "s-achilles", topic: "snowball",
    q: "When can you cast <i-c>Achilles Davenport</i-c> for its freerunning cost, {U}{B}?",
    options: ["Any time an Assassin attacked this turn", "Only if you control Ramses", "Only during combat", "After an Assassin or your commander dealt combat damage to a player this turn"],
    answer: 3,
    explain: "Freerunning needs combat damage to a player this turn from an Assassin or a commander. He's a creature, so that means your second main phase.",
    cards: ["Achilles Davenport"] },
  { id: "s-steals", topic: "snowball",
    q: "In the confirmation run (bot games), how many cards a game did the heist closer steal against the precons?",
    options: ["2.1", "12.4", "7.3", "4.0"],
    answer: 2,
    explain: "7.3 against the precons and 5.1 against Bracket 4 (8.5 in wins, 6.1 in losses against the precons). Almost all of it is Etrata's cloak." },
  { id: "s-commander-worth", topic: "snowball",
    q: "In the bot games, what did removing Etrata from the deck cost against the precons?",
    options: ["Nothing measurable", "40 points", "3 points", "16.7 points"],
    answer: 3,
    explain: "16.7 ±0.8 points against the precons and 7.0 ±0.7 against Bracket 4, over 5,040 paired games each. The engine is the commander." },

  /* ---------- tutors ---------- */
  { id: "t-first", topic: "tutors",
    q: "You resolve your first tutor and Ramses isn't out. What do you find?",
    options: ["<i-c>Bloodletter of Aclazotz</i-c>", "<i-c>Ramses, Assassin Lord</i-c>", "<i-c>Lightning Greaves</i-c>", "A drain-loop piece"],
    answer: 1,
    explain: "Rule 3: tutor for Ramses first. In the bot games, tutoring generic targets first cost 10.9 points against the precons and the kill kit first 6.2. After Ramses the order barely matters.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "t-count", topic: "tutors",
    q: "How many cards in the list can find Ramses from the library?",
    options: ["Seven", "Three", "Five", "Ten"],
    answer: 0,
    explain: "<i-c>Demonic Tutor</i-c>, <i-c>Vampiric Tutor</i-c>, <i-c>Imperial Seal</i-c>, <i-c>Grim Tutor</i-c>, <i-c>Diabolic Intent</i-c>, <i-c>Demonic Consultation</i-c> and <i-c>Pyre of Heroes</i-c>. <i-c>Reanimate</i-c> brings him back from a graveyard." },
  { id: "t-pyre-pick", topic: "tutors",
    q: "Which creature can you sacrifice to <i-c>Pyre of Heroes</i-c> to put Ramses onto the battlefield?",
    options: ["<i-c>Tetsuko Umezawa, Fugitive</i-c>", "<i-c>Changeling Outcast</i-c>", "<i-c>Bloodletter of Aclazotz</i-c>", "<i-c>Virtus the Veiled</i-c>"],
    answer: 3,
    explain: "The Pyre finds a creature that shares a type with the sacrificed one and costs exactly 1 more. Virtus is a 3-mana Assassin, Ramses a 4-mana Assassin. <i-c>Unstoppable Slasher</i-c>, <i-c>Mari, the Killing Quill</i-c> and Etrata work too.",
    cards: ["Pyre of Heroes", "Virtus the Veiled"] },
  { id: "t-pyre-outcast", topic: "tutors",
    q: "You sacrifice <i-c>Changeling Outcast</i-c> to <i-c>Pyre of Heroes</i-c>. What can you find?",
    options: ["Any creature with mana value 2", "Only an Assassin with mana value 2", "Ramses", "Nothing: changelings have no type"],
    answer: 0,
    explain: "The Outcast is every creature type and has mana value 1, so any 2-mana creature shares a type with it: <i-c>Tetsuko Umezawa, Fugitive</i-c>, <i-c>Satoru, the Infiltrator</i-c>, <i-c>Dark Confidant</i-c>, <i-c>Basim Ibn Ishaq</i-c> and the rest.",
    cards: ["Pyre of Heroes", "Changeling Outcast"] },
  { id: "t-pyre-speed", topic: "tutors",
    q: "When can you activate <i-c>Pyre of Heroes</i-c>?",
    options: ["Any time you have priority", "Only in combat", "Only as a sorcery: your main phase, empty stack", "Only on an opponent's turn"],
    answer: 2,
    explain: "“Activate only as a sorcery.” Ramses arrives in your main phase, ready to attack next turn (or this turn with <i-c>Lightning Greaves</i-c>).",
    cards: ["Pyre of Heroes"] },
  { id: "t-vampiric-when", topic: "tutors",
    q: "When is the best time to cast <i-c>Vampiric Tutor</i-c> for Ramses?",
    options: ["In your main phase", "In response to your own draw trigger", "In your upkeep", "At the end of the turn before yours"],
    answer: 3,
    explain: "It's an instant that puts the card on top. Cast it at the last end step before your turn and you draw Ramses in your draw step, with mana that untaps anyway.",
    cards: ["Vampiric Tutor"] },
  { id: "t-instants", topic: "tutors",
    q: "Choose all that apply: which tutors are instants?",
    options: ["<i-c>Imperial Seal</i-c>", "<i-c>Vampiric Tutor</i-c>", "<i-c>Grim Tutor</i-c>", "<i-c>Demonic Consultation</i-c>"],
    answer: [1, 3],
    explain: "Vampiric Tutor and Demonic Consultation are instants. Imperial Seal, Grim Tutor, Demonic Tutor and Diabolic Intent are sorceries.",
    cards: ["Vampiric Tutor", "Demonic Consultation"] },
  { id: "t-consult-top", topic: "tutors",
    q: "You <i-c>Brainstorm</i-c> and put Ramses back on top. Then you cast <i-c>Demonic Consultation</i-c> naming Ramses. What happens?",
    options: ["You get Ramses: he's on top", "Ramses is exiled with the top six, and you keep revealing and exiling until the library is gone", "Consultation fizzles", "You shuffle first"],
    answer: 1,
    explain: "Consultation exiles the top six before it reveals anything. With no Ramses left, nothing matches and every revealed card is exiled: your whole library.",
    cards: ["Demonic Consultation", "Brainstorm"] },
  { id: "t-consult-name", topic: "tutors",
    q: "When do you name a card for <i-c>Demonic Consultation</i-c>?",
    options: ["As you cast it", "Before you draw for the turn", "As it resolves", "When you reveal the first card"],
    answer: 2,
    explain: "You name it on resolution (Consultation ruling). In the bot games, Consultation exiling half the library is part of why 8% of the losses against the precons were empty libraries.",
    cards: ["Demonic Consultation"] },
  { id: "t-intent", topic: "tutors",
    q: "What's the best creature to sacrifice to <i-c>Diabolic Intent</i-c>?",
    options: ["Etrata", "Ramses", "A stolen face-down 2/2 you don't need", "<i-c>Tetsuko Umezawa, Fugitive</i-c>"],
    answer: 2,
    explain: "The extra cost is any creature. A stolen 2/2 costs you nothing you paid for. It goes to its owner's graveyard.",
    cards: ["Diabolic Intent"] },
  { id: "t-bob", topic: "tutors",
    q: "<i-c>Dark Confidant</i-c> is out. You <i-c>Vampiric Tutor</i-c> for Ramses at the end of the turn before yours. How much life does it cost you by your draw step?",
    options: ["2", "4", "0", "6"],
    answer: 3,
    explain: "2 for the Tutor, then Bob reveals Ramses in your upkeep and you lose his mana value, 4. And you get him in your upkeep rather than your draw step.",
    cards: ["Dark Confidant", "Vampiric Tutor"] },
  { id: "t-reanimate", topic: "tutors",
    q: "Ramses died to a wrath. You cast <i-c>Reanimate</i-c> on him. What does it cost you?",
    options: ["{B} and 4 life", "{B} only", "{B} and 2 life", "{B} and half your life"],
    answer: 0,
    explain: "You lose life equal to the card's mana value: 4. Reanimate can also take a creature from an opponent's graveyard.",
    cards: ["Reanimate"] },
  { id: "t-grim", topic: "tutors",
    q: "Which tutor costs you 3 life?",
    options: ["<i-c>Demonic Tutor</i-c>", "<i-c>Imperial Seal</i-c>", "<i-c>Diabolic Intent</i-c>", "<i-c>Grim Tutor</i-c>"],
    answer: 3,
    explain: "Grim Tutor is {1}{B}{B} and 3 life, to your hand. Vampiric Tutor and Imperial Seal cost 2 life and put the card on top.",
    cards: ["Grim Tutor"] },

  /* ---------- cards ---------- */
  { id: "c-etrata-pt", topic: "cards",
    q: "What are Etrata, Deadly Fugitive's power and toughness?",
    options: ["1/4", "2/2", "4/4", "1/1"],
    answer: 0,
    explain: "A 1/4 with deathtouch, for {1}{U}{B}. With 1 power, <i-c>Tetsuko Umezawa, Fugitive</i-c> makes her unblockable." },
  { id: "c-etrata-flip", topic: "cards",
    q: "What does the ability Etrata gives your face-down creatures cost?",
    options: ["{U}{B}", "{1}{U}{B}", "{3}", "{2}{U}{B}"],
    answer: 3,
    explain: "{2}{U}{B}: turn it face up, or if it can't be (a noncreature card), exile it and you may cast it without paying its mana cost." },
  { id: "c-outcast", topic: "cards",
    q: "Why is <i-c>Changeling Outcast</i-c> the best one-drop here?",
    options: ["It makes mana", "It's every creature type (an Assassin) and can't be blocked", "It gives the team deathtouch", "It draws a card each turn"],
    answer: 1,
    explain: "Changeling makes it an Assassin for Etrata, and it connects every turn. It can't block, though.",
    cards: ["Changeling Outcast"] },
  { id: "c-tetsuko", topic: "cards",
    q: "What does <i-c>Tetsuko Umezawa, Fugitive</i-c> do?",
    options: ["Creatures you control with power or toughness 1 or less can't be blocked", "Assassins you control can't be blocked", "Creatures with power 1 get flying", "Your face-down creatures can't be blocked"],
    answer: 0,
    explain: "Power OR toughness 1 or less. Etrata (1/4), <i-c>Hired Poisoner</i-c> and <i-c>Virtus the Veiled</i-c> qualify. Face-down 2/2s don't.",
    cards: ["Tetsuko Umezawa, Fugitive"] },
  { id: "c-spy", topic: "cards",
    q: "<i-c>Brotherhood Spy</i-c> gets +1/+0 and can't be blocked if you control a legendary Assassin. Which of these does NOT turn it on?",
    options: ["Etrata", "<i-c>Reno and Rude</i-c>", "<i-c>Tetsuko Umezawa, Fugitive</i-c>", "<i-c>Basim Ibn Ishaq</i-c>"],
    answer: 2,
    explain: "Tetsuko is a legendary Human Rogue, not an Assassin (unless a type-changer is out). Etrata, Reno and Rude, Basim, Virtus, Mari, Ramses, Achilles and Roshan all count. The check is at the beginning of combat on your turn.",
    cards: ["Brotherhood Spy", "Tetsuko Umezawa, Fugitive"] },
  { id: "c-mari-rogue", topic: "cards",
    q: "<i-c>Mari, the Killing Quill</i-c> is out. Which of these gets deathtouch from her?",
    options: ["<i-c>Slither Blade</i-c>", "<i-c>Dark Confidant</i-c>", "<i-c>Bloodletter of Aclazotz</i-c>", "A face-down 2/2 with no type-changer"],
    answer: 0,
    explain: "Mari gives Assassins, Mercenaries and Rogues deathtouch and her card-and-Treasures trigger. Slither Blade is a Snake Rogue. Bob is a Human Wizard, Bloodletter a Vampire Demon, and a face-down creature has no types.",
    cards: ["Mari, the Killing Quill", "Slither Blade"] },
  { id: "c-reno", topic: "cards",
    q: "<i-c>Reno and Rude</i-c> hits a player. What do you need to play the card it exiles?",
    options: ["Mana of that card's colors", "Nothing, it's free", "To sacrifice another creature or artifact, then play it this turn with any type of mana", "Etrata on the battlefield"],
    answer: 2,
    explain: "A stolen face-down 2/2 is a fine thing to sacrifice. You still follow timing rules: a land only as your land play.",
    cards: ["Reno and Rude"] },
  { id: "c-basim", topic: "cards",
    q: "When does <i-c>Basim Ibn Ishaq</i-c> draw you a card and become unblockable this turn?",
    options: ["When it attacks", "The first time each turn you cast a historic spell (artifact, legendary or Saga)", "When an Assassin dies", "When you cloak"],
    answer: 1,
    explain: "Once each turn. Etrata, Ramses, <i-c>Sol Ring</i-c>, <i-c>Lightning Greaves</i-c>: lots of the deck is historic. It also grows a +1/+1 counter whenever it hits a player.",
    cards: ["Basim Ibn Ishaq"] },
  { id: "c-slasher", topic: "cards",
    q: "<i-c>Unstoppable Slasher</i-c> dies with no counters on it. What happens?",
    options: ["It's gone", "It returns to your hand", "It returns tapped with two stun counters", "It returns untapped with a +1/+1 counter"],
    answer: 2,
    explain: "It returns to the battlefield tapped under its owner's control with two stun counters. With counters on it, it stays dead next time.",
    cards: ["Unstoppable Slasher"] },
  { id: "c-mothdust", topic: "cards",
    q: "How does <i-c>Mothdust Changeling</i-c> get flying?",
    options: ["It always has flying", "Pay {U}", "Tap an untapped creature you control", "Only with Eldrazi Monument"],
    answer: 2,
    explain: "Tap an untapped creature you control: it gains flying until end of turn. A face-down 2/2 that isn't attacking can pay for it.",
    cards: ["Mothdust Changeling"] },
  { id: "c-free", topic: "cards",
    q: "Choose all that apply: which spells are free while you control a commander?",
    options: ["<i-c>Fierce Guardianship</i-c>", "<i-c>Force of Negation</i-c>", "<i-c>Deadly Rollick</i-c>", "<i-c>Swan Song</i-c>"],
    answer: [0, 2],
    explain: "Both say “If you control a commander, you may cast this spell without paying its mana cost.” Force of Negation is free (exile a blue card) only when it isn't your turn.",
    cards: ["Fierce Guardianship", "Deadly Rollick"] },
  { id: "c-snuff", topic: "cards",
    q: "What can <i-c>Snuff Out</i-c> NOT destroy?",
    options: ["A black creature", "A commander", "A creature with flying", "An artifact creature"],
    answer: 0,
    explain: "“Destroy target nonblack creature.” With a Swamp out you can pay 4 life instead of its mana cost. <i-c>Watery Grave</i-c>, <i-c>Sunken Hollow</i-c> and <i-c>Undercity Sewers</i-c> are Swamps too.",
    cards: ["Snuff Out"] },
  { id: "c-swan", topic: "cards",
    q: "What can <i-c>Swan Song</i-c> counter?",
    options: ["Any spell", "An enchantment, instant or sorcery spell", "Creature spells only", "Artifact spells"],
    answer: 1,
    explain: "Its controller gets a 2/2 flying Bird. It can't touch creatures or artifacts.",
    cards: ["Swan Song"] },
  { id: "c-dominance", topic: "cards",
    q: "What does <i-c>Kindred Dominance</i-c> do?",
    options: ["Destroys all creatures of the chosen type", "Destroys all creatures that aren't of the chosen type", "Exiles all opponents' creatures", "Gives the chosen type +2/+2"],
    answer: 1,
    explain: "Choose Assassin and most of your team lives. With a type-changer out, so do your stolen 2/2s. In the bot games it measured +0.8 / +0.7 over a basic land, confirmed over 5,040 games.",
    cards: ["Kindred Dominance"] },

  /* ---------- rules ---------- */
  { id: "r-cloak", topic: "rules",
    q: "What is a cloaked card?",
    options: ["A face-down 2/2 creature with ward {2}", "A face-down 1/1 with hexproof", "An exiled card you may cast", "A face-down 2/2 with no abilities at all, like a manifest"],
    answer: 0,
    explain: "Cloak puts the card onto the battlefield face down as a 2/2 with ward {2}. A manifested card is a plain 2/2 without ward." },
  { id: "r-cloak-flip", topic: "rules",
    q: "A card you cloaked is a creature card. How can you turn it face up?",
    options: ["Only with Etrata's ability", "For its mana cost, any time you have priority, as a special action, or with Etrata's {2}{U}{B}", "Only at sorcery speed", "It can't be turned face up"],
    answer: 1,
    explain: "Its own mana cost works, and it's a special action: no stack, no response. Etrata's ability uses the stack but needs no colors from the card, so it's the way to flip a stolen green or white creature.",
    cards: ["Etrata, Deadly Fugitive"] },
  { id: "r-noncreature", topic: "rules",
    q: "You use Etrata's ability on a face-down card that turns out to be an opponent's instant. What happens?",
    options: ["It turns face up and stays on the battlefield", "It goes to your hand", "It's exiled and you may cast it without paying its mana cost", "It goes back to its owner's hand"],
    answer: 2,
    explain: "An instant can't be turned face up, so you exile it and may cast it right away for free. Their removal or counter works for you.",
    cards: ["Etrata, Deadly Fugitive"] },
  { id: "r-stack", topic: "rules",
    q: "Does Etrata's {2}{U}{B} flip use the stack?",
    options: ["No, it's a special action", "Yes: it's an activated ability, opponents can respond", "Only for instants", "Only on your turn"],
    answer: 1,
    explain: "It's an activated ability of the face-down creature. Opponents can respond, for example by removing it. A creature card's own mana-cost flip is the one that doesn't use the stack." },
  { id: "r-owner", topic: "rules",
    q: "A card you cloaked from an opponent's library dies. Where does it go?",
    options: ["Your graveyard", "Exile", "Its owner's graveyard", "The bottom of your library"],
    answer: 2,
    explain: "You control it but they own it. Cards go to their owner's graveyard. If that player leaves the game, the card leaves with them." },
  { id: "r-rift", topic: "rules",
    q: "You overload <i-c>Cyclonic Rift</i-c>. What happens to the face-down cards you stole?",
    options: ["They go back to their owners' hands", "They stay: Rift only hits permanents you don't control", "They're exiled", "They turn face up"],
    answer: 1,
    explain: "Rift returns each nonland permanent you don't control. You control the cloaks.",
    cards: ["Cyclonic Rift"] },
  { id: "r-faceup-etb", topic: "rules",
    q: "You turn face up a stolen creature that has an “enters” trigger. Does it trigger?",
    options: ["Yes", "Only if you paid its mana cost", "No: turning face up isn't entering the battlefield", "Only with Etrata's ability"],
    answer: 2,
    explain: "The permanent was already on the battlefield. “When turned face up” abilities do trigger." },
  { id: "r-etrata-same-turn", topic: "rules",
    q: "You cast Etrata in your first main phase. <i-c>Changeling Outcast</i-c> attacks and connects. Does Etrata cloak?",
    options: ["Yes: her trigger doesn't need her to attack, so summoning sickness doesn't matter", "No, she needs haste", "Only if she attacks too", "Only next turn"],
    answer: 0,
    explain: "That's rule 2 of the plan: cast her the turn an Assassin is getting through, before combat.",
    cards: ["Changeling Outcast"] },
  { id: "r-tetsuko-pumped", topic: "rules",
    q: "Choose all that apply: <i-c>Tetsuko Umezawa, Fugitive</i-c> and <i-c>Ramses, Assassin Lord</i-c> are out. Which of these can be blocked?",
    options: ["Etrata (2/5 with Ramses)", "<i-c>Changeling Outcast</i-c> (2/2)", "<i-c>Slither Blade</i-c> (1/2)", "<i-c>Hired Poisoner</i-c> (2/2)"],
    answer: [0, 3],
    explain: "Ramses pumps other Assassins: Etrata becomes 2/5 and the Poisoner 2/2, so neither has power or toughness 1 or less and Tetsuko no longer covers them. The Outcast and Slither Blade can't be blocked by their own text. <i-c>Quietus Spike</i-c> adds no power, so it keeps Tetsuko's evasion.",
    cards: ["Tetsuko Umezawa, Fugitive", "Ramses, Assassin Lord", "Hired Poisoner"] },
  { id: "r-veil", topic: "rules",
    q: "<i-c>Teferi's Veil</i-c> is out and you attack. When do your attackers come back?",
    options: ["At the end of the turn", "At the beginning of the next player's turn", "In your next untap step, before you untap", "Never: they're exiled"],
    answer: 2,
    explain: "They phase out at end of combat and phase in during your next untap step. While phased out they're treated as though they don't exist: the other players' wraths miss them. They can't block either.",
    cards: ["Teferi's Veil"] },
  { id: "r-veil-lethal", topic: "rules",
    q: "A blocker deals lethal damage to your attacker. Does <i-c>Teferi's Veil</i-c> save it?",
    options: ["Yes, it phases out first", "No: the Veil triggers at end of combat, after combat damage", "Only if it has deathtouch", "Only on your turn"],
    answer: 1,
    explain: "Teferi's Veil ruling: the trigger happens after combat damage. Creatures dealt lethal damage die first.",
    cards: ["Teferi's Veil"] },
  { id: "r-monument-sac", topic: "rules",
    q: "<i-c>Eldrazi Monument</i-c>'s upkeep trigger resolves and you control creatures. Can you sacrifice the Monument instead?",
    options: ["Yes, always", "Only if you have one creature", "No: you must sacrifice a creature if you have one", "Only on an opponent's turn"],
    answer: 2,
    explain: "The Monument goes only if you can't sacrifice a creature (Monument ruling). A stolen face-down 2/2 is the usual payment.",
    cards: ["Eldrazi Monument"] },
  { id: "r-monument-wrath", topic: "rules",
    q: "<i-c>Eldrazi Monument</i-c> is out. Which of these still kills your creatures?",
    options: ["A spell that says “destroy all creatures”", "Lethal combat damage", "A spell that gives all creatures -4/-4", "<i-c>Kindred Dominance</i-c>"],
    answer: 2,
    explain: "Indestructible stops destroy effects and lethal damage, not toughness 0 or less, sacrifice or exile.",
    cards: ["Eldrazi Monument"] },
  { id: "r-dominance-facedown", topic: "rules",
    q: "No type-changer is out. You cast <i-c>Kindred Dominance</i-c> naming Assassin. What happens to your face-down 2/2s?",
    options: ["They live: they're Assassins", "They're destroyed: face-down creatures have no creature types", "They turn face up", "They return to their owners"],
    answer: 1,
    explain: "With <i-c>Leyline of Transformation</i-c>, <i-c>Arcane Adaptation</i-c> or <i-c>Roshan, Hidden Magister</i-c> out they're Assassins and live. Without one they die with the opponents' creatures.",
    cards: ["Kindred Dominance"] },
  { id: "r-fierce-zone", topic: "rules",
    q: "Etrata is in the command zone. Is <i-c>Fierce Guardianship</i-c> free?",
    options: ["Yes, she's still your commander", "Only on your turn", "No: you have to control a commander on the battlefield", "Only if you pay 2 life"],
    answer: 2,
    explain: "A commander in the command zone isn't one you control. Same for <i-c>Deadly Rollick</i-c>.",
    cards: ["Fierce Guardianship", "Deadly Rollick"] },
  { id: "r-fon", topic: "rules",
    q: "When can you cast <i-c>Force of Negation</i-c> by exiling a blue card instead of paying {1}{U}{U}?",
    options: ["Any time", "Only on your turn", "Only when it's not your turn", "Only with Etrata out"],
    answer: 2,
    explain: "“If it's not your turn.” On your own turn it costs {1}{U}{U}. <i-c>Force of Will</i-c> (1 life and a blue card) works on any turn and counters creature spells too.",
    cards: ["Force of Negation", "Force of Will"] },

  /* ---------- plan: the nine rules and the game plan ---------- */
  { id: "p-keep", topic: "plan",
    q: "Which opening hand is a keep under rule 1?",
    options: ["Three counterspells and two lands", "Two lands with blue and black, <i-c>Changeling Outcast</i-c>, and Etrata castable on turn 3", "<i-c>Rhystic Study</i-c>, <i-c>Brainstorm</i-c>, <i-c>Preordain</i-c> and one land", "Five lands and two tutors"],
    answer: 1,
    explain: "Mulligan is the default: keep a hand that does something by turn 3. Interaction alone, or draw without development, isn't a keep. In the bot games the rule was worth +1.3 against Bracket 4 and +0.2 against the precons." },
  { id: "p-etrata-when", topic: "plan",
    q: "Rule 2: when does Etrata come down?",
    options: ["Turn 3, always", "When an Assassin connects that turn", "Only with Greaves ready", "After Ramses"],
    answer: 1,
    explain: "Her trigger works the turn she's cast and she's kill-on-sight, so cast her before combat on a turn an Assassin is getting through. Greaves on her as soon as you can. Measured +1.0 against Bracket 4, −0.2 against the precons (bot games)." },
  { id: "p-ramses-first", topic: "plan",
    q: "In the bot games, what did tutoring something other than Ramses first cost?",
    options: ["Nothing measurable", "1 point", "8 to 11 points", "25 points"],
    answer: 2,
    explain: "Rule 3. Generic tutor targets first cost 10.9 against the precons; the kill kit (halvers and Bloodletter) first cost 6.2. Cast Ramses right before combat, with a counter up if you can.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "p-dont-wait", topic: "plan",
    q: "Rule 4: you have Ramses and the mana for him, but no protection. What do you do?",
    options: ["Cast him now", "Wait until <i-c>Lightning Greaves</i-c> can go on him the same turn", "Hold him until his attack is lethal", "Keep him for after a wrath"],
    answer: 0,
    explain: "Holding him until protected cost 3.8 / 4.8 points in the bot games: he lands in fewer games and a turn later. A turn of his anthem and pressure is worth more than the third of his games in which he's removed.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "p-last-counter", topic: "plan",
    q: "Rule 5: you have one counter left. What do you save it for?",
    options: ["The first creature an opponent casts", "Any commander", "The wrath, and removal aimed at Ramses or Etrata", "Card-draw spells"],
    answer: 2,
    explain: "Let single creatures and commanders resolve. Saving the last counter measured +1.0 against the precons in the bot games." },
  { id: "p-veil", topic: "plan",
    q: "Rule 6: <i-c>Teferi's Veil</i-c> is out. How do you attack?",
    options: ["Keep half the team home as blockers", "With everything that gets through", "Only with face-down creatures", "Only with Ramses"],
    answer: 1,
    explain: "The attackers phase out through everyone else's turn, so the wraths miss them. In the bot games Teferi's Veil measured +1.0 and <i-c>Eldrazi Monument</i-c>, which does the same against destroy effects, +1.9.",
    cards: ["Teferi's Veil", "Eldrazi Monument"] },
  { id: "p-mark", topic: "plan",
    q: "Rule 7: Ramses is out. Who do your attackers go at?",
    options: ["Spread evenly over all three", "The player with the most cards in hand", "The player the board kills soonest; the rest hit whoever is open", "Whoever attacked you last"],
    answer: 2,
    explain: "One death is the game. Everything that gets through goes at the mark, and the rest still hit open players, because each Assassin hit is a card. The marking attack brain was worth 3.1 / 1.6 points in the bot games." },
  { id: "p-no-ramses", topic: "plan",
    q: "Rule 7, without Ramses: how do you attack?",
    options: ["Spread the hits", "Kill the weakest player first", "Don't attack until Ramses is out", "Only with Etrata"],
    answer: 0,
    explain: "Without Ramses a single death doesn't win, and a player who leaves the game takes the cards you stole from them. Each hit is a cloak." },
  { id: "p-flip", topic: "plan",
    q: "Rule 8: when do you turn a stolen card face up?",
    options: ["As soon as you can", "Before combat, to attack with it", "Only when it beats the 2/2 it is, after your own spells, never before combat", "Never"],
    answer: 2,
    explain: "A big creature or a free artifact or enchantment is worth it. Stolen instants and sorceries are cast through Etrata's exile clause at the moment they matter. Flipping first cost 1.7 / 0.7 in the bot games." },
  { id: "p-hatred", topic: "plan",
    q: "Rule 9: what did holding five mana for a Hatred-style one-shot do in the bot games?",
    options: ["+5 points", "−0.8 / −0.5: nothing useful", "+1.0", "It won a third of the games"],
    answer: 1,
    explain: "Hatred isn't in the list. Keeping the board home for the crack-back measured +0.2 / +0.4, also nothing. Spend your mana and attack." },
  { id: "p-winrate", topic: "plan",
    q: "In the bot games, how often does the heist closer win against three precons?",
    options: ["25.4%", "68.0%", "47.9%", "40.4%"],
    answer: 2,
    explain: "47.9% ±0.7 over 5,040 games, and 27.5% against three Bracket 4 bots. A fair share in a four-player game is 25%. 40.4% is the snowball list without the loop." },
  { id: "p-rounds", topic: "plan",
    q: "In the bot games, what's the heist closer's average winning round against the precons?",
    options: ["5.0", "9.0", "12.0", "7.0"],
    answer: 1,
    explain: "9.0 against the precons and 8.0 against Bracket 4. Against the precons 31% of its wins came by round 7 and 49% by round 8." },
  { id: "p-ramses-dep", topic: "plan",
    q: "In the bot games against the precons, how often does the deck win when Ramses lands, and when he never does?",
    options: ["56% with him, 38% without", "90% with him, 10% without", "48% either way", "38% with him, 56% without"],
    answer: 0,
    explain: "He lands in 54% of games against the precons (36% against Bracket 4). With him 56% / 44%, without 38% / 18%. When he lands and stays it wins 70% / 48%.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "p-skeptic", topic: "plan",
    q: "Why should you expect a lower win rate at a real Bracket 4 table than the bot numbers?",
    options: ["The bots play too slowly", "Humans kill Ramses faster and hold up more interaction", "The engine doesn't let Etrata cloak", "Real decks have fewer lands"],
    answer: 1,
    explain: "These are bot games: the engine's precons and Bracket 4 bots. What transfers is the ordering of the lists and the piloting rules, not the exact percentages." },
  { id: "p-loop-gain", topic: "plan",
    q: "In the bot games, how much does the heist closer gain over the same deck without the drain loop (the heist snowball) against the precons?",
    options: ["7.5 points", "0.5 points", "20 points", "It loses points"],
    answer: 0,
    explain: "47.9% against 40.4% (27.5% against 23.6% vs Bracket 4), over 5,040 paired games. The closer still makes 64% of its kills by combat and on-hit triggers." },
  { id: "p-dominance-when", topic: "plan",
    q: "When is <i-c>Kindred Dominance</i-c> at its best?",
    options: ["On turn 2", "With a type-changer out, so your stolen 2/2s are Assassins and live", "When you have no creatures", "In response to a wrath"],
    answer: 1,
    explain: "Name Assassin. Your Assassins and changelings live, and with <i-c>Leyline of Transformation</i-c>, <i-c>Arcane Adaptation</i-c> or <i-c>Roshan, Hidden Magister</i-c> the face-down cards are Assassins too. It's a sorcery, so it's your turn.",
    cards: ["Kindred Dominance"] },

  /* ---------- mana ---------- */
  { id: "m-lands", topic: "mana",
    q: "How many lands does the heist closer play?",
    options: ["31", "37", "33", "42"],
    answer: 1,
    explain: "37: 22 nonbasic lands, 8 Islands and 7 Swamps, plus seven nonland fast-mana pieces. That's more than the Bracket 4 sources' 25 to 36, and it's a bot number: the report says a pilot who trusts their counter play can run 35 or 36." },
  { id: "m-fast", topic: "mana",
    q: "Which of these is NOT one of the deck's fast-mana pieces?",
    options: ["<i-c>Chrome Mox</i-c>", "<i-c>Lotus Petal</i-c>", "Mana Vault", "<i-c>Dark Ritual</i-c>"],
    answer: 2,
    explain: "Mana Vault was tested and measured −0.8 / −0.2 in the bot games. The fast mana is <i-c>Sol Ring</i-c>, <i-c>Mox Amber</i-c>, Chrome Mox, Lotus Petal, Dark Ritual, <i-c>Arcane Signet</i-c>, <i-c>Talisman of Dominance</i-c>, plus <i-c>Ancient Tomb</i-c>." },
  { id: "m-amber", topic: "mana",
    q: "What does <i-c>Mox Amber</i-c> need to make mana?",
    options: ["A legendary creature or planeswalker you control", "Any creature", "A legendary land", "Nothing"],
    answer: 0,
    explain: "One mana of a color among your legendary creatures and planeswalkers. The deck has plenty: Etrata, Tetsuko, Satoru, Reno and Rude, Basim, Virtus, Mari, Ramses, Achilles, Roshan, Vito, Sakashima.",
    cards: ["Mox Amber"] },
  { id: "m-darkwater", topic: "mana",
    q: "Your only lands are a Swamp and <i-c>Darkwater Catacombs</i-c>. How much mana can you make?",
    options: ["One: {B}", "Three", "Two: {U}{B}, the Swamp pays the Catacombs' {1}", "None"],
    answer: 2,
    explain: "{1}, {T}: add {U}{B}. Tap the Swamp for the {1}: two mana, both colors.",
    cards: ["Darkwater Catacombs"] },
  { id: "m-river", topic: "mana",
    q: "When does <i-c>River of Tears</i-c> make {B}?",
    options: ["Always", "Only on opponents' turns", "On a turn you played a land", "Only if you control a Swamp"],
    answer: 2,
    explain: "It makes {U}, or {B} if you played a land this turn. On opponents' turns that's {U}.",
    cards: ["River of Tears"] },
  { id: "m-morphic", topic: "mana",
    q: "Does <i-c>Morphic Pool</i-c> enter tapped in Commander?",
    options: ["Yes, always", "No: it enters untapped when you have two or more opponents", "Only on turn 1", "Only if you control no basics"],
    answer: 1,
    explain: "Three opponents is two or more, so it's an untapped dual at a four-player table.",
    cards: ["Morphic Pool"] },
  { id: "m-cavern", topic: "mana",
    q: "<i-c>Cavern of Souls</i-c> named Assassin. What does its colored mana do for Ramses?",
    options: ["Nothing special", "Makes him cost one less", "He can't be countered", "Gives him haste"],
    answer: 2,
    explain: "Mana from Cavern's second ability only casts creature spells of the chosen type, and those can't be countered.",
    cards: ["Cavern of Souls", "Ramses, Assassin Lord"] },
  { id: "m-hq", topic: "mana",
    q: "<i-c>Brotherhood Headquarters</i-c>'s colored mana can't pay for which spell?",
    options: ["Etrata", "<i-c>Ramses, Assassin Lord</i-c>", "<i-c>Kindred Dominance</i-c>", "<i-c>Achilles Davenport</i-c> for its freerunning cost"],
    answer: 2,
    explain: "Its colored mana only casts Assassin spells and spells with freerunning, or activates abilities of Assassin sources. Kindred Dominance is a sorcery. It still taps for {C} for anything.",
    cards: ["Brotherhood Headquarters"] },
  { id: "m-price", topic: "mana",
    q: "What does the heist closer cost, and how many Game Changers does it have?",
    options: ["$1,323.02, 9 Game Changers", "$650, 4 Game Changers", "$2,400, 12 Game Changers", "$1,099, 0 Game Changers"],
    answer: 0,
    explain: "$1,323.02 at Scryfall's cheapest nonfoil prices. The Game Changers: <i-c>Imperial Seal</i-c>, <i-c>Demonic Tutor</i-c>, <i-c>Vampiric Tutor</i-c>, <i-c>Rhystic Study</i-c>, <i-c>Fierce Guardianship</i-c>, <i-c>Ancient Tomb</i-c>, <i-c>Chrome Mox</i-c>, <i-c>Cyclonic Rift</i-c> and <i-c>Force of Will</i-c>." },
  { id: "m-path", topic: "mana",
    q: "You spend <i-c>Path of Ancestry</i-c>'s mana on Ramses. Do you scry 1?",
    options: ["No, only on Etrata", "Yes: he shares the Assassin type with your commander", "Only if he's cast from the command zone", "No, Path only makes colorless"],
    answer: 1,
    explain: "Path scries when its mana casts a creature spell that shares a creature type with your commander. Etrata is a Vampire Assassin. Path enters tapped.",
    cards: ["Path of Ancestry"] },

  /* ---------- rulings: the hard ones ---------- */
  { id: "rl-ramses-late", topic: "rulings",
    q: "<i-c>Hired Poisoner</i-c> attacked a player. In your second main phase you cast Ramses, then finish the drain loop and that player dies. Do you win?",
    options: ["No: Ramses wasn't out when the Assassin attacked", "Yes: Ramses checks whether they were attacked this turn by an Assassin you controlled, not whether he was there", "Only if Ramses attacked", "It's a draw"],
    answer: 1,
    explain: "The condition looks back over the turn. Ramses only has to be on the battlefield when the player loses.",
    cards: ["Ramses, Assassin Lord", "Hired Poisoner"] },
  { id: "rl-ramses-entered-attacking", topic: "rulings",
    q: "A creature is put onto the battlefield attacking (it never was declared as an attacker). Does that count as an Assassin attacking the player for Ramses?",
    options: ["Yes", "No: it didn't attack", "Only if it deals damage", "Only if it's legendary"],
    answer: 1,
    explain: "Ramses ruling: an Assassin that enters attacking didn't “attack”, so it doesn't mark the player.",
    cards: ["Ramses, Assassin Lord"] },
  { id: "rl-spike-math", topic: "rulings",
    q: "When does <i-c>Quietus Spike</i-c> work out how much life to take?",
    options: ["When the creature attacks", "When blockers are declared", "As the trigger resolves, after combat damage has been dealt", "At end of combat"],
    answer: 2,
    explain: "Quietus Spike ruling: half their life after combat damage, determined as the trigger resolves. Two Spike triggers take half, then half of what's left.",
    cards: ["Quietus Spike"] },
  { id: "rl-bloodletter-lifelink", topic: "rulings",
    q: "Your turn, <i-c>Bloodletter of Aclazotz</i-c> out. A 1/1 with lifelink deals combat damage to an opponent. What happens?",
    options: ["They lose 2, you gain 2", "They lose 2, you gain 1", "They lose 1, you gain 1", "They lose 1, you gain 2"],
    answer: 1,
    explain: "Bloodletter ruling: it doubles the life lost, not the damage dealt. Lifelink gains the damage, 1. <i-c>Exquisite Blood</i-c> would gain the 2 they lost.",
    cards: ["Bloodletter of Aclazotz"] },
  { id: "rl-greaves-spike", topic: "rulings",
    q: "Ramses wears <i-c>Lightning Greaves</i-c>. Can you equip <i-c>Quietus Spike</i-c> to him?",
    options: ["Yes, equip ignores shroud", "No: equip targets, and shroud stops your targets too. Move the Greaves off first", "Only on your turn", "Yes, because you control both"],
    answer: 1,
    explain: "Shroud means no player can target him. Equip is “attach to target creature you control”. Equip Greaves to another creature ({0}), then equip the Spike, or put the Spike on something else.",
    cards: ["Lightning Greaves", "Quietus Spike"] },
  { id: "rl-polarity-own", topic: "rulings",
    q: "Your <i-c>Exquisite Blood</i-c> is on the stack and an opponent casts a counter on it. You cast <i-c>Reverse the Polarity</i-c> choosing “counter all other spells”. What happens to Exquisite Blood?",
    options: ["It resolves", "It's countered too: the mode counters every other spell, yours included", "It's exiled", "It returns to your hand"],
    answer: 1,
    explain: "The mode doesn't target and doesn't choose: every other spell on the stack is countered. Use a targeted counter to protect your own spell.",
    cards: ["Reverse the Polarity", "Exquisite Blood"] },
  { id: "rl-dominance-two", topic: "rulings",
    q: "Can you name two creature types with <i-c>Kindred Dominance</i-c>, like “Vampire Assassin”?",
    options: ["Yes, any two", "Only Vampire and Assassin together", "No: you choose one existing creature type", "Only types on your commander"],
    answer: 2,
    explain: "Kindred Dominance ruling: one type. And once it starts resolving, nobody can respond after you choose.",
    cards: ["Kindred Dominance"] },
  { id: "rl-adaptation-cloaked", topic: "rulings",
    q: "One of your stolen face-down cards is an opponent's <i-c>Arcane Adaptation</i-c>. What does Etrata's {2}{U}{B} ability do with it?",
    options: ["Turns it face up with no type chosen", "Exiles it and lets you cast it for free: it enters under your control and you choose Assassin", "Nothing, enchantments can't be cloaked", "Returns it to its owner"],
    answer: 1,
    explain: "It isn't a creature card, so it can't be turned face up: you exile it and may cast it without paying its mana cost. Cast, it enters normally, so its “as this enchantment enters, choose a creature type” happens and you name Assassin.",
    cards: ["Arcane Adaptation"] },
  { id: "rl-free-rift", topic: "rulings",
    q: "Etrata's ability exiles a stolen <i-c>Cyclonic Rift</i-c> and you cast it for free. Can you overload it?",
    options: ["Yes, overload is free too", "No: overload is an alternative cost, and a free cast can't use one", "Only if you pay {6}{U}", "Only at an opponent's end step"],
    answer: 1,
    explain: "Casting “without paying its mana cost” rules out other alternative costs like overload. You get the one-target version.",
    cards: ["Cyclonic Rift"] },
  { id: "rl-free-x", topic: "rulings",
    q: "You cast a stolen spell with {X} in its cost for free through Etrata's ability. What is X?",
    options: ["Any number", "0", "The number of face-down creatures you control", "Its mana value"],
    answer: 1,
    explain: "When you cast a spell without paying its mana cost, X is 0. Additional costs (like paying life or sacrificing) are still paid." },
  { id: "rl-cloaked-land", topic: "rulings",
    q: "You use Etrata's ability on a face-down card that turns out to be a land. What happens?",
    options: ["You play it as your land drop", "It turns face up as a land creature", "It goes back to its owner's hand", "It's exiled and stays there: a land can't be cast"],
    answer: 3,
    explain: "It can't be turned face up (not a creature card), so it's exiled; Etrata lets you cast the card, and lands can't be cast." },
  { id: "rl-veil-etrata", topic: "rulings",
    q: "Etrata attacked with <i-c>Teferi's Veil</i-c> out and phased out. A face-down card you control stayed home. Can it use her {2}{U}{B} ability on the next player's turn?",
    options: ["Yes, she's still your commander", "No: while she's phased out she's treated as though she doesn't exist, so she grants nothing", "Only once", "Only if it attacked too"],
    answer: 1,
    explain: "A phased-out permanent's abilities don't work until it phases in during your untap step. If you want flips on other players' turns, keep Etrata home that turn.",
    cards: ["Teferi's Veil"] },
  { id: "rl-fierce-stolen", topic: "rulings",
    q: "Etrata is dead, but you control an opponent's commander you stole. Is <i-c>Fierce Guardianship</i-c> free?",
    options: ["No, it has to be your commander", "Only if it's in the command zone", "Only on your turn", "Yes: any commander you control counts"],
    answer: 3,
    explain: "“If you control a commander” means any commander, including one you've taken (Fierce Guardianship ruling).",
    cards: ["Fierce Guardianship"] },
  { id: "rl-spark-tetsuko", topic: "rulings",
    q: "<i-c>Spark Double</i-c> copies Etrata. With <i-c>Tetsuko Umezawa, Fugitive</i-c> out, can the copy be blocked?",
    options: ["Yes: it's a 2/5 with its +1/+1 counter, too big for Tetsuko", "No, it copies Etrata's 1/4", "No, copies are always unblockable", "Only by fliers"],
    answer: 0,
    explain: "Spark Double enters with an extra +1/+1 counter, so it's 2/5: neither number is 1 or less. The original Etrata (1/4) stays covered.",
    cards: ["Spark Double", "Tetsuko Umezawa, Fugitive"] },
  { id: "rl-amber-facedown", topic: "rulings",
    q: "Your only creatures are face-down cards, one of them secretly a legendary creature. What does <i-c>Mox Amber</i-c> make?",
    options: ["One mana of that legend's color", "{C}", "Nothing: face-down creatures are colorless with no name or supertype", "Two mana"],
    answer: 2,
    explain: "A face-down creature is a nameless, colorless 2/2 with no supertypes.",
    cards: ["Mox Amber"] }
];
