/* Quiz question bank for the Corrupted Etrata deck ("Etrata's Shadow Market v3", Etrata, Deadly Fugitive).
   Each question: { id, topic, q, options, answer (index or array of indices), explain, cards }.
   Topics: combos, tutors, cards, rules, plan, mana, theft, rulings. Card mentions use <i-c>Exact Card Name</i-c>. */
window.CETRATA_QUIZ = [
  /* ---------- combos ---------- */
  { id: "vamp-drain-pick", topic: "combos",
    q: "Which card is a drain for the vampire court loop?",
    options: ["<i-c>Sanguine Bond</i-c>", "<i-c>Vito, Thorn of the Dusk Rose</i-c>", "<i-c>Bloodthirsty Conqueror</i-c>", "<i-c>Marauding Blight-Priest</i-c>"],
    answer: 2,
    explain: "Conqueror and <i-c>Exquisite Blood</i-c> gain you life when an opponent loses life. The other three are payoffs: they make opponents lose life when you gain.",
    cards: ["Bloodthirsty Conqueror", "Exquisite Blood"] },
  { id: "vamp-pairs", topic: "combos",
    q: "How many different two-card pairs make the vampire court loop?",
    options: ["Ten", "Six", "Five", "Seven"],
    answer: 0,
    explain: "Two drains (Exquisite Blood, Bloodthirsty Conqueror) times five payoffs (Blight-Priest, Starscape Cleric, Vito, Sanguine Bond, Enduring Tenacity) is ten pairs." },
  { id: "vamp-not-a-piece", topic: "combos",
    q: "<i-c>Exquisite Blood</i-c> is on the battlefield. Which card does NOT finish the loop with it?",
    options: ["<i-c>Sanguine Bond</i-c>", "<i-c>Marauding Blight-Priest</i-c>", "<i-c>Vito, Thorn of the Dusk Rose</i-c>", "<i-c>Bloodthirsty Conqueror</i-c>"],
    answer: 3,
    explain: "Conqueror is another drain. Two drains just gain you life twice. You need a payoff that makes opponents lose life when you gain.",
    cards: ["Exquisite Blood", "Bloodthirsty Conqueror"] },
  { id: "vamp-starter", topic: "combos",
    q: "<i-c>Exquisite Blood</i-c> and <i-c>Marauding Blight-Priest</i-c> are out. An opponent cracks a fetchland and pays 1 life. What happens?",
    options: ["Nothing, paying life isn't losing life", "Only that opponent loses life once", "The loop starts and every opponent dies", "You gain 1 life and it stops"],
    answer: 2,
    explain: "Paying life is losing life. You gain 1, Blight-Priest makes each opponent lose 1, each of those triggers Exquisite Blood again, and so on until they're all dead.",
    cards: ["Exquisite Blood", "Marauding Blight-Priest"] },
  { id: "vamp-bond-table", topic: "combos",
    q: "With <i-c>Exquisite Blood</i-c> and <i-c>Sanguine Bond</i-c>, the first target opponent dies. What happens to the loop?",
    options: ["It stops, Bond had only one target", "The game is a draw", "It continues, but only you gain life", "It continues: each new Bond trigger can target a living opponent"],
    answer: 3,
    explain: "Each life gain is a new Sanguine Bond trigger with a new target. When one opponent dies, the next trigger targets someone still alive.",
    cards: ["Exquisite Blood", "Sanguine Bond"] },
  { id: "crank-pieces", topic: "combos",
    q: "What does <i-c>Duskmantle Guildmage</i-c>'s {1}{U}{B} ability do?",
    options: ["Target player mills two cards", "Return a card from a graveyard to hand", "Each opponent loses 1 life", "This turn, each card put into an opponent's graveyard makes that player lose 1 life"],
    answer: 3,
    explain: "That's the half that loops with <i-c>Mindcrank</i-c>. The {2}{U}{B} ability is the mill two.",
    cards: ["Duskmantle Guildmage", "Mindcrank"] },
  { id: "crank-loop", topic: "combos",
    q: "The Guildmage is active and <i-c>Mindcrank</i-c> is out. An opponent's sorcery resolves. What happens?",
    options: ["Nothing, a resolving spell doesn't count", "You draw a card", "Every opponent loses 1 life", "That player loses 1 life and mills 1, over and over, until they die"],
    answer: 3,
    explain: "The sorcery card goes to their graveyard: they lose 1. Mindcrank mills 1. That card goes to their graveyard: they lose 1 again. It repeats.",
    cards: ["Mindcrank", "Duskmantle Guildmage"] },
  { id: "crank-one-player", topic: "combos",
    q: "Mindcrank plus the Guildmage starts on one opponent. Who dies?",
    options: ["Everyone at the table, you included", "Every opponent", "Only that opponent, unless the others get their own starter this turn", "Nobody until their next draw"],
    answer: 2,
    explain: "Both triggers name 'that player'. To kill everyone, give each opponent a starter in the same turn, like <i-c>Windfall</i-c>, which makes every opponent with a hand discard." },
  { id: "crank-windfall", topic: "combos",
    q: "Why is <i-c>Windfall</i-c> the best starter for Mindcrank and the Guildmage?",
    options: ["It makes every opponent with a hand discard into their graveyard at once", "It draws you seven cards", "It can't be countered", "It mills every library"],
    answer: 0,
    explain: "Every discarded card hits a graveyard. Every opponent with at least one card in hand starts their own loop.",
    cards: ["Windfall", "Duskmantle Guildmage", "Mindcrank"] },
  { id: "tenacity-dies", topic: "combos",
    q: "<i-c>Enduring Tenacity</i-c> is a creature and dies to removal. What happens?",
    options: ["It's gone for good", "It returns as an enchantment that isn't a creature, and its lifegain trigger still works", "It returns as a 4/3 creature", "It returns to your hand"],
    answer: 1,
    explain: "When it dies as a creature, it comes back as an enchantment. It's still a vampire loop payoff, so creature removal doesn't stop the combo.",
    cards: ["Enduring Tenacity"] },
  { id: "silumgar-etrata-cost", topic: "combos",
    q: "How much does Etrata's ability cost to turn a face-down <i-c>Silumgar Assassin</i-c> face up, without <i-c>Training Grounds</i-c>?",
    options: ["{2}{B}", "{3}", "{U}{B}", "{2}{U}{B}"],
    answer: 3,
    explain: "Etrata's granted ability costs {2}{U}{B}, or {U}{B} with Training Grounds. Its own megamorph cost, {2}{B}, is cheaper and adds a +1/+1 counter.",
    cards: ["Silumgar Assassin"] },
  { id: "cleric-loop", topic: "combos",
    q: "<i-c>Exquisite Blood</i-c> and <i-c>Starscape Cleric</i-c> are out. You gain 1 life. What happens?",
    options: ["Each opponent loses 1 and it stops", "The loop starts and every opponent dies", "Nothing, the Cleric has to attack", "Only one opponent loses life"],
    answer: 1,
    explain: "The Cleric makes each opponent lose 1. Each loss triggers Exquisite Blood, and each gain triggers the Cleric again. It works exactly like Marauding Blight-Priest.",
    cards: ["Starscape Cleric", "Exquisite Blood"] },
  { id: "silumgar-facedown-cost", topic: "combos",
    q: "How much does it cost to cast <i-c>Silumgar Assassin</i-c> face down?",
    options: ["{1}{B}", "{3}", "{2}{U}{B}", "{2}{B}"],
    answer: 1,
    explain: "Any morph or megamorph card can be cast face down as a 2/2 for {3}. {2}{B} is its megamorph cost, to turn it face up." },
  { id: "doubletap-math", topic: "combos",
    q: "<i-c>Bloodletter of Aclazotz</i-c> is out. On your turn, <i-c>Virtus the Veiled</i-c> deals 1 combat damage to a player at 40. Where do they end up?",
    options: ["20", "19", "0", "38"],
    answer: 2,
    explain: "The damage is doubled: 40 to 38. Then the trigger: half of 38 rounded up is 19, doubled to 38. They're at 0.",
    cards: ["Bloodletter of Aclazotz", "Virtus the Veiled"] },
  { id: "doubletap-no-bloodletter", topic: "combos",
    q: "No Bloodletter. <i-c>Virtus the Veiled</i-c> deals 1 combat damage to a player at 40. Where do they end up?",
    options: ["19", "20", "0", "39"],
    answer: 0,
    explain: "40 minus 1 is 39. Half of 39 rounded up is 20. 39 minus 20 is 19." },
  { id: "doubletap-one-player", topic: "combos",
    q: "On your turn, <i-c>Virtus the Veiled</i-c> connects with <i-c>Bloodletter of Aclazotz</i-c> out. Who dies?",
    options: ["Every opponent", "Only the player Virtus hit", "You win the game on the spot", "Nobody, Bloodletter only doubles damage"],
    answer: 1,
    explain: "Virtus's trigger names 'that player', and Bloodletter doubles it to their whole life total. The other opponents need another line: a vampire loop, Mindcrank, or another hit.",
    cards: ["Virtus the Veiled", "Bloodletter of Aclazotz"] },
  { id: "manta-pieces", topic: "combos",
    q: "Which three cards make the infinite-turns loop?",
    options: ["<i-c>Scroll of Fate</i-c>, <i-c>Wormfang Manta</i-c>, <i-c>Crystal Shard</i-c>", "<i-c>Silumgar Assassin</i-c>, <i-c>Hooded Blightfang</i-c>, <i-c>Training Grounds</i-c>", "<i-c>Wormfang Manta</i-c>, <i-c>Otawara, Soaring City</i-c>, <i-c>Necropotence</i-c>", "<i-c>Scroll of Fate</i-c>, <i-c>Wormfang Manta</i-c>, <i-c>Cyclonic Rift</i-c>"],
    answer: 0,
    explain: "The Scroll manifests the Manta, Etrata flips it, the Shard bounces it for an extra turn. Rift and Otawara can't repeat every turn." },
  { id: "manta-cost", topic: "combos",
    q: "With Etrata out and no <i-c>Training Grounds</i-c>, how much mana does each Manta loop cost?",
    options: ["3", "8", "5", "7"],
    answer: 2,
    explain: "{2}{U}{B} for Etrata's flip plus {U} for <i-c>Crystal Shard</i-c>. The Scroll only taps. With Training Grounds it's 3." },
  { id: "manta-cost-tg", topic: "combos",
    q: "Same loop with <i-c>Training Grounds</i-c> out. How much per turn?",
    options: ["2", "5", "4", "3"],
    answer: 3,
    explain: "Etrata's flip drops to {U}{B}. Crystal Shard is an artifact, so it stays {U}. Total 3." },
  { id: "blightfang-trigger", topic: "combos",
    q: "<i-c>Hooded Blightfang</i-c> is out. Etrata attacks and gets blocked. What happens?",
    options: ["Nothing, she has to connect", "Each opponent loses 1 and you gain 1 as she attacks", "Only the blocking player loses 1", "You draw a card"],
    answer: 1,
    explain: "The Blightfang triggers whenever a creature you control with deathtouch attacks, before blockers. Etrata has deathtouch, so the drain happens either way.",
    cards: ["Hooded Blightfang", "Etrata, Deadly Fugitive"] },

  { id: "blightfang-loop", topic: "combos",
    q: "<i-c>Exquisite Blood</i-c>, <i-c>Vito, Thorn of the Dusk Rose</i-c> and <i-c>Hooded Blightfang</i-c> are out. What's the cheapest way to start the loop on your turn?",
    options: ["Cast Windfall", "Attack with any creature that has deathtouch", "Pay {3}{B}{B} for Vito's lifelink", "Cast Toxic Deluge"],
    answer: 1,
    explain: "The Blightfang triggers as a deathtouch creature attacks: each opponent loses 1 and you gain 1. Your gain triggers Vito and their losses trigger Exquisite Blood. No mana needed.",
    cards: ["Hooded Blightfang", "Exquisite Blood", "Vito, Thorn of the Dusk Rose"] },
  { id: "tetsuko-silumgar-counter", topic: "rules",
    q: "<i-c>Tetsuko Umezawa, Fugitive</i-c> is out. Which of your creatures can still be blocked?",
    options: ["<i-c>Virtus the Veiled</i-c>", "<i-c>Etrata, Deadly Fugitive</i-c>", "<i-c>Silumgar Assassin</i-c> with its megamorph counter", "<i-c>Vito, Thorn of the Dusk Rose</i-c>"],
    answer: 2,
    explain: "With its +1/+1 counter Silumgar Assassin is a 3/2: neither number is 1 or less. Virtus (1/1), Etrata (1/4) and Vito (1/3) all have 1 power. Its own text still stops creatures with more power from blocking it.",
    cards: ["Tetsuko Umezawa, Fugitive", "Silumgar Assassin"] },
  /* ---------- tutors ---------- */
  { id: "transmute-cleric", topic: "tutors",
    q: "Which transmute card can find <i-c>Starscape Cleric</i-c>?",
    options: ["<i-c>Drift of Phantasms</i-c>", "<i-c>Muddle the Mixture</i-c>", "<i-c>Dimir House Guard</i-c>", "None of them"],
    answer: 1,
    explain: "Starscape Cleric has mana value 2, like <i-c>Muddle the Mixture</i-c> and <i-c>Shred Memory</i-c>.",
    cards: ["Muddle the Mixture", "Starscape Cleric"] },
  { id: "transmute-mv2", topic: "tutors",
    q: "Which transmute card finds <i-c>Mindcrank</i-c>?",
    options: ["<i-c>Drift of Phantasms</i-c>", "<i-c>Dimir House Guard</i-c>", "<i-c>Shred Memory</i-c>", "None of them"],
    answer: 2,
    explain: "Mindcrank has mana value 2, like <i-c>Shred Memory</i-c> and <i-c>Muddle the Mixture</i-c>." },
  { id: "transmute-drift", topic: "tutors",
    q: "<i-c>Drift of Phantasms</i-c> transmutes for a card with mana value 3. Which of these can it find?",
    options: ["<i-c>Exquisite Blood</i-c>", "<i-c>Bloodletter of Aclazotz</i-c>", "<i-c>Duskmantle Guildmage</i-c>", "<i-c>Scroll of Fate</i-c>"],
    answer: 3,
    explain: "Scroll of Fate costs {3}. Exquisite Blood is 5, Bloodletter 4, the Guildmage 2.",
    cards: ["Drift of Phantasms", "Scroll of Fate"] },
  { id: "transmute-houseguard", topic: "tutors",
    q: "<i-c>Dimir House Guard</i-c> transmutes for mana value 4. Which piece does it find?",
    options: ["<i-c>Bloodletter of Aclazotz</i-c>", "<i-c>Virtus the Veiled</i-c>", "<i-c>Wormfang Manta</i-c>", "<i-c>Tetsuko Umezawa, Fugitive</i-c>"],
    answer: 0,
    explain: "Bloodletter costs {1}{B}{B}{B}, mana value 4. So do Enduring Tenacity, Notion Thief, Beseech the Mirror and Deadly Rollick.",
    cards: ["Dimir House Guard", "Bloodletter of Aclazotz"] },
  { id: "transmute-cant", topic: "tutors",
    q: "Which combo piece can NO transmute card in the deck find?",
    options: ["<i-c>Crystal Shard</i-c>", "<i-c>Exquisite Blood</i-c>", "<i-c>Bloodletter of Aclazotz</i-c>", "<i-c>Duskmantle Guildmage</i-c>"],
    answer: 1,
    explain: "Exquisite Blood has mana value 5. The transmute cards cover 2, 3 and 4 only." },
  { id: "transmute-cant-2", topic: "tutors",
    q: "Which two vampire loop pieces are both out of transmute range?",
    options: ["<i-c>Marauding Blight-Priest</i-c> and <i-c>Vito, Thorn of the Dusk Rose</i-c>", "<i-c>Starscape Cleric</i-c> and <i-c>Enduring Tenacity</i-c>", "<i-c>Exquisite Blood</i-c> and <i-c>Sanguine Bond</i-c>", "<i-c>Starscape Cleric</i-c> and <i-c>Marauding Blight-Priest</i-c>"],
    answer: 2,
    explain: "Both have mana value 5. Spend open tutors on them. Starscape Cleric (2), Blight-Priest and Vito (3) and Enduring Tenacity (4) each have a transmute card." },
  { id: "transmute-speed", topic: "tutors",
    q: "When can you transmute?",
    options: ["Any time you have priority", "Only on an opponent's turn", "Only in your upkeep", "Only as a sorcery: your main phase, empty stack"],
    answer: 3,
    explain: "Every transmute card says 'Transmute only as a sorcery.'" },
  { id: "transmute-cost-black", topic: "tutors",
    q: "Which transmute cards cost {1}{B}{B} to transmute?",
    options: ["<i-c>Shred Memory</i-c> and <i-c>Dimir House Guard</i-c>", "<i-c>Muddle the Mixture</i-c> and <i-c>Drift of Phantasms</i-c>", "<i-c>Muddle the Mixture</i-c> and <i-c>Shred Memory</i-c>", "All four"],
    answer: 0,
    explain: "Shred Memory and Dimir House Guard are black: {1}{B}{B}. Muddle and Drift are blue: {1}{U}{U}." },
  { id: "transmute-chain", topic: "tutors",
    q: "You need <i-c>Exquisite Blood</i-c> and only have <i-c>Muddle the Mixture</i-c>. What's the path?",
    options: ["You can't get it with Muddle", "Transmute Muddle for <i-c>Demonic Tutor</i-c>, then tutor for Exquisite Blood", "Transmute Muddle for Exquisite Blood directly", "Counter your own spell with Muddle"],
    answer: 1,
    explain: "Demonic Tutor has mana value 2, like Muddle. Every transmute card can find an open tutor." },
  { id: "tribute-mage", topic: "tutors",
    q: "What can <i-c>Tribute Mage</i-c> find?",
    options: ["Any creature with mana value 2", "Any card with mana value 2", "An artifact with mana value 2, like <i-c>Mindcrank</i-c> or <i-c>Wishclaw Talisman</i-c>", "Any artifact"],
    answer: 2,
    explain: "Its enters trigger searches for an artifact card with mana value 2. Mindcrank, Wishclaw and the two-mana rocks qualify.",
    cards: ["Tribute Mage", "Mindcrank", "Wishclaw Talisman"] },
  { id: "wishclaw-control", topic: "tutors",
    q: "What happens after you activate <i-c>Wishclaw Talisman</i-c>?",
    options: ["It's sacrificed", "It loses all its counters", "An opponent gains control of it", "Nothing, you keep it"],
    answer: 2,
    explain: "You tutor any card to your hand, then an opponent gains control of the Talisman. Use it on the turn you win." },
  { id: "wishclaw-timing", topic: "tutors",
    q: "When can a player activate <i-c>Wishclaw Talisman</i-c>?",
    options: ["Only during their own turn", "Any time", "Only in their upkeep", "Only during combat"],
    answer: 0,
    explain: "'Activate only during your turn.' An opponent who gets it can use it on their next turn." },
  { id: "beseech-free", topic: "tutors",
    q: "You bargain <i-c>Beseech the Mirror</i-c>. Which card can you cast for free off it?",
    options: ["<i-c>Exquisite Blood</i-c>", "<i-c>Sanguine Bond</i-c>", "<i-c>Wormfang Manta</i-c>", "<i-c>Bloodletter of Aclazotz</i-c>"],
    answer: 3,
    explain: "Bargained Beseech casts the card free if its mana value is 4 or less. Bloodletter is 4. The others go to your hand.",
    cards: ["Beseech the Mirror", "Bloodletter of Aclazotz"] },
  { id: "beseech-bargain", topic: "tutors",
    q: "What can you sacrifice to bargain <i-c>Beseech the Mirror</i-c>?",
    options: ["Any creature", "A card from your hand", "A land", "An artifact, enchantment or token"],
    answer: 3,
    explain: "Bargain is sacrificing an artifact, enchantment or token. Treasures, a rock or a changeling token from <i-c>Black Market Connections</i-c> all work." },
  { id: "symmetry", topic: "tutors",
    q: "What does <i-c>Scheming Symmetry</i-c> do?",
    options: ["You search for two cards", "Target opponent shuffles their library", "Each player searches for a land", "Two target players each search for a card and put it on top"],
    answer: 3,
    explain: "You and the player you pick each put a card on top. Pick an opponent who won't win with it, or one <i-c>Opposition Agent</i-c> is watching." },
  { id: "vampiric-timing", topic: "tutors",
    q: "When is the best time to cast <i-c>Vampiric Tutor</i-c> for a piece you want next turn?",
    options: ["At the end of the turn before yours", "In your main phase", "In your upkeep", "In response to your own draw"],
    answer: 0,
    explain: "It's an instant that puts the card on top. Cast it at the last end step before your turn, and you draw it in your draw step with mana that would untap anyway." },

  /* ---------- cards ---------- */
  { id: "etrata-flip-cost", topic: "cards",
    q: "What does Etrata's granted ability cost?",
    options: ["{1}{U}{B}", "{2}{U}{B}", "{U}{B}", "{3}"],
    answer: 1,
    explain: "{2}{U}{B}. <i-c>Training Grounds</i-c> reduces it to {U}{B}. Etrata herself costs {1}{U}{B}." },
  { id: "etrata-trigger", topic: "cards",
    q: "What triggers Etrata's cloak ability?",
    options: ["Any creature dealing combat damage to an opponent", "A face-down creature turning face up", "Etrata attacking", "An Assassin you control dealing combat damage to an opponent"],
    answer: 3,
    explain: "Only Assassins count. One cloak per Assassin that connects, from the damaged player's library." },
  { id: "etrata-pt", topic: "cards",
    q: "What are Etrata, Deadly Fugitive's power and toughness?",
    options: ["2/2", "4/3", "1/4", "1/1"],
    answer: 2,
    explain: "A 1/4 with deathtouch, which makes her a strong early blocker." },
  { id: "tetsuko-who", topic: "cards",
    q: "Which creature does <i-c>Tetsuko Umezawa, Fugitive</i-c> NOT make unblockable on its own?",
    options: ["<i-c>Virtus the Veiled</i-c>", "<i-c>Vito, Thorn of the Dusk Rose</i-c>", "<i-c>Thief of Sanity</i-c>", "<i-c>Wormfang Manta</i-c>"],
    answer: 2,
    explain: "Tetsuko covers creatures with power or toughness 1 or less. Thief of Sanity is a 2/2. Virtus is 1/1, Vito has 1 power, the Manta has 1 toughness." },
  { id: "outcast", topic: "cards",
    q: "Why is <i-c>Changeling Outcast</i-c> a great turn-1 play here?",
    options: ["It's every creature type, so it's an Assassin, and it can't be blocked", "It makes mana", "It draws a card each turn", "It gives Etrata flying"],
    answer: 0,
    explain: "Changeling makes it an Assassin. It can't be blocked, so it connects every turn and Etrata cloaks every turn." },
  { id: "river-of-tears", topic: "cards",
    q: "When does <i-c>River of Tears</i-c> tap for {B}?",
    options: ["Always", "On a turn you played a land", "Only if you control a Swamp", "Never, it only makes {U}"],
    answer: 1,
    explain: "It makes {U}, or {B} instead if you played a land this turn. On opponents' turns that means {U}.",
    cards: ["River of Tears"] },
  { id: "tainted-isle", topic: "cards",
    q: "What does <i-c>Tainted Isle</i-c> need to tap for {U} or {B}?",
    options: ["An Island", "Nothing", "A Swamp, and Watery Grave counts as one", "Two other lands"],
    answer: 2,
    explain: "Its colored ability works only if you control a Swamp. Basic Swamps, <i-c>Watery Grave</i-c>, <i-c>Sunken Hollow</i-c> and <i-c>Undercity Sewers</i-c> all have the Swamp type. Without one it still taps for {C}.",
    cards: ["Tainted Isle", "Swamp"] },
  { id: "bloodletter-text", topic: "cards",
    q: "What does <i-c>Bloodletter of Aclazotz</i-c> do?",
    options: ["Opponents lose twice as much life during your turn", "Opponents lose twice as much life on every turn", "You gain twice as much life", "Opponents can't gain life"],
    answer: 0,
    explain: "Only during your turn. On opponents' turns, life loss is normal." },
  { id: "silumgar-text", topic: "cards",
    q: "What happens when <i-c>Silumgar Assassin</i-c> is turned face up?",
    options: ["You draw a card", "Destroy target creature with power 3 or less an opponent controls", "Each opponent loses 1 life", "Exile target creature"],
    answer: 1,
    explain: "That's why it's cast face down: a 2/2 blocker that holds instant-speed removal for {2}{B}.",
    cards: ["Silumgar Assassin"] },
  { id: "cleric-block", topic: "cards",
    q: "Why isn't <i-c>Starscape Cleric</i-c> one of your early blockers?",
    options: ["It has defender", "It can't block", "It's a 0/1", "It only blocks fliers"],
    answer: 1,
    explain: "'This creature can't block.' It's a 2-mana loop payoff that attacks in the air. Your blockers are <i-c>Vampire of the Dire Moon</i-c>, <i-c>Hooded Blightfang</i-c>, Etrata and a face-down <i-c>Silumgar Assassin</i-c>.",
    cards: ["Starscape Cleric"] },
  { id: "manta-text", topic: "cards",
    q: "What does <i-c>Wormfang Manta</i-c> do when it leaves the battlefield?",
    options: ["You skip your next turn", "Each opponent skips their next turn", "You take an extra turn after this one", "You draw a card"],
    answer: 2,
    explain: "Leaving gives an extra turn. Entering makes you skip a turn, which is why you manifest it instead." },
  { id: "crystal-shard", topic: "cards",
    q: "What does <i-c>Crystal Shard</i-c>'s cheap mode cost?",
    options: ["{U}, {T}", "{3}, {T}", "{1}", "{U}{U}"],
    answer: 0,
    explain: "{3}, {T} or {U}, {T}: return target creature to its owner's hand unless its controller pays {1}." },
  { id: "free-spells", topic: "cards",
    q: "Which two spells are free while you control your commander?",
    options: ["<i-c>Counterspell</i-c> and <i-c>Swan Song</i-c>", "<i-c>Fierce Guardianship</i-c> and <i-c>Deadly Rollick</i-c>", "<i-c>Shred Memory</i-c> and <i-c>Toxic Deluge</i-c>", "<i-c>Cyclonic Rift</i-c> and <i-c>Dark Ritual</i-c>"],
    answer: 1,
    explain: "Both say 'If you control a commander, you may cast this spell without paying its mana cost.' Etrata has to be on the battlefield." },
  { id: "culling", topic: "cards",
    q: "What does <i-c>Culling the Weak</i-c> make?",
    options: ["{B}{B}{B}", "{B}{B}{B}{B}", "{C}{C}", "One Treasure"],
    answer: 1,
    explain: "{B}{B}{B}{B} for {B} plus a creature. A stolen cloak is the perfect sacrifice." },

  /* ---------- rules ---------- */
  { id: "manifest-manta-etb", topic: "rules",
    q: "You manifest <i-c>Wormfang Manta</i-c> with <i-c>Scroll of Fate</i-c>. Do you skip your next turn?",
    options: ["Yes", "Only if you flip it this turn", "Only if an opponent looks at it", "No, a face-down creature has no abilities as it enters"],
    answer: 3,
    explain: "It enters as a plain 2/2 with no text. The skip trigger doesn't exist." },
  { id: "faceup-not-enter", topic: "rules",
    q: "You turn the manifested Manta face up. Do you skip a turn now?",
    options: ["No, turning face up isn't entering the battlefield", "Yes, it enters again", "Only if you used Etrata's ability", "Only if you paid its mana cost"],
    answer: 0,
    explain: "The permanent was already on the battlefield. Enters triggers never happen when a card is turned face up." },
  { id: "facedown-bounce", topic: "rules",
    q: "You bounce the Manta with <i-c>Crystal Shard</i-c> while it's still face down. Extra turn?",
    options: ["Yes", "No, a face-down creature has no leaves trigger", "Yes, but only after you reveal it", "Only on your turn"],
    answer: 1,
    explain: "Face down, it has no abilities. Turn it face up first, then bounce it." },
  { id: "silumgar-etrata-counter", topic: "rules",
    q: "You turn <i-c>Silumgar Assassin</i-c> face up with Etrata's {2}{U}{B} ability. Does it get the +1/+1 counter?",
    options: ["Yes, always", "No: only the megamorph flip adds the counter, but the destroy trigger still happens", "No, and the destroy trigger doesn't happen either", "Only with Training Grounds"],
    answer: 1,
    explain: "The counter is part of megamorph. 'When turned face up' triggers however it's turned face up.",
    cards: ["Silumgar Assassin", "Etrata, Deadly Fugitive"] },
  { id: "special-action", topic: "rules",
    q: "You turn a morph face up by paying its morph cost. Can opponents respond to the flip?",
    options: ["Yes, with any instant", "No, it's a special action that doesn't use the stack", "Only with a counterspell", "Only if it's a cloak"],
    answer: 1,
    explain: "Natural flips and morph flips are special actions. Opponents can respond to triggers that follow, like <i-c>Silumgar Assassin</i-c>'s, but not to the flip." },
  { id: "etrata-ability-stack", topic: "rules",
    q: "Does Etrata's {2}{U}{B} flip use the stack?",
    options: ["No, it's a special action", "Only for instants and sorceries", "Yes, it's an activated ability", "Only on your turn"],
    answer: 2,
    explain: "It's an activated ability. Opponents can respond, for example by killing the face-down creature." },
  { id: "training-grounds-min", topic: "rules",
    q: "<i-c>Training Grounds</i-c> is out. What does Etrata's flip cost now?",
    options: ["{B}", "{U}{B}", "{2}", "Nothing"],
    answer: 1,
    explain: "It takes off up to {2}, generic only, and never below one mana. {2}{U}{B} becomes {U}{B}." },
  { id: "training-grounds-morph", topic: "rules",
    q: "Does <i-c>Training Grounds</i-c> reduce <i-c>Silumgar Assassin</i-c>'s megamorph cost?",
    options: ["Yes, by {2}", "Yes, to {B}", "Only on your turn", "No, turning a megamorph face up is a special action, not an ability"],
    answer: 3,
    explain: "Training Grounds only affects activated abilities of your creatures." },
  { id: "bloodletter-their-turn", topic: "rules",
    q: "An opponent's own fetchland costs them 1 life on their turn, with <i-c>Bloodletter of Aclazotz</i-c> out. How much do they lose?",
    options: ["1", "2", "0", "Half their life"],
    answer: 0,
    explain: "Bloodletter only doubles during your turn." },
  { id: "virtus-tetsuko", topic: "rules",
    q: "<i-c>Tetsuko Umezawa, Fugitive</i-c> is out and <i-c>Virtus the Veiled</i-c>, a 1/1, attacks. Can it be blocked?",
    options: ["Yes, by fliers", "No: it has power 1, so Tetsuko makes it unblockable", "Only by deathtouch creatures", "Only if Bloodletter isn't out"],
    answer: 1,
    explain: "Tetsuko checks as blockers are declared: power or toughness 1 or less can't be blocked. If something made Virtus a 2/2 by then, use <i-c>Rogue's Passage</i-c> instead.",
    cards: ["Tetsuko Umezawa, Fugitive", "Virtus the Veiled"] },
  { id: "estuary-reveal", topic: "rules",
    q: "Your hand has <i-c>Choked Estuary</i-c> and <i-c>Watery Grave</i-c>, no basics. Can the Estuary enter untapped?",
    options: ["No, only basic lands can be revealed", "Yes: Watery Grave is an Island Swamp card, so you can reveal it", "Only if you pay 2 life", "Only if you already control a Swamp"],
    answer: 1,
    explain: "It asks for an Island or Swamp card, not a basic. Watery Grave has both types. You reveal it and keep it in your hand.",
    cards: ["Choked Estuary", "Watery Grave"] },
  { id: "cloak-owner", topic: "rules",
    q: "A cloak you took from an opponent's library dies. Where does it go?",
    options: ["Your graveyard", "Exile", "Its owner's graveyard", "The bottom of your library"],
    answer: 2,
    explain: "You control it, but the opponent still owns it. Cards go to their owner's graveyard." },
  { id: "rift-cloaks", topic: "rules",
    q: "You overload <i-c>Cyclonic Rift</i-c>. What happens to the cloaks you stole?",
    options: ["They go back to their owners' hands", "They stay: Rift only hits permanents you don't control", "They're exiled", "They turn face up"],
    answer: 1,
    explain: "Rift returns each nonland permanent you don't control. You control the cloaks." },
  { id: "tenacity-twice", topic: "rules",
    q: "<i-c>Enduring Tenacity</i-c> already came back as an enchantment. An opponent destroys it with enchantment removal. Does it return again?",
    options: ["Yes, every time", "No: it wasn't a creature when it went to the graveyard", "Only if Exquisite Blood is out", "Yes, as a creature"],
    answer: 1,
    explain: "It returns only 'if it was a creature'. In its enchantment form it isn't one, so it's gone.",
    cards: ["Enduring Tenacity"] },
  { id: "notion-first-draw", topic: "rules",
    q: "<i-c>Notion Thief</i-c> is out. An opponent draws for their turn. Who gets the card?",
    options: ["You", "Nobody", "They do: the first draw in their draw step is exempt", "They draw two"],
    answer: 2,
    explain: "Only draws other than the first in their draw step are stolen. Windfall's draws are all yours." },
  { id: "free-cast-x", topic: "rules",
    q: "Etrata's ability exiles a cloaked sorcery with {X} in its cost. You cast it for free. What is X?",
    options: ["0", "Any number you choose", "The number of cloaks you control", "Its mana value"],
    answer: 0,
    explain: "When you cast a spell without paying its mana cost, X is 0." },

  /* ---------- plan ---------- */
  { id: "plan-speed", topic: "plan",
    q: "What turns does the deck aim to win on?",
    options: ["Turns 2 to 3", "Turns 6 to 7", "Turns 10 to 12", "Turn 4 every game"],
    answer: 1,
    explain: "The list is built for turn 6 to 7 wins. In the v3 bot games its median win came in round 7 against Bracket 4 tables and round 8 against precons." },
  { id: "plan-sim-turn7", topic: "plan",
    q: "In four-player bot games against three precons, how often does the v3 list win?",
    options: ["25%", "43%", "69%", "90%"],
    answer: 2,
    explain: "69% of 2,400 games, where a fair share is 25%. Against three Bracket 4 decks it wins 43%. The v2 list won 50% and 25%." },
  { id: "plan-most-common", topic: "plan",
    q: "Which line ended the most games in the v2 simulator?",
    options: ["The vampire court", "The double tap", "Manta infinite turns", "Mindcrank and the Guildmage"],
    answer: 3,
    explain: "Mindcrank won 42% of games with answers, then the vampire loop at 23%." },
  { id: "plan-floor", topic: "plan",
    q: "Why are the simulator's numbers called a floor?",
    options: ["It doesn't count stolen cards or most combat damage", "It plays with 41 cards", "It always mulligans", "It ignores tutors"],
    answer: 0,
    explain: "Real games add theft and attacks, which win games the sim scores as slower." },
  { id: "plan-wishclaw-when", topic: "plan",
    q: "When should you use <i-c>Wishclaw Talisman</i-c>?",
    options: ["Turn 2, for a rock", "On the turn you go off", "Whenever you have spare mana", "Only after an opponent uses it"],
    answer: 1,
    explain: "After you use it, an opponent gets it and can tutor on their turn. Win first, so they never get that turn." },
  { id: "plan-etrata-main1", topic: "plan",
    q: "You have an Assassin ready to attack and Etrata in the command zone. When do you cast her?",
    options: ["Second main phase", "At the end of an opponent's turn", "First main phase, before combat", "Never, she's only a blocker"],
    answer: 2,
    explain: "Her trigger works the turn she arrives. Cast after combat and you miss a cloak." },
  { id: "plan-turn3", topic: "plan",
    q: "Real games with the old list punished one turn-3 habit. Which?",
    options: ["Tapping out with no blockers or answers up", "Casting Etrata before combat", "Playing a land", "Holding up Counterspell"],
    answer: 0,
    explain: "Etrata came down late and there were too few blockers. On turn 3, prefer a face-down <i-c>Silumgar Assassin</i-c>, <i-c>Hooded Blightfang</i-c> or Etrata herself, and keep <i-c>Vampire of the Dire Moon</i-c> home.",
    cards: ["Silumgar Assassin", "Hooded Blightfang"] },
  { id: "plan-darkwater", topic: "plan",
    q: "Your only lands are a <i-c>Swamp</i-c> and <i-c>Darkwater Catacombs</i-c>. How much mana can you make?",
    options: ["One: {B}", "Two: {U}{B}, the Swamp's mana pays the Catacombs' {1}", "Three: {B}{U}{B}", "None"],
    answer: 1,
    explain: "The Catacombs need {1} from somewhere else. Tap the Swamp for it and you get {U}{B}: two mana, both colors. Count it as a full land only next to another mana source.",
    cards: ["Darkwater Catacombs", "Swamp"] },
  { id: "plan-symmetry-target", topic: "plan",
    q: "Who should get the other search from <i-c>Scheming Symmetry</i-c>?",
    options: ["The player closest to winning", "Always the player to your left", "The player least likely to win with a tutor, or one <i-c>Opposition Agent</i-c> is watching", "Nobody, it only targets you"],
    answer: 2,
    explain: "It targets two players. With Opposition Agent out, their search becomes yours." },
  { id: "plan-pregame", topic: "plan",
    q: "What should you mention in the pregame talk?",
    options: ["Only that it's Bracket 4", "Nothing, Bracket 4 covers it", "Only the commander", "Two-card infinites and infinite turns"],
    answer: 3,
    explain: "Both are allowed in Bracket 4, but tables like to know. Mention the 9 Game Changers too." },
  { id: "plan-game-changers", topic: "plan",
    q: "How many Game Changers are in the deck?",
    options: ["4", "9", "12", "0"],
    answer: 1,
    explain: "Necropotence, Imperial Seal, Demonic Tutor, Vampiric Tutor, Opposition Agent, Notion Thief, Rhystic Study, Fierce Guardianship and Cyclonic Rift." },
  { id: "plan-crank-others", topic: "plan",
    q: "On your turn, Mindcrank and an active Guildmage can kill one opponent. How do you get the others too?",
    options: ["Pass the turn", "Cast <i-c>Windfall</i-c>: every opponent discards, and each one's loop starts", "Flip a face-down Silumgar Assassin", "Attack the player who's already dead"],
    answer: 1,
    explain: "The Guildmage's effect covers every opponent for the turn, but each loop needs its own starter. Windfall puts cards into every opponent's graveyard at once.",
    cards: ["Mindcrank", "Duskmantle Guildmage", "Windfall"] },

  /* ---------- mana ---------- */
  { id: "mana-mox", topic: "mana",
    q: "What does <i-c>Mox Amber</i-c> need to make mana?",
    options: ["A legendary creature or planeswalker you control", "Any creature", "A legendary land", "Nothing"],
    answer: 0,
    explain: "It makes one mana of a color among your legendary creatures and planeswalkers. Legendary lands don't count." },
  { id: "mana-mox-legends", topic: "mana",
    q: "Which of these is NOT a legend that turns on <i-c>Mox Amber</i-c>?",
    options: ["<i-c>Tetsuko Umezawa, Fugitive</i-c>", "<i-c>Virtus the Veiled</i-c>", "<i-c>Thief of Sanity</i-c>", "<i-c>Vito, Thorn of the Dusk Rose</i-c>"],
    answer: 2,
    explain: "Thief of Sanity isn't legendary. The deck has four legendary creatures: Etrata, Tetsuko, Virtus and Vito." },
  { id: "mana-lands", topic: "mana",
    q: "How many lands does the deck play?",
    options: ["36", "33", "28", "31"],
    answer: 0,
    explain: "36 lands, plus seven rocks and two rituals. v3 went from 31 to 36 after bot games showed the deck was short on mana." },
  { id: "mana-keep", topic: "mana",
    q: "What opening hand does the simulator keep?",
    options: ["Any hand with Etrata's colors", "Three to five lands, or two lands with a rock", "Any hand with a tutor", "Exactly four lands"],
    answer: 1,
    explain: "That's the sim's keep rule. In real games, also look for both colors by turn 3 and something to do." },
  { id: "mana-darkslick", topic: "mana",
    q: "When does <i-c>Darkslick Shores</i-c> enter untapped?",
    options: ["When you control two or more basic lands", "Always", "When you control two or fewer other lands", "When you pay 2 life"],
    answer: 2,
    explain: "It's a fast land: good early, tapped later." },
  { id: "mana-sunken", topic: "mana",
    q: "When does <i-c>Sunken Hollow</i-c> enter untapped?",
    options: ["When you control two or more basic lands", "When you control an Island or a Swamp", "Never", "When you have two or more opponents"],
    answer: 0,
    explain: "Sunken Hollow checks basics. <i-c>Drowned Catacomb</i-c> is the one that checks for an Island or Swamp." },
  { id: "mana-delta", topic: "mana",
    q: "Which land can <i-c>Polluted Delta</i-c> fetch?",
    options: ["<i-c>Darkslick Shores</i-c>", "<i-c>Morphic Pool</i-c>", "<i-c>Underground River</i-c>", "<i-c>Watery Grave</i-c>"],
    answer: 3,
    explain: "It finds an Island or Swamp card. Watery Grave, Sunken Hollow and Undercity Sewers have those types. The others don't." },
  { id: "mana-ritual-necro", topic: "mana",
    q: "Which turn-1 play does <i-c>Dark Ritual</i-c> enable?",
    options: ["<i-c>Necropotence</i-c>", "<i-c>Exquisite Blood</i-c>", "<i-c>Hooded Blightfang</i-c>", "Etrata and a land drop"],
    answer: 0,
    explain: "A Swamp plus Dark Ritual is {B}{B}{B}, exactly Necropotence's cost." },
  { id: "mana-channel", topic: "mana",
    q: "What makes <i-c>Otawara, Soaring City</i-c>'s channel cheaper?",
    options: ["Each Island you control", "Each legendary creature you control", "Each face-down creature", "Nothing"],
    answer: 1,
    explain: "{1} less for each legendary creature you control. Same for <i-c>Takenuma, Abandoned Mire</i-c>." },
  { id: "mana-price", topic: "mana",
    q: "About how much does the deck cost?",
    options: ["$300", "$1,099", "$2,500", "$600"],
    answer: 1,
    explain: "About $1,099, roughly 930€, not counting the seven cards still without a price. <i-c>Imperial Seal</i-c> at $180 is the most expensive card." },

  /* ---------- theft ---------- */
  { id: "theft-agent-mana", topic: "theft",
    q: "You cast a card <i-c>Opposition Agent</i-c> exiled during an opponent's search. What mana can you spend on it?",
    options: ["Only mana of the card's own colors", "Mana as though it were mana of any color", "None: it's cast for free", "Only Treasure mana"],
    answer: 1,
    explain: "Opposition Agent: you may play those cards and spend mana as though it were mana of any color to cast them.",
    cards: ["Opposition Agent"] },
  { id: "theft-thief-mana", topic: "theft",
    q: "<i-c>Thief of Sanity</i-c> exiled a green card. Can you spend blue or black mana on its green symbols?",
    options: ["No, you need green mana", "Yes: you may spend mana as though it were mana of any type", "Only with Etrata out", "Only Treasure mana"],
    answer: 1,
    explain: "Thief of Sanity lets you spend mana as though it were mana of any type to cast that card. <i-c>Opposition Agent</i-c> does the same with any color.",
    cards: ["Thief of Sanity", "Opposition Agent"] },
  { id: "theft-thief", topic: "theft",
    q: "<i-c>Thief of Sanity</i-c> hits a player. What happens to their top three cards?",
    options: ["You take all three", "You exile one to cast, and the other two go to their graveyard", "They're shuffled back", "You draw one"],
    answer: 1,
    explain: "You may cast the exiled card while it stays exiled, with any type of mana." },
  { id: "theft-thief-duration", topic: "theft",
    q: "How long can you cast the card <i-c>Thief of Sanity</i-c> exiles?",
    options: ["Until end of turn", "For as long as it remains exiled", "Until your next turn", "Only during combat"],
    answer: 1,
    explain: "You may look at and cast it for as long as it remains exiled, so you can wait for the right turn." },
  { id: "theft-mutavault", topic: "theft",
    q: "You animate <i-c>Mutavault</i-c> for {1} and it deals combat damage to an opponent. Does Etrata cloak a card?",
    options: ["No: it's a land", "Yes: it has all creature types, so it's an Assassin", "Only if it's also legendary", "Only with Changeling Outcast out"],
    answer: 1,
    explain: "Animated, Mutavault is a 2/2 creature with all creature types, Assassin included. Etrata cloaks the top card of that player's library.",
    cards: ["Mutavault", "Etrata, Deadly Fugitive"] },
  { id: "theft-agent", topic: "theft",
    q: "<i-c>Opposition Agent</i-c> is out. An opponent casts a tutor. What happens to the card they find?",
    options: ["It goes to their hand as usual", "It's exiled and you may play it", "It goes to your hand", "It goes to the bottom of their library"],
    answer: 1,
    explain: "You control them while they search, they exile what they find, and you may play it with mana of any color." },
  { id: "theft-agent-fetch", topic: "theft",
    q: "With <i-c>Opposition Agent</i-c> out, an opponent cracks a fetchland. What happens?",
    options: ["They get the land as usual", "The fetch is countered", "You control the search, the land is exiled, and you may play it", "They lose the game"],
    answer: 2,
    explain: "Any library search counts. Playing the land uses your land drop for the turn." },
  { id: "theft-cloak-instant", topic: "theft",
    q: "Etrata cloaked an opponent's instant. You flip it with her {2}{U}{B} ability. What happens?",
    options: ["It turns face up and stays on the battlefield", "It's exiled and you may cast it without paying its mana cost", "It goes back to its owner's hand", "Nothing: instants can't be cloaked"],
    answer: 1,
    explain: "An instant or sorcery can't be turned face up, so it's exiled and you may cast it for free right away. Their own removal or tutor works for you.",
    cards: ["Etrata, Deadly Fugitive"] },
  { id: "theft-notion-windfall", topic: "theft",
    q: "<i-c>Notion Thief</i-c> is out and you cast <i-c>Windfall</i-c>. What do your opponents end up with?",
    options: ["A new hand of seven", "Their old hands back", "One card each", "No cards in hand"],
    answer: 3,
    explain: "They discard their hands, and every draw they would make goes to you instead." },
  { id: "theft-bmc", topic: "theft",
    q: "Which mode of <i-c>Black Market Connections</i-c> makes a creature, and what does it cost?",
    options: ["A 3/2 changeling for 3 life", "A 2/2 Rogue for 2 life", "A 1/1 Assassin for 1 life", "A 3/2 Mercenary for {3}"],
    answer: 0,
    explain: "A 3/2 colorless Shapeshifter with changeling for 3 life. Changeling makes it an Assassin for Etrata." },
  { id: "theft-cloak-ward", topic: "theft",
    q: "What protects a cloaked creature that a manifested one doesn't have?",
    options: ["Hexproof", "Ward {2}", "Indestructible", "Menace"],
    answer: 1,
    explain: "Cloaks have ward {2}. Manifests and morphs don't, so a face-down Silumgar Assassin dies to any removal." },
  { id: "theft-instant-cast", topic: "theft",
    q: "You flip a stolen cloak with Etrata and it's an opponent's instant. What happens?",
    options: ["It stays face down", "It goes to your hand", "It's exiled and you may cast it for free right away", "It returns to its owner"],
    answer: 2,
    explain: "An instant can't be turned face up, so Etrata's ability exiles it and you may cast it without paying its mana cost." },
  /* ---------- rulings: the hard ones (Gatherer rulings, release notes and the comprehensive rules; see etrata-deck/training/research.md) ---------- */
  { id: "rl-rift-overload", topic: "rulings",
    q: "Etrata's ability exiles a cloaked <i-c>Cyclonic Rift</i-c> and you cast it for free. Can you overload it?",
    options: ["Yes, overload is free too", "No: overload is an alternative cost, and a free cast can't use one", "Only if you pay {6}{U}", "Only on an opponent's end step"],
    answer: 1,
    explain: "Casting “without paying its mana cost” rules out alternative costs like overload (Murders at Karlov Manor release notes; Cyclonic Rift ruling). You get the one-target version.",
    cards: ["Cyclonic Rift", "Etrata, Deadly Fugitive"] },
  { id: "rl-deluge-free", topic: "rulings",
    q: "You cast a cloaked <i-c>Toxic Deluge</i-c> for free off Etrata's ability. What do you pay?",
    options: ["Nothing at all", "X life, for the X you choose", "{2}{B} after all", "X is 0, so it does nothing"],
    answer: 1,
    explain: "Paying X life is an additional cost, not part of the mana cost, so you still choose X and pay that much life (Toxic Deluge ruling). X being 0 applies to {X} in a mana cost only.",
    cards: ["Toxic Deluge"] },
  { id: "rl-cloaked-land", topic: "rulings",
    q: "You activate Etrata's ability on a face-down card that turns out to be a land. What happens?",
    options: ["You play it as your land drop", "It turns face up as a land creature", "It's exiled and stays there: Etrata lets you cast, and lands can't be cast", "It goes back to its owner's hand"],
    answer: 2,
    explain: "It can't be turned face up (not a creature card), so it's exiled; then you “may cast” it, and a land can't be cast. It stays in exile. (Compare Thief of Sanity's ruling: “cast” never lets you play a land.)",
    cards: ["Etrata, Deadly Fugitive"] },
  { id: "rl-simultaneous", topic: "rulings",
    q: "You're at 2 life with <i-c>Exquisite Blood</i-c> out. A spell makes each player lose 3 life. What happens?",
    options: ["You gain 9 first and survive", "You lose before Exquisite Blood's trigger resolves", "It's a draw", "You go to -1 and the loop saves you"],
    answer: 1,
    explain: "You and the opponents lose life at the same time. You're at 0 or less when state-based actions are checked, before the trigger ever resolves (Exquisite Blood ruling).",
    cards: ["Exquisite Blood"] },
  { id: "rl-mindcrank-math", topic: "rulings",
    q: "<i-c>Mindcrank</i-c> and an active <i-c>Duskmantle Guildmage</i-c>. An opponent at 40 life with 25 cards in library loses 1 life. Where do they end up?",
    options: ["Dead now", "Empty library at 14 life: they lose on their next draw", "At 39", "At 0 with 15 cards left"],
    answer: 1,
    explain: "Each life lost mills a card and each card milled costs a life, until the library runs out. They lose 1 + 25 = 26 life and survive at 14 with no library, so they lose when they next draw. The loop only kills outright if their life is no more than their library plus the card that started it.",
    cards: ["Mindcrank", "Duskmantle Guildmage"] },
  { id: "rl-bloodletter-blood", topic: "rulings",
    q: "Your turn. <i-c>Bloodletter of Aclazotz</i-c> and <i-c>Exquisite Blood</i-c> are out. An opponent pays 1 life for a shockland. How much life do you gain?",
    options: ["1", "2", "4", "None: paying life isn't losing it"],
    answer: 1,
    explain: "Paying life is losing life, and on your turn Bloodletter doubles it to 2. Exquisite Blood gains “that much life”: the 2 they actually lost (Bloodletter and Exquisite Blood rulings).",
    cards: ["Bloodletter of Aclazotz", "Exquisite Blood"] },
  { id: "rl-tetsuko-timing", topic: "rulings",
    q: "<i-c>Tetsuko Umezawa, Fugitive</i-c> is out. An opponent blocks your 2/2, then you shrink it to 1/1. What happens?",
    options: ["It becomes unblocked", "It stays blocked: unblockability only matters when blockers are declared", "The blocker is removed from combat", "Combat damage is skipped"],
    answer: 1,
    explain: "Tetsuko's “can't be blocked” is checked once, as blockers are declared. A creature that's already blocked stays blocked (Tetsuko ruling).",
    cards: ["Tetsuko Umezawa, Fugitive"] },
  { id: "rl-blightfang-facedown", topic: "rulings",
    q: "<i-c>Hooded Blightfang</i-c> is out. A face-down <i-c>Silumgar Assassin</i-c> attacks. Does the Blightfang trigger?",
    options: ["Yes", "No: a face-down creature has no abilities, so it doesn't have deathtouch", "Only with Etrata out", "Only if it's blocked"],
    answer: 1,
    explain: "Face down it's a plain 2/2. Silumgar Assassin doesn't have deathtouch face up either, so only Etrata, Virtus, the Conqueror, Vampire of the Dire Moon and the Blightfang trigger it.",
    cards: ["Hooded Blightfang", "Silumgar Assassin"] },
  { id: "rl-cleric-offspring", topic: "rulings",
    q: "You cast <i-c>Starscape Cleric</i-c> with offspring, and both Clerics are out with <i-c>Exquisite Blood</i-c>. You gain 1 life. How much does each opponent lose from the Clerics' first triggers?",
    options: ["1", "2", "0", "3"],
    answer: 1,
    explain: "The offspring token is a 1/1 copy with the same trigger, so both trigger and each opponent loses 1 twice. Each loss then feeds Exquisite Blood, and the loop runs.",
    cards: ["Starscape Cleric", "Exquisite Blood"] },
  { id: "rl-necro-vampiric", topic: "rulings",
    q: "<i-c>Necropotence</i-c> is out. You cast <i-c>Vampiric Tutor</i-c> on your upkeep. When does the card reach your hand?",
    options: ["In your draw step", "At your end step, if you pay 1 life to exile it with Necropotence", "Immediately", "Never"],
    answer: 1,
    explain: "Necropotence makes you skip your draw step, so the card on top isn't drawn. Pay 1 life to exile it face down, and it comes to your hand at your next end step.",
    cards: ["Necropotence", "Vampiric Tutor"] },
  { id: "rl-wishclaw-turn", topic: "rulings",
    q: "You activate <i-c>Wishclaw Talisman</i-c>. Who decides which opponent gets it, and when can they use it?",
    options: ["They roll for it; never", "You choose as it resolves; they can use it on their own turn", "The player to your left; on your turn", "You choose; only after it untaps on your turn"],
    answer: 1,
    explain: "You choose the opponent as the ability resolves. “Activate only during your turn” means its controller's turn, so they can use it on theirs and pass it on (Wishclaw ruling).",
    cards: ["Wishclaw Talisman"] },
  { id: "rl-offer-uncounterable", topic: "rulings",
    q: "You cast <i-c>An Offer You Can't Refuse</i-c> on a spell that can't be countered. What happens?",
    options: ["Offer fizzles and nothing happens", "The spell resolves, but its controller still gets two Treasures", "The spell is countered anyway", "You get the Treasures"],
    answer: 1,
    explain: "The target is legal, so Offer resolves: the countering does nothing but its controller still makes the Treasures (Offer ruling). Swan Song works the same: the Bird is still made.",
    cards: ["An Offer You Can't Refuse", "Swan Song"] },
  { id: "rl-fierce-stolen", topic: "rulings",
    q: "Etrata is dead, but you control an opponent's commander you stole. Is <i-c>Fierce Guardianship</i-c> free?",
    options: ["No, it has to be your commander", "Yes: any commander you control counts", "Only if it's in the command zone", "Only on your turn"],
    answer: 1,
    explain: "“If you control a commander” means any commander, including one you've taken (Fierce Guardianship ruling).",
    cards: ["Fierce Guardianship", "Deadly Rollick"] },
  { id: "rl-fierce-response", topic: "rulings",
    q: "You start casting <i-c>Fierce Guardianship</i-c> for free. Can an opponent kill Etrata in response to make you pay?",
    options: ["Yes, then you pay {2}{U}", "No: once you start casting, no one can act until you finish", "Yes, and the spell is countered", "Only with a split second spell"],
    answer: 1,
    explain: "The check happens while you cast it, and no player gets priority during casting. By the time they can respond, the cost is paid (ruling on Fierce Guardianship and Deadly Rollick).",
    cards: ["Fierce Guardianship"] },
  { id: "rl-two-agents", topic: "rulings",
    q: "You and an opponent each control an <i-c>Opposition Agent</i-c>. A third player searches. Who controls the search?",
    options: ["You, always", "The player whose Agent entered most recently", "Nobody: they cancel out", "The searching player"],
    answer: 1,
    explain: "With two Agents, the most recently entered one wins (Opposition Agent ruling). Flash yours in after theirs.",
    cards: ["Opposition Agent"] },
  { id: "rl-amber-facedown", topic: "rulings",
    q: "Your only creatures are face-down cards (one is secretly a legendary creature). What does <i-c>Mox Amber</i-c> make?",
    options: ["One mana of that legend's color", "Nothing: face-down creatures are colorless with no name or supertype", "{C}", "Two mana"],
    answer: 1,
    explain: "A face-down creature is a nameless, colorless 2/2 with no supertypes. Mox Amber needs a legendary creature or planeswalker with a color.",
    cards: ["Mox Amber"] },
  { id: "rl-river-delta", topic: "rulings",
    q: "You play <i-c>Polluted Delta</i-c> and crack it for a <i-c>Swamp</i-c>. What does <i-c>River of Tears</i-c> make this turn?",
    options: ["{U}: fetching a land isn't playing one", "{B}: you played a land this turn, the Delta", "{U}{B}", "Nothing until next turn"],
    answer: 1,
    explain: "Playing the Delta was your land play, so River of Tears makes {B}. The fetched Swamp wasn't played, but it doesn't need to be.",
    cards: ["River of Tears", "Polluted Delta"] },
  { id: "rl-remora-partial", topic: "rulings",
    q: "<i-c>Mystic Remora</i-c> gets its fourth age counter. You have 3 mana. Can you pay 3 and keep it?",
    options: ["Yes, pay what you can", "No: cumulative upkeep is all or nothing, so you pay 4 or sacrifice it", "Yes, it costs 1 each turn", "Only if an opponent agrees"],
    answer: 1,
    explain: "You pay {1} per age counter, all of it, or sacrifice it. Partial payment isn't allowed (Remora ruling). It's usually kept a turn or two, then sacrificed or bargained to Beseech.",
    cards: ["Mystic Remora", "Beseech the Mirror"] },
  { id: "rl-deluge-entering", topic: "rulings",
    q: "You cast <i-c>Toxic Deluge</i-c> for X = 5. After it resolves, an opponent flashes in a 3/3. Does it die?",
    options: ["Yes, the -5/-5 lasts all turn", "No: it only affects creatures on the battlefield as it resolves", "Only if it's a token", "It gets -5/-5 at end of turn"],
    answer: 1,
    explain: "Toxic Deluge locks in the set of creatures it affects as it resolves (ruling). Later creatures are unaffected.",
    cards: ["Toxic Deluge"] },
  { id: "rl-transmute-rift", topic: "rulings",
    q: "You transmute <i-c>Muddle the Mixture</i-c> (mana value 2). Can it find <i-c>Cyclonic Rift</i-c>?",
    options: ["No, Rift's overload makes it 7", "Yes, Rift's mana value is always 2", "Only if you overload it later", "No, transmute only finds creatures"],
    answer: 1,
    explain: "Overload is an alternative cost; it never changes mana value. Rift is mana value 2 in your library (Rift ruling).",
    cards: ["Muddle the Mixture", "Cyclonic Rift"] },
  { id: "rl-otawara-cost", topic: "rulings",
    q: "You control Etrata and <i-c>Tetsuko Umezawa, Fugitive</i-c>. What does channeling <i-c>Otawara, Soaring City</i-c> cost?",
    options: ["{3}{U}", "{2}{U}", "{1}{U}", "{U}"],
    answer: 2,
    explain: "{3}{U}, minus {1} for each legendary creature you control. Etrata and Tetsuko are both legendary: {1}{U}.",
    cards: ["Otawara, Soaring City", "Tetsuko Umezawa, Fugitive"] },
  { id: "rl-thief-control", topic: "rulings",
    q: "An opponent steals your <i-c>Thief of Sanity</i-c>. Can they cast the cards it exiled while you controlled it?",
    options: ["Yes, the Thief's cards follow it", "No: only you can cast cards exiled while you controlled it", "Only lands", "Only if they pay double"],
    answer: 1,
    explain: "The permission belongs to whoever controlled the Thief when it exiled the card, and lasts after the Thief leaves (Thief of Sanity ruling).",
    cards: ["Thief of Sanity"] }

];
